// Generated by `python -m criciq_api.featured`. Do not edit.
import type { Timeline } from "@/lib/api/types";

export const featuredTimelines: Record<number, () => Promise<Timeline>> = {
  1534217: () => import("./1534217.json").then((m) => m.default as unknown as Timeline),
  1478005: () => import("./1478005.json").then((m) => m.default as unknown as Timeline),
  1428711: () => import("./1428711.json").then((m) => m.default as unknown as Timeline),
  1369591: () => import("./1369591.json").then((m) => m.default as unknown as Timeline),
  1323177: () => import("./1323177.json").then((m) => m.default as unknown as Timeline),
  1269732: () => import("./1269732.json").then((m) => m.default as unknown as Timeline),
};
