// Generated by `python -m criciq_api.featured`. Do not edit.
import type { Timeline } from "@/lib/api/types";

import iplIndex from "./ipl/index.json";
import { featuredTimelines as iplTimelines } from "./ipl/manifest";
import iplSnapshot from "./ipl/snapshot.json";
import bblIndex from "./bbl/index.json";
import { featuredTimelines as bblTimelines } from "./bbl/manifest";
import bblSnapshot from "./bbl/snapshot.json";
import cplIndex from "./cpl/index.json";
import { featuredTimelines as cplTimelines } from "./cpl/manifest";
import cplSnapshot from "./cpl/snapshot.json";
import odiIndex from "./odi/index.json";
import { featuredTimelines as odiTimelines } from "./odi/manifest";
import odiSnapshot from "./odi/snapshot.json";
import pslIndex from "./psl/index.json";
import { featuredTimelines as pslTimelines } from "./psl/manifest";
import pslSnapshot from "./psl/snapshot.json";
import sa20Index from "./sa20/index.json";
import { featuredTimelines as sa20Timelines } from "./sa20/manifest";
import sa20Snapshot from "./sa20/snapshot.json";
import t20iIndex from "./t20i/index.json";
import { featuredTimelines as t20iTimelines } from "./t20i/manifest";
import t20iSnapshot from "./t20i/snapshot.json";

export interface FeaturedBundle {
  index: unknown;
  snapshot: unknown;
  timelines: Record<number, () => Promise<Timeline>>;
}

export const featuredBundles: Record<string, FeaturedBundle> = {
  ipl: { index: iplIndex, snapshot: iplSnapshot, timelines: iplTimelines },
  bbl: { index: bblIndex, snapshot: bblSnapshot, timelines: bblTimelines },
  cpl: { index: cplIndex, snapshot: cplSnapshot, timelines: cplTimelines },
  odi: { index: odiIndex, snapshot: odiSnapshot, timelines: odiTimelines },
  psl: { index: pslIndex, snapshot: pslSnapshot, timelines: pslTimelines },
  sa20: { index: sa20Index, snapshot: sa20Snapshot, timelines: sa20Timelines },
  t20i: { index: t20iIndex, snapshot: t20iSnapshot, timelines: t20iTimelines },
};
