// Generated by `python -m criciq_api.featured`. Do not edit.
import type { Timeline } from "@/lib/api/types";

export const featuredTimelines: Record<number, () => Promise<Timeline>> = {
  1494286: () => import("./1494286.json").then((m) => m.default as unknown as Timeline),
  1449667: () => import("./1449667.json").then((m) => m.default as unknown as Timeline),
  1392685: () => import("./1392685.json").then((m) => m.default as unknown as Timeline),
  1343973: () => import("./1343973.json").then((m) => m.default as unknown as Timeline),
};
