"""Generate the committed data-quality report (docs/data-quality-report.md).

The report is deterministic for a given data version (no timestamps), so it
only changes in git when the data or the checks change.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import duckdb

from criciq_pipelines.validation import ValidationReport

# Sample thresholds used to define "players with a meaningful IPL sample".
MIN_BALLS_FACED = 100
MIN_BALLS_BOWLED = 120


def _table(headers: list[str], rows: list[tuple[Any, ...]]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    for row in rows:
        lines.append("| " + " | ".join("" if v is None else str(v) for v in row) + " |")
    return "\n".join(lines)


def _pct(part: int, whole: int) -> str:
    return f"{part:,} / {whole:,} ({100 * part / whole:.1f}%)" if whole else "0 / 0"


def render_report(warehouse: Path, validation: ValidationReport) -> str:
    con = duckdb.connect(str(warehouse), read_only=True)
    try:
        return _render(con, validation)
    finally:
        con.close()


def _render(con: duckdb.DuckDBPyConnection, validation: ValidationReport) -> str:
    def one(sql: str) -> Any:
        row = con.execute(sql).fetchone()
        return None if row is None else row[0]

    meta = dict(con.execute("SELECT key, value FROM meta").fetchall())
    sections: list[str] = [
        "# Data Quality Report",
        "",
        "_Generated by `criciq-data report`. Do not edit by hand._",
        "",
        f"- **Data version:** `{meta['data_version']}`",
        "- **Source:** [Cricsheet](https://cricsheet.org) IPL ball-by-ball JSON (ODC-BY 1.0)",
        f"- **Overall status:** {'PASS' if validation.passed else 'FAIL'}",
        "",
        "## Contents",
        "",
        _table(
            ["Entity", "Rows"],
            [
                (name, f"{one(f'SELECT count(*) FROM {name}'):,}")
                for name in (
                    "seasons",
                    "franchises",
                    "team_seasons",
                    "venues",
                    "players",
                    "matches",
                    "innings",
                    "deliveries",
                    "wickets",
                    "match_players",
                    "substitutions",
                )
            ],
        ),
        "",
        "## Coverage by season",
        "",
        _table(
            [
                "Season",
                "Matches",
                "Wins",
                "Ties",
                "No result",
                "D/L",
                "Deliveries",
                "Avg 1st-innings score",
            ],
            con.execute(
                """
                SELECT s.year,
                       count(DISTINCT m.match_id),
                       count(DISTINCT m.match_id) FILTER (WHERE m.outcome_type = 'win'),
                       count(DISTINCT m.match_id) FILTER (WHERE m.outcome_type = 'tie'),
                       count(DISTINCT m.match_id) FILTER (WHERE m.outcome_type = 'no_result'),
                       count(DISTINCT m.match_id) FILTER (WHERE m.win_method IS NOT NULL),
                       (SELECT count(*) FROM deliveries d JOIN matches m2 USING (match_id)
                        WHERE m2.season_id = s.season_id),
                       round(avg(i.runs) FILTER (WHERE i.innings_no = 1
                                                   AND m.outcome_type <> 'no_result'
                                                   AND m.win_method IS NULL), 1)
                FROM seasons s JOIN matches m USING (season_id)
                LEFT JOIN innings i USING (match_id)
                GROUP BY s.year, s.season_id ORDER BY s.year
                """
            ).fetchall(),
        ),
        "",
        "Average first-innings scores exclude no-results and rain-affected (D/L) matches.",
        "",
        "## Validation checks",
        "",
        "Schema constraints (primary keys, foreign keys, value domains) are enforced when the",
        "warehouse loads. The checks below cover cricket logic a schema cannot express.",
        "",
        _table(
            ["Check", "Severity", "Status", "Violations", "Rule"],
            [
                (
                    f"`{c.id}`",
                    c.severity,
                    "pass" if c.passed else ("FAIL" if c.severity == "error" else "warn"),
                    c.violations,
                    c.description,
                )
                for c in validation.checks
            ],
        ),
        "",
        "## Golden matches",
        "",
        "Independently known scorecards that the warehouse must reproduce exactly",
        "(`config/golden_matches.yaml`).",
        "",
        _table(
            ["Match", "Description", "Status"],
            [
                (
                    g.match_id,
                    g.description,
                    "pass" if g.passed else "FAIL: " + "; ".join(g.mismatches),
                )
                for g in validation.golden
            ],
        ),
        "",
        "## Recorded anomalies",
        "",
        "These are faithful records of what happened on the field, kept as-is and handled",
        "explicitly downstream.",
        "",
        _table(
            ["Anomaly", "Count", "Handling"],
            [
                (
                    "Overs miscounted by the umpire (5 or 7 legal balls), as recorded by Cricsheet",
                    one("""SELECT coalesce(sum(len(json_keys(miscounted_overs))), 0)
                           FROM innings WHERE miscounted_overs IS NOT NULL"""),
                    "Legal balls are counted, never assumed to be 6 per over",
                ),
                (
                    "Rain-affected results (D/L)",
                    one("SELECT count(*) FROM matches WHERE win_method IS NOT NULL"),
                    "Chase uses the revised target and overs",
                ),
                (
                    "Tied matches decided by super over",
                    one("SELECT count(*) FROM matches WHERE decided_by_super_over"),
                    "Super-over innings flagged `is_super_over`; excluded from models",
                ),
                (
                    "No-result matches",
                    one("SELECT count(*) FROM matches WHERE outcome_type = 'no_result'"),
                    "Kept for display; excluded from outcome models",
                ),
                (
                    "Retired hurt",
                    one("SELECT count(*) FROM wickets WHERE kind = 'retired hurt'"),
                    "Not a dismissal: does not count toward team wickets",
                ),
                (
                    "Penalty runs awarded",
                    one("SELECT count(*) FROM deliveries WHERE extras_penalty > 0"),
                    "Counted in extras and team total",
                ),
                (
                    "Fours run (not boundaries)",
                    one("""SELECT count(*) FROM deliveries
                           WHERE runs_batter = 4 AND NOT is_four"""),
                    "Excluded from boundary counts",
                ),
                (
                    "Impact Player substitutions",
                    one("SELECT count(*) FROM substitutions WHERE reason = 'impact_player'"),
                    "Substitute flagged in `match_players.selection`",
                ),
                (
                    "Concussion substitutions",
                    one(
                        "SELECT count(*) FROM substitutions WHERE reason = 'concussion_substitute'"
                    ),
                    "Substitute flagged in `match_players.selection`",
                ),
                (
                    "Mid-over bowler replacements",
                    one("SELECT count(*) FROM substitutions WHERE kind = 'role'"),
                    "Recorded in `substitutions`",
                ),
            ],
        ),
        "",
        _attribute_section(con),
    ]
    return "\n".join(sections) + "\n"


def _attribute_section(con: duckdb.DuckDBPyConnection) -> str:
    faced = "(SELECT count(*) FROM deliveries d WHERE d.batter_id = p.player_id)"
    bowled = "(SELECT count(*) FROM deliveries d WHERE d.bowler_id = p.player_id)"
    significant = f"""
        SELECT p.* FROM players p
        WHERE {faced} >= {MIN_BALLS_FACED} OR {bowled} >= {MIN_BALLS_BOWLED}
    """
    bowlers = f"SELECT p.* FROM players p WHERE {bowled} >= {MIN_BALLS_BOWLED}"

    def coverage(population: str, column: str) -> str:
        row = con.execute(
            f"SELECT count(*) FILTER (WHERE {column} IS NOT NULL), count(*) FROM ({population})"
        ).fetchone()
        assert row is not None
        return _pct(int(row[0]), int(row[1]))

    everyone = "SELECT * FROM players"
    rows = [
        (label, coverage(everyone, column), coverage(significant, column))
        for label, column in (
            ("Full name", "full_name"),
            ("Date of birth", "date_of_birth"),
            ("Country", "country"),
            ("Batting hand", "batting_hand"),
        )
    ]
    rows.append(
        (
            "Bowling type (pace/spin)",
            coverage(everyone, "bowling_type"),
            coverage(bowlers, "bowling_type") + " of bowlers",
        )
    )
    return "\n".join(
        [
            "## Player attributes",
            "",
            "Cricsheet identifies players but has no biographical attributes. These come from",
            "Wikidata (CC0) and English Wikipedia cricketer infoboxes (CC BY-SA 4.0), linked",
            "through ESPNcricinfo ids, plus a small set of documented manual overrides",
            "(`reference/player_attributes_overrides.csv`). Missing values are left empty rather",
            "than guessed.",
            "",
            f"Players with a meaningful sample: at least {MIN_BALLS_FACED} balls faced or "
            f"{MIN_BALLS_BOWLED} balls bowled.",
            "",
            _table(["Attribute", "All players", "Players with a meaningful sample"], rows),
        ]
    )
