// Generated by `python -m criciq_api.featured`. Do not edit.
import type { Timeline } from "@/lib/api/types";

export const featuredTimelines: Record<number, () => Promise<Timeline>> = {
  1384439: () => import("./1384439.json").then((m) => m.default as unknown as Timeline),
  1144530: () => import("./1144530.json").then((m) => m.default as unknown as Timeline),
  656495: () => import("./656495.json").then((m) => m.default as unknown as Timeline),
  433606: () => import("./433606.json").then((m) => m.default as unknown as Timeline),
  247507: () => import("./247507.json").then((m) => m.default as unknown as Timeline),
  65286: () => import("./65286.json").then((m) => m.default as unknown as Timeline),
  1466428: () => import("./1466428.json").then((m) => m.default as unknown as Timeline),
  1022375: () => import("./1022375.json").then((m) => m.default as unknown as Timeline),
  566948: () => import("./566948.json").then((m) => m.default as unknown as Timeline),
  238200: () => import("./238200.json").then((m) => m.default as unknown as Timeline),
};
