"""Model card and Model Insights data for the ball-outcome model and matchup shrinkage."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from criciq_core import paths
from criciq_ml import registry
from criciq_ml.ball_outcome_training import CANDIDATE_MIN_GAIN
from criciq_ml.report_common import (
    IPL,
    by_competition,
    comparison_section,
    competitions_of,
    fitted_on,
    format_path,
    ipl_card_path,
    phase_labels,
    pooled,
    pooled_path,
    spans_groups,
    write_json,
    write_text,
)
from criciq_ml.report_common import label as competition_label

INSIGHTS_PATH = paths.repo_root() / "frontend" / "data" / "models" / "ball-outcome.json"
MODEL_CARD_PATH = paths.repo_root() / "docs" / "model-cards" / "ball-outcome.md"

OUTCOME_LABELS = {
    "dot": "Dot",
    "one": "1 run",
    "two": "2 runs",
    "three": "3 runs",
    "four": "Four",
    "six": "Six",
    "out": "Wicket",
}
HISTORY_LABELS = {"1-9": "1-9 balls", "10-29": "10-29 balls", "30+": "30 balls or more"}


def insights(version: str) -> dict[str, Any]:
    evaluation = registry.load_evaluation(version, registry.BALL_OUTCOME)
    manifest = json.loads(
        (registry.version_dir(version, registry.BALL_OUTCOME) / "manifest.json").read_text(
            encoding="utf-8"
        )
    )
    test = evaluation["test"]
    return {
        "name": manifest["name"],
        "version": version,
        "data_version": evaluation["data_version"],
        "trained_on": manifest["trained_on"],
        "kappa": manifest["kappa"],
        "player_scale": manifest["player_scale"],
        "splits": evaluation["splits"],
        "outcomes": [{"key": c, "label": OUTCOME_LABELS[c]} for c in evaluation["classes"]],
        "feature_selection": evaluation["feature_selection"],
        "candidate_min_gain": evaluation["tuning"].get("candidate_min_gain", CANDIDATE_MIN_GAIN),
        "phase_players": evaluation["tuning"].get("phase_players", False),
        "test": {
            "model": test["model"],
            "situation_only": test["situation_only"],
            "baseline": test["baseline"],
            "by_phase": test["by_phase"],
            "by_competition": test.get("by_competition", []),
            "calibration": test["calibration"],
            "runs_calibration": test["runs_calibration"],
        },
        "matchups": evaluation["matchups"],
        "backtest": evaluation["backtest"],
        "competition_terms": "competition" in manifest.get("extra_groups", []),
        **(
            {"ipl_comparison": evaluation["ipl_comparison"]}
            if "ipl_comparison" in evaluation
            else {}
        ),
    }


def _f(value: float, digits: int = 4) -> str:
    return f"{value:.{digits}f}"


def _pct(value: float, digits: int = 1) -> str:
    return f"{value * 100:.{digits}f}%"


def _seasons(values: list[int]) -> str:
    return f"{values[0]}-{values[-1]}" if len(values) > 1 else str(values[0])


def _gain(model: float, other: float) -> str:
    return f"{(other - model) / other * 100:.2f}%"


def model_card(data: dict[str, Any]) -> str:
    test = data["test"]
    m, s, b = test["model"], test["situation_only"], test["baseline"]
    mu = data["matchups"]
    splits = data["splits"]
    wins = sum(r["model_log_loss"] < r["baseline_log_loss"] for r in data["backtest"])
    is_pooled = pooled(data)
    period = "years" if is_pooled else "seasons"
    lines = [
        "# Model card: ball outcome and matchup shrinkage",
        "",
        "<!-- Generated by `criciq-ml report` from the model registry. Do not edit by hand. -->",
        "",
        f"**Version** {data['version']} · **data** {data['data_version']} · trained on "
        f"{_seasons(data['trained_on']['seasons'])} ({data['trained_on']['balls']:,} balls)",
        "",
        "## Intended use",
        "",
        "The chance of each outcome on the next ball a batter faces from a bowler, and the",
        "baseline that batter-vs-bowler records in the Matchup Lab are shrunk towards. It is an",
        "estimate for analysis and education. It is not for betting.",
        *(
            [
                "",
                "One model is fitted on "
                + (
                    "every T20 competition at once ("
                    + ", ".join(competition_label(c) for c in competitions_of(data))
                    + ")"
                    if spans_groups(competitions_of(data))
                    else f"{fitted_on(competitions_of(data))} at once"
                )
                + ", so a player who has played in several has one record across them.",
            ]
            if is_pooled
            else []
        ),
        "",
        "## Outcomes and model",
        "",
        "Every ball faced outside super overs (wides are not faced) is one of seven outcomes: a",
        "dot, 1, 2, 3 (with the rare 5), 4, 6, or the batter dismissed by the bowler. Run outs count",
        "as the runs completed.",
        "",
        "A multinomial logistic regression with:",
        "",
        "- the situation: phase and innings, wickets down, balls the batter has faced, batter hand",
        "  against bowler type, and the required rate against par in a chase;",
        "- the scoring era: runs per ball over the competition's previous 60 matches;",
        *(
            [
                "- a term per competition, for what the era does not capture (how the",
                "  competition plays); serving one competition folds its term into the intercept;",
            ]
            if data.get("competition_terms")
            else []
        ),
        "- a coefficient per outcome for every batter and every bowler, penalised towards zero",
        f"  (player one-hots scaled by {data['player_scale']}, so their L2 penalty is"
        f" {1 / data['player_scale'] ** 2:.0f} times the situation terms'). A newcomer starts at",
        "  average and earns an effect ball by ball.",
        "",
        "The fitted model is a table of additive terms, so the API evaluates it with arithmetic",
        "and ships no ML library (ADR-0004).",
        "",
        "## Protocol",
        "",
        f"- **Tuning:** fit on {period} up to {splits['tune_train_through']}, compared on"
        f" {_seasons(splits['tune_valid'])}.",
        f"- **Test:** refit on every {period[:-1]} before {splits['test'][0]}, scored once on"
        f" {_seasons(splits['test'])}.",
        f"- **Backtest:** for each {period[:-1]}, fit on every earlier {period[:-1]} and score it.",
        *(
            ["- Splits are calendar years of the match date (cut-offs on 1 January)."]
            if is_pooled
            else []
        ),
        f"- **Served model:** refit on {_seasons(data['trained_on']['seasons'])} with the tuned"
        " penalty.",
        "",
        f"## Test results ({_seasons(splits['test'])}, {m['balls']:,} balls)",
        "",
        "| Model | Log loss | Brier | Gain vs baseline |",
        "|---|---|---|---|",
        f"| **CricIQ ball model** | **{_f(m['log_loss'])}** | **{_f(m['brier'])}** |"
        f" **{_gain(m['log_loss'], b['log_loss'])}** |",
        f"| Situation only (no players) | {_f(s['log_loss'])} | {_f(s['brier'])} |"
        f" {_gain(s['log_loss'], b['log_loss'])} |",
        f"| Phase and wickets frequencies (last two {period}) | {_f(b['log_loss'])} |"
        f" {_f(b['brier'])} | - |",
        "",
        "Single balls are noisy: the gains are small in absolute terms, as they are for any",
        "ball-by-ball model. Who is batting and bowling adds"
        f" {_gain(m['log_loss'], s['log_loss'])} on top of the situation.",
        "",
        "### Calibration by outcome",
        "",
        "| Outcome | Predicted rate | Observed rate | ECE |",
        "|---|---|---|---|",
    ]
    for key, row in test["calibration"].items():
        lines.append(
            f"| {OUTCOME_LABELS[key]} | {_pct(row['predicted'], 2)} | {_pct(row['observed'], 2)} |"
            f" {_f(row['ece'], 4)} |"
        )
    lines += [
        "",
        f"Expected runs per ball {_f(m['expected_runs'], 3)} against {_f(m['actual_runs'], 3)}"
        " actual.",
        "",
        "### By phase",
        "",
        "| Phase | Balls | Model | Baseline |",
        "|---|---|---|---|",
    ]
    for r in test["by_phase"]:
        lines.append(
            f"| {phase_labels()[r['phase']]} | {r['balls']:,} | {_f(r['model_log_loss'])} |"
            f" {_f(r['baseline_log_loss'])} |"
        )
    if test.get("by_competition"):
        lines += [
            "",
            "### By competition (test)",
            "",
            "| Competition | Balls | Model | Baseline | Gain vs baseline |",
            "|---|---|---|---|---|",
        ]
        for r in by_competition(test["by_competition"]):
            mm, bb = r["model"], r["baseline"]
            lines.append(
                f"| {competition_label(r['competition'])} | {mm['balls']:,} | "
                f"{_f(mm['log_loss'])} | {_f(bb['log_loss'])} | "
                f"{_gain(mm['log_loss'], bb['log_loss'])} |"
            )
        lines += comparison_section(data, "log_loss")
    lines += [
        "",
        "## Backtest",
        "",
        f"Lower log loss than the baseline in {wins} of {len(data['backtest'])} {period}.",
        "",
        f"| {period[:-1].capitalize()} | Balls | Model | Baseline |",
        "|---|---|---|---|",
    ]
    for r in data["backtest"]:
        lines.append(
            f"| {r['season']} | {r['balls']:,} | {_f(r['model_log_loss'])} |"
            f" {_f(r['baseline_log_loss'])} |"
        )
    lines += [
        "",
        "## Head-to-head shrinkage",
        "",
        "A pair's record is shrunk towards what the model expects for those same balls with a",
        "Dirichlet prior. Its strength, kappa, is fitted by maximising the Dirichlet-multinomial",
        "likelihood of every pair's outcome counts (empirical Bayes). History gets weight",
        "`balls / (balls + kappa)`.",
        "",
        f"- **Served kappa:** {data['kappa']:,.0f} balls. A long rivalry is about 160",
        f"  balls, so head-to-head history never carries more than"
        f" {160 / (160 + data['kappa']) * 100:.0f}% of an estimate.",
        f"- **Check on {_seasons(splits['test'])}:** with kappa fitted on earlier {period}"
        f" ({mu['kappa']:,.0f} balls), {mu['all']['balls']:,} test balls between"
        f" {mu['test_pairs']:,} pairs who had met before:",
        "",
        "| History before the test | Balls | Model alone | Shrunk head-to-head | Raw head-to-head |",
        "|---|---|---|---|---|",
    ]
    for r in [*mu["by_history"], {"history": "all", **mu["all"]}]:
        label = HISTORY_LABELS.get(r["history"], "All pairs")
        lines.append(
            f"| {label} | {r['balls']:,} | {_f(r['model'])} | {_f(r['shrunk'])} | {_f(r['raw'])} |"
        )
    lines += [
        "",
        "Raw head-to-head rates predict a pair's future balls far worse than the model;",
        "shrinking them recovers the model's accuracy. Head-to-head records are mostly noise",
        "around what the players' overall records already say.",
        "",
        "## Feature selection",
        "",
        f"A candidate joins the served model only if it cuts validation log loss by at least"
        f" {data['candidate_min_gain'] * 100:.1f}%. Separate per-phase player effects were"
        f" {'kept' if data['phase_players'] else 'not kept'}.",
        "",
        "| Variant | Validation log loss |",
        "|---|---|",
    ]
    for r in data["feature_selection"]:
        lines.append(f"| {r['label']} | {_f(r['log_loss'], 5)} |")
    lines += [
        "",
        "## Limitations",
        "",
        "- No ball tracking: line, length, pace and field settings are not in the data.",
        "- Player effects are career-long: a player's form within a season moves them only slowly.",
        *(
            [
                "- A player's effect is the same in every competition; only the era and the",
                "  competition's term differ between them.",
            ]
            if is_pooled
            else []
        ),
        "- Venue, pitch and dew are not modelled.",
        "- The next-ball odds in the Matchup Lab assume a typical situation (first innings, two or",
        "  three wickets down, a set batter, the current scoring era).",
        "",
    ]
    return "\n".join(lines)


def write_format() -> list[Path]:
    """Another format's current version (see ``report.write_format``)."""
    version = registry.current_version(registry.BALL_OUTCOME)
    if version is None:
        return []
    data = insights(version)
    return [
        write_json(format_path(INSIGHTS_PATH), data),
        write_text(format_path(MODEL_CARD_PATH), model_card(data)),
    ]


def write_all() -> list[Path]:
    default = registry.current_version(registry.BALL_OUTCOME)
    ipl = registry.current_version(registry.BALL_OUTCOME, IPL)
    if default is None or ipl is None:
        return []
    ipl_data = insights(ipl)
    data = ipl_data if default == ipl else insights(default)
    out = [write_json(INSIGHTS_PATH, ipl_data), write_text(MODEL_CARD_PATH, model_card(data))]
    if default != ipl:
        out.append(write_text(ipl_card_path(MODEL_CARD_PATH), model_card(ipl_data)))
    if pooled(data):
        out.append(write_json(pooled_path(INSIGHTS_PATH), data))
    return out
