"""Model card and Model Insights data for the ball-outcome model and matchup shrinkage."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from criciq_core import paths
from criciq_ml import registry
from criciq_ml.ball_outcome_training import CANDIDATE_MIN_GAIN

INSIGHTS_PATH = paths.repo_root() / "frontend" / "data" / "models" / "ball-outcome.json"
MODEL_CARD_PATH = paths.repo_root() / "docs" / "model-cards" / "ball-outcome.md"

OUTCOME_LABELS = {
    "dot": "Dot",
    "one": "1 run",
    "two": "2 runs",
    "three": "3 runs",
    "four": "Four",
    "six": "Six",
    "out": "Wicket",
}
PHASE_LABELS = {
    "powerplay": "Powerplay (overs 1-6)",
    "middle": "Middle (7-15)",
    "death": "Death (16-20)",
}
HISTORY_LABELS = {"1-9": "1-9 balls", "10-29": "10-29 balls", "30+": "30 balls or more"}


def insights(version: str) -> dict[str, Any]:
    evaluation = registry.load_evaluation(version, registry.BALL_OUTCOME)
    manifest = json.loads(
        (registry.version_dir(version, registry.BALL_OUTCOME) / "manifest.json").read_text(
            encoding="utf-8"
        )
    )
    test = evaluation["test"]
    return {
        "name": manifest["name"],
        "version": version,
        "data_version": evaluation["data_version"],
        "trained_on": manifest["trained_on"],
        "kappa": manifest["kappa"],
        "player_scale": manifest["player_scale"],
        "splits": evaluation["splits"],
        "outcomes": [{"key": c, "label": OUTCOME_LABELS[c]} for c in evaluation["classes"]],
        "feature_selection": evaluation["feature_selection"],
        "candidate_min_gain": evaluation["tuning"].get("candidate_min_gain", CANDIDATE_MIN_GAIN),
        "phase_players": evaluation["tuning"].get("phase_players", False),
        "test": {
            "model": test["model"],
            "situation_only": test["situation_only"],
            "baseline": test["baseline"],
            "by_phase": test["by_phase"],
            "calibration": test["calibration"],
            "runs_calibration": test["runs_calibration"],
        },
        "matchups": evaluation["matchups"],
        "backtest": evaluation["backtest"],
    }


def _f(value: float, digits: int = 4) -> str:
    return f"{value:.{digits}f}"


def _pct(value: float, digits: int = 1) -> str:
    return f"{value * 100:.{digits}f}%"


def _seasons(values: list[int]) -> str:
    return f"{values[0]}-{values[-1]}" if len(values) > 1 else str(values[0])


def _gain(model: float, other: float) -> str:
    return f"{(other - model) / other * 100:.2f}%"


def model_card(data: dict[str, Any]) -> str:
    test = data["test"]
    m, s, b = test["model"], test["situation_only"], test["baseline"]
    mu = data["matchups"]
    splits = data["splits"]
    wins = sum(r["model_log_loss"] < r["baseline_log_loss"] for r in data["backtest"])
    lines = [
        "# Model card: ball outcome and matchup shrinkage",
        "",
        "<!-- Generated by `criciq-ml report` from the model registry. Do not edit by hand. -->",
        "",
        f"**Version** {data['version']} · **data** {data['data_version']} · trained on "
        f"{_seasons(data['trained_on']['seasons'])} ({data['trained_on']['balls']:,} balls)",
        "",
        "## Intended use",
        "",
        "The chance of each outcome on the next ball a batter faces from a bowler, and the",
        "baseline that batter-vs-bowler records in the Matchup Lab are shrunk towards. It is an",
        "estimate for analysis and education. It is not for betting.",
        "",
        "## Outcomes and model",
        "",
        "Every ball faced outside super overs (wides are not faced) is one of seven outcomes: a",
        "dot, 1, 2, 3 (with the rare 5), 4, 6, or the batter dismissed by the bowler. Run outs count",
        "as the runs completed.",
        "",
        "A multinomial logistic regression with:",
        "",
        "- the situation: phase and innings, wickets down, balls the batter has faced, batter hand",
        "  against bowler type, and the required rate against par in a chase;",
        "- the scoring era: league runs per ball over the previous 60 matches;",
        "- a coefficient per outcome for every batter and every bowler, penalised towards zero",
        f"  (player one-hots scaled by {data['player_scale']}, so their L2 penalty is"
        f" {1 / data['player_scale'] ** 2:.0f} times the situation terms'). A newcomer starts at",
        "  average and earns an effect ball by ball.",
        "",
        "The fitted model is a table of additive terms, so the API evaluates it with arithmetic",
        "and ships no ML library (ADR-0004).",
        "",
        "## Protocol",
        "",
        f"- **Tuning:** fit on seasons up to {splits['tune_train_through']}, compared on"
        f" {_seasons(splits['tune_valid'])}.",
        f"- **Test:** refit on every season before {splits['test'][0]}, scored once on"
        f" {_seasons(splits['test'])}.",
        "- **Backtest:** for each season, fit on every earlier season and score that season.",
        f"- **Served model:** refit on {_seasons(data['trained_on']['seasons'])} with the tuned"
        " penalty.",
        "",
        f"## Test results ({_seasons(splits['test'])}, {m['balls']:,} balls)",
        "",
        "| Model | Log loss | Brier | Gain vs baseline |",
        "|---|---|---|---|",
        f"| **CricIQ ball model** | **{_f(m['log_loss'])}** | **{_f(m['brier'])}** |"
        f" **{_gain(m['log_loss'], b['log_loss'])}** |",
        f"| Situation only (no players) | {_f(s['log_loss'])} | {_f(s['brier'])} |"
        f" {_gain(s['log_loss'], b['log_loss'])} |",
        f"| Phase and wickets frequencies (last two seasons) | {_f(b['log_loss'])} |"
        f" {_f(b['brier'])} | - |",
        "",
        "Single balls are noisy: the gains are small in absolute terms, as they are for any",
        "ball-by-ball model. Who is batting and bowling adds"
        f" {_gain(m['log_loss'], s['log_loss'])} on top of the situation.",
        "",
        "### Calibration by outcome",
        "",
        "| Outcome | Predicted rate | Observed rate | ECE |",
        "|---|---|---|---|",
    ]
    for key, row in test["calibration"].items():
        lines.append(
            f"| {OUTCOME_LABELS[key]} | {_pct(row['predicted'], 2)} | {_pct(row['observed'], 2)} |"
            f" {_f(row['ece'], 4)} |"
        )
    lines += [
        "",
        f"Expected runs per ball {_f(m['expected_runs'], 3)} against {_f(m['actual_runs'], 3)}"
        " actual.",
        "",
        "### By phase",
        "",
        "| Phase | Balls | Model | Baseline |",
        "|---|---|---|---|",
    ]
    for r in test["by_phase"]:
        lines.append(
            f"| {PHASE_LABELS[r['phase']]} | {r['balls']:,} | {_f(r['model_log_loss'])} |"
            f" {_f(r['baseline_log_loss'])} |"
        )
    lines += [
        "",
        "## Backtest",
        "",
        f"Lower log loss than the baseline in {wins} of {len(data['backtest'])} seasons.",
        "",
        "| Season | Balls | Model | Baseline |",
        "|---|---|---|---|",
    ]
    for r in data["backtest"]:
        lines.append(
            f"| {r['season']} | {r['balls']:,} | {_f(r['model_log_loss'])} |"
            f" {_f(r['baseline_log_loss'])} |"
        )
    lines += [
        "",
        "## Head-to-head shrinkage",
        "",
        "A pair's record is shrunk towards what the model expects for those same balls with a",
        "Dirichlet prior. Its strength, kappa, is fitted by maximising the Dirichlet-multinomial",
        "likelihood of every pair's outcome counts (empirical Bayes). History gets weight",
        "`balls / (balls + kappa)`.",
        "",
        f"- **Served kappa:** {data['kappa']:,.0f} balls. The longest IPL rivalry is about 160",
        f"  balls, so head-to-head history never carries more than"
        f" {160 / (160 + data['kappa']) * 100:.0f}% of an estimate.",
        f"- **Check on {_seasons(splits['test'])}:** with kappa fitted on earlier seasons"
        f" ({mu['kappa']:,.0f} balls), {mu['all']['balls']:,} test balls between"
        f" {mu['test_pairs']:,} pairs who had met before:",
        "",
        "| History before the test | Balls | Model alone | Shrunk head-to-head | Raw head-to-head |",
        "|---|---|---|---|---|",
    ]
    for r in [*mu["by_history"], {"history": "all", **mu["all"]}]:
        label = HISTORY_LABELS.get(r["history"], "All pairs")
        lines.append(
            f"| {label} | {r['balls']:,} | {_f(r['model'])} | {_f(r['shrunk'])} | {_f(r['raw'])} |"
        )
    lines += [
        "",
        "Raw head-to-head rates predict a pair's future balls far worse than the model;",
        "shrinking them recovers the model's accuracy. Head-to-head records are mostly noise",
        "around what the players' overall records already say.",
        "",
        "## Feature selection",
        "",
        f"A candidate joins the served model only if it cuts validation log loss by at least"
        f" {data['candidate_min_gain'] * 100:.1f}%. Separate per-phase player effects were"
        f" {'kept' if data['phase_players'] else 'not kept'}.",
        "",
        "| Variant | Validation log loss |",
        "|---|---|",
    ]
    for r in data["feature_selection"]:
        lines.append(f"| {r['label']} | {_f(r['log_loss'], 5)} |")
    lines += [
        "",
        "## Limitations",
        "",
        "- No ball tracking: line, length, pace and field settings are not in the data.",
        "- Player effects are career-long: a player's form within a season moves them only slowly.",
        "- Venue, pitch and dew are not modelled.",
        "- The next-ball odds in the Matchup Lab assume a typical situation (first innings, two or",
        "  three wickets down, a set batter, the current scoring era).",
        "",
    ]
    return "\n".join(lines)


def write_all() -> list[Path]:
    version = registry.current_version(registry.BALL_OUTCOME)
    if version is None:
        return []
    data = insights(version)
    INSIGHTS_PATH.parent.mkdir(parents=True, exist_ok=True)
    INSIGHTS_PATH.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8", newline="\n")
    MODEL_CARD_PATH.parent.mkdir(parents=True, exist_ok=True)
    MODEL_CARD_PATH.write_text(model_card(data), encoding="utf-8", newline="\n")
    return [INSIGHTS_PATH, MODEL_CARD_PATH]
