"""Model card and Model Insights data for the score projection model."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from criciq_core import paths
from criciq_ml import registry

INSIGHTS_PATH = paths.repo_root() / "frontend" / "data" / "models" / "score-projection.json"
MODEL_CARD_PATH = paths.repo_root() / "docs" / "model-cards" / "score-projection.md"

FEATURE_LABELS = {
    "legal_balls": "Legal balls bowled",
    "balls_remaining": "Balls remaining",
    "wickets": "Wickets lost",
    "runs_vs_par": "Runs above the era's par for this stage",
    "run_rate_rel": "Run rate relative to the era's scoring rate",
    "runs_last_12": "Runs in the last 12 legal balls",
    "wickets_last_12": "Wickets in the last 12 legal balls",
}

CANDIDATE_LABELS = {
    "served": "Served features",
    "+crease": "+ Batters at the crease (career strike rate, average, balls faced)",
    "+depth": "+ Batting still to come (career averages)",
    "+bowling": "+ Bowling still to come (career economy, 4-over quotas)",
    "+venue": "+ Venue scoring index",
}

PHASE_LABELS = {
    "powerplay": "Powerplay (overs 1-6)",
    "middle": "Middle (7-15)",
    "death": "Death (16-20)",
}


def insights(version: str) -> dict[str, Any]:
    evaluation = registry.load_evaluation(version, registry.PROJECTION)
    manifest = json.loads(
        (registry.version_dir(version, registry.PROJECTION) / "manifest.json").read_text(
            encoding="utf-8"
        )
    )
    return {
        "name": manifest["name"],
        "version": version,
        "data_version": evaluation["data_version"],
        "trained_on": manifest["trained_on"],
        "calibrated_on": manifest["calibrated_on"],
        "levels": manifest["levels"],
        "splits": evaluation["splits"],
        "features": [{"key": f, "label": FEATURE_LABELS[f]} for f in manifest["features"]],
        "test": evaluation["test"],
        "feature_selection": [
            {**row, "label": CANDIDATE_LABELS.get(row["variant"], row["variant"])}
            for row in evaluation["feature_selection"]
        ],
        "backtest": evaluation["backtest"],
    }


def _f(value: float, digits: int = 2) -> str:
    return f"{value:.{digits}f}"


def _pct(value: float) -> str:
    return f"{value * 100:.1f}%"


def _seasons(values: list[int]) -> str:
    return f"{values[0]}-{values[-1]}" if len(values) > 1 else str(values[0])


def model_card(data: dict[str, Any]) -> str:
    test, splits = data["test"], data["splits"]
    model, par, rr = test["model"], test["par_baseline"], test["run_rate"]
    served = next(r for r in data["feature_selection"] if r["variant"] == "served")
    better = [
        r
        for r in data["feature_selection"]
        if r["variant"] != "served" and r["pinball"] < served["pinball"] - 0.01
    ]
    trained = data["trained_on"]
    lines = [
        "# Model card: score projection",
        "",
        "<!-- Generated by `criciq-ml report` from the model registry. Do not edit by hand. -->",
        "",
        f"**Version** {data['version']} · **data** {data['data_version']} · served model trained on "
        f"{_seasons(trained['seasons'])} ({trained['innings']:,} complete first innings, "
        f"{trained['rows']:,} match states)",
        "",
        "## What it does",
        "",
        "During a first innings, estimates the distribution of the final total after every ball: "
        "the median, an 80% range and the chance of passing any total. Chases are not projected, "
        "because a chase stops at its target (the win probability covers them). Outputs are "
        "model estimates of historical patterns, not predictions of live matches, and not for "
        "betting.",
        "",
        "## How it works",
        "",
        "- **Target:** the runs still to come, divided by what the scoring era would expect from "
        "the balls left (a rolling league scoring rate). One model then stays valid from 2008 to "
        "2026, while average first-innings totals rose by about 30 runs.",
        "- **Model:** LightGBM quantile regression at the 5, 10, 25, 50, 75, 90 and 95% levels. "
        "Crossing quantiles are sorted.",
        "- **Calibration:** conformal, per level. Each level is shifted by the matching quantile of "
        "its errors on held-out seasons, so that about that share of totals falls below it. The "
        f"served model is calibrated on out-of-fold predictions for {', '.join(map(str, data['calibrated_on']))}.",
        "- **P(total ≥ X)** is read off a piecewise-linear CDF through the quantiles. The CDF starts "
        "at the current score and ends a little beyond the 95% quantile.",
        "- Rain-shortened innings are excluded from training and evaluation and are not projected.",
        "",
        "**Features:** " + "; ".join(f["label"] for f in data["features"]) + ".",
        "",
        "## Evaluation protocol",
        "",
        f"- **Tune** on {_seasons(splits['tune_valid'])}, with candidates trained on seasons up to "
        f"{splits['tune_train_through']}.",
        f"- **Calibrate** on {_seasons(splits['calibrate'])}.",
        f"- **Test** on {_seasons(splits['test'])}, touched once.",
        "- No season does two jobs.",
        "",
        f"## Test results ({model['innings']} first innings, {model['rows']:,} match states)",
        "",
        "| Model | 80% range covers | Range width (runs) | Median error (runs) | Bias (runs) | Pinball | Brier, P(total ≥ X) |",
        "|---|---|---|---|---|---|---|",
    ]
    for label, m in (
        ("**CricIQ projection** (conformal)", model),
        ("Same model, uncalibrated", test["uncalibrated"]),
        ("Par for the era + historical spread", par),
    ):
        lines.append(
            f"| {label} | {_pct(m['coverage80'])} | {_f(m['width80'], 1)} | {_f(m['mae'])} | "
            f"{m['bias']:+.2f} | {_f(m['pinball'], 3)} | {_f(m['threshold_brier'], 3)} |"
        )
    lines += [
        f"| TV-style run-rate projection (point only) | n/a | n/a | {_f(rr['mae'])} | "
        f"{rr['bias']:+.2f} | n/a | n/a |",
        "",
        f"The Brier score averages P(total ≥ X) for X in {', '.join(map(str, test['thresholds']))}. "
        "Bias is the median minus the actual total; positive means the projection ran high.",
        "",
        "### Does each quantile mean what it says? (test)",
        "",
        "| Level | Share of totals at or below it |",
        "|---|---|",
    ]
    for row in model["level_calibration"]:
        lines.append(f"| {row['level']:.0%} | {_pct(row['observed'])} |")
    lines += [
        "",
        "### By phase (test)",
        "",
        "| Phase | States | Median error: model | Par | Run rate | 80% coverage | Range width |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in test["by_phase"]:
        lines.append(
            f"| {PHASE_LABELS[r['phase']]} | {r['rows']:,} | {_f(r['model_mae'])} | {_f(r['par_mae'])} | "
            f"{_f(r['run_rate_mae'])} | {_pct(r['model_coverage80'])} | {_f(r['model_width80'], 1)} |"
        )
    lines += [
        "",
        "## Rolling-origin backtest",
        "",
        "For each season *s*: fit on seasons before *s - 2*, calibrate on *s - 2* and *s - 1*, "
        "test on *s*. This doubles as the **season-bias check**, a watch on the drift in scoring "
        "across the IPL's eras.",
        "",
        "| Season | Innings | Mean total | 80% coverage | Median error | Par median error | Bias |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in data["backtest"]:
        lines.append(
            f"| {r['season']} | {r['innings']} | {_f(r['mean_total'], 1)} | {_pct(r['coverage80'])} | "
            f"{_f(r['mae'])} | {_f(r['par_mae'])} | {r['bias']:+.2f} |"
        )
    wins = sum(r["mae"] < r["par_mae"] for r in data["backtest"])
    biases = [r["bias"] for r in data["backtest"]]
    lines += [
        "",
        f"The projection beats par on median error in {wins} of {len(data['backtest'])} seasons. "
        f"Season bias ranges from {min(biases):+.1f} to {max(biases):+.1f} runs. The scoring-era "
        "adjustment keeps it from drifting in one direction, but a single season can run a few runs "
        "high or low.",
        "",
        "## Feature selection",
        "",
        "Each candidate group was added to the served features and scored by rolling origin on "
        f"{_seasons(served['seasons'])}, never on the test seasons.",
        "",
        (
            "None improved the pinball loss by more than 0.01 runs (well inside season-to-season "
            "noise), so the served model leaves them out."
            if not better
            else "Groups that improved the pinball loss by more than 0.01 runs: "
            + ", ".join(r["label"] for r in better)
            + "."
        ),
        "",
        "| Variant | Pinball | Median error |",
        "|---|---|---|",
    ]
    for r in data["feature_selection"]:
        lines.append(f"| {r['label']} | {_f(r['pinball'], 3)} | {_f(r['mae'])} |")
    coverage = {r["phase"]: r["model_coverage80"] for r in test["by_phase"]}
    lines += [
        "",
        "## Limitations",
        "",
        "- The range is calibrated on average over all balls, so coverage varies by phase: "
        + ", ".join(
            f"{PHASE_LABELS[k].split(' (')[0].lower()} {_pct(v)}" for k, v in coverage.items()
        )
        + " on the test seasons.",
        "- Weather, pitch and team news are not in the data. The model knows the era, not the venue "
        "or the day.",
        "- Innings reduced by rain are not projected.",
        "",
    ]
    return "\n".join(lines)


def write_all() -> list[Path]:
    version = registry.current_version(registry.PROJECTION)
    if version is None:
        return []
    data = insights(version)
    INSIGHTS_PATH.parent.mkdir(parents=True, exist_ok=True)
    INSIGHTS_PATH.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8", newline="\n")
    MODEL_CARD_PATH.parent.mkdir(parents=True, exist_ok=True)
    MODEL_CARD_PATH.write_text(model_card(data), encoding="utf-8", newline="\n")
    return [INSIGHTS_PATH, MODEL_CARD_PATH]
