"""Model card and Model Insights data for CricIQ Ratings and similar players."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from criciq_core import paths
from criciq_core.ratings import MIN_BALLS, MIN_INNINGS, MIN_RATED_BALLS, MIN_SUBSET_BALLS
from criciq_core.style import MIN_PROFILE_BALLS
from criciq_ml import registry

INSIGHTS_PATH = paths.repo_root() / "frontend" / "data" / "models" / "ratings.json"
MODEL_CARD_PATH = paths.repo_root() / "docs" / "model-cards" / "ratings.md"

UNIT_LABELS = {
    "runs_per_100": "runs per 100 balls above par",
    "dismissals_per_100": "dismissals avoided per 100 balls",
    "runs_per_over": "runs saved per over",
    "wickets_per_4_overs": "wickets per 4 overs above par",
    "points": "win probability points per innings",
    "percent": "% of innings at or better than par",
}


def insights(version: str) -> dict[str, Any]:
    evaluation = registry.load_evaluation(version, registry.RATINGS)
    manifest = json.loads(
        (registry.version_dir(version, registry.RATINGS) / "manifest.json").read_text(
            encoding="utf-8"
        )
    )
    return {
        "name": manifest["name"],
        "version": version,
        "data_version": evaluation["data_version"],
        "trained_on": manifest["trained_on"],
        "splits": evaluation["splits"],
        "stability": evaluation["stability"],
        "season_factor": evaluation["season_factor"],
        "thresholds": {
            "min_balls": MIN_BALLS,
            "min_subset_balls": MIN_SUBSET_BALLS,
            "min_innings": MIN_INNINGS,
            "min_rated_balls": MIN_RATED_BALLS,
            "min_profile_balls": MIN_PROFILE_BALLS,
            "style_min_balls": evaluation["style_min_balls"],
        },
        "components": [
            {**c, "unit_label": UNIT_LABELS[c["unit"]]} for c in evaluation["components"]
        ],
        "similarity": evaluation["similarity"],
    }


def _r(value: float | None) -> str:
    return "n/a" if value is None else f"{value:.2f}"


def _pct(value: float | None, digits: int = 1) -> str:
    return "n/a" if value is None else f"{100 * value:+.{digits}f}%"


def _weight(c: dict[str, Any]) -> str:
    sizes = ["300", "1000"] if c["exposure"] == "balls" else ["30", "100"]
    return ", ".join(f"{100 * c['weight_at'][s]:.0f}% at {s}" for s in sizes)


def model_card(data: dict[str, Any]) -> str:
    t = data["thresholds"]
    test_from = data["splits"]["test_from"]
    levels = data["stability"]
    lines = [
        f"# Model card: CricIQ Ratings v{data['version']}",
        "",
        "_Generated by `criciq-ml report` from the registry; do not edit by hand._",
        "",
        "## What a rating is",
        "",
        "A CricIQ Rating says where a player stands among regular IPL players on one thing they",
        "do, over any span of seasons, after allowing for how much their record can be trusted.",
        "Ratings are a profile, never a single verdict: there is no overall number.",
        "",
        "Every component is a sum of per-innings evidence `e` over an exposure `n` (balls or",
        "innings), oriented so higher is better, and measured against **par**: the league rate",
        "for the same season and phase, summed over the player's balls.",
        "",
        "```",
        "record       v   = scale * sum(e) / sum(n)",
        "estimate     v^  = scale * (sum(e) + k * mu) / (sum(n) + k)",
        "uncertainty  se  = scale * sqrt(sigma2 / (sum(n) + k))",
        "rating           = share of qualified players in the window with a lower estimate (0-100)",
        "interval         = the ratings of v^ - 1.645 se and v^ + 1.645 se (90%)",
        "```",
        "",
        f"- `mu` is the average of the qualified players in the window: at least {t['min_balls']}",
        f"  balls in the role, plus {t['min_subset_balls']} balls for a phase or chasing component",
        f"  and {t['min_innings']} innings for an innings component. A record with little evidence",
        "  is assumed to be a typical regular's.",
        "- `k` (per component) is how many balls or innings of that average are blended in. It is",
        "  tuned so a player's shrunk record in one season best predicts their next season.",
        "- `sigma2` is the noise per ball (or innings), pooled from how much a player's innings",
        "  vary within a season. Innings are the units, so streaks within an innings count.",
        f"- Players are rated from {t['min_rated_balls']} balls in the role (with wide intervals);",
        "  only qualified players form the reference the percentile is taken against.",
        "",
        "## Components",
        "",
        "| Role | Component | Measure | k | Weight of own record | Year-to-year r | Odd/even seasons r | Next season vs par | vs raw record | Stability |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for c in data["components"]:
        ns = c["next_season"]
        lines.append(
            f"| {c['role']} | {c['label']} | {c['unit_label']} | {c['k']:.0f} {c['exposure']} "
            f"| {_weight(c)} | {_r(c['year_to_year']['r'])} ({c['year_to_year']['pairs']}) "
            f"| {_r(c['split_half']['r'])} ({c['split_half']['players']}) "
            f"| {_pct(ns.get('skill_vs_par'))} | {_pct(ns.get('skill_vs_raw'))} | {c['stability']} |"
        )
    stable = [c for c in data["components"] if c["stability"] == "high"]
    low = [c for c in data["components"] if c["stability"] == "low"]
    lines += [
        "",
        "- **Year-to-year r**: correlation between a player's ratings in consecutive seasons",
        f"  (both seasons qualified at {data['season_factor']:.0%} of the window thresholds; pairs",
        f"  in brackets). Stability is *high* from {levels['high']}, *moderate* from",
        f"  {levels['moderate']}, otherwise *low*; low components carry a warning in the app.",
        "- **Odd/even seasons r**: correlation between a player's raw record in odd and in even",
        f"  seasons ({t['min_balls']}+ balls in each half; players in brackets): how reliable a",
        "  career-length record is.",
        f"- **Next season**: `k` re-tuned on season pairs before {test_from}, then each season from",
        f"  {test_from} on predicted from the one before. The figures are the cut in squared error",
        "  against predicting par for everyone, and against trusting the raw record.",
        "",
        "## What the evaluation shows",
        "",
        "- Shrinking always helps: for every component the shrunk record predicts a player's next",
        "  season better than the raw record (the promotion gate).",
        "- Persistent skills: "
        + ", ".join(f"{c['role']} {c['label'].lower()}" for c in stable)
        + ".",
        "- Mostly luck within a season: "
        + ", ".join(f"{c['role']} {c['label'].lower()}" for c in low)
        + ". Their ratings are shown with a low-stability warning; over a whole career they",
        "  still say something (see the odd/even column).",
        "- Wicket-taking against par is the weakest component: the record has to reach thousands",
        "  of balls before it outweighs the average, while economy against par is among the",
        "  most persistent. Runs conceded say more about a bowler than wickets do.",
        "",
        "## Similar players",
        "",
        "A style profile is a handful of per-ball rates against par and usage shares, z-scored",
        "within the qualified players of the window; two players are similar when their profiles",
        f"point the same way (cosine similarity). Profiles need {t['min_profile_balls']} balls, and",
        f"candidates {t['min_balls']}.",
        "",
    ]
    for role, s in data["similarity"].items():
        features = ", ".join(f["label"].lower() for f in s["features"])
        lines += [
            f"- **{role.capitalize()}** ({features}): from a player's profile in one season, the",
            f"  same player is the closest of next season's {s['candidates_median']} profiles"
            f" {s['top1']:.0%} of the time and in the top five {s['top5']:.0%}",
            f"  (chance: {s['chance_top1']:.0%} and {s['chance_top5']:.0%}; {s['players']} player-seasons,"
            f" {data['thresholds']['style_min_balls']}+ balls in both). Median rank {s['median_rank']:.0f}.",
        ]
    lines += [
        "",
        "Wicket rate against par was left out of the bowling profile: it barely persists (above),",
        "so it adds noise to the match.",
        "",
        "## Limitations",
        "",
        "- Par adjusts for season and phase only, not venue, match situation or opposition.",
        "- Ratings rank players against the regulars of the same seasons; a rating of 50 in a",
        "  strong era is not the same player as 50 in a weak one.",
        "- Intervals assume the noise per ball is the same for everyone; for impact (win",
        "  probability added), whose size depends on the match situation, they are approximate.",
        "- Ratings describe what happened, adjusted for sample size. They are not forecasts of",
        "  form, fitness or role changes.",
        "",
    ]
    return "\n".join(lines)


def write_all() -> list[Path]:
    version = registry.current_version(registry.RATINGS)
    if version is None:
        return []
    data = insights(version)
    INSIGHTS_PATH.parent.mkdir(parents=True, exist_ok=True)
    INSIGHTS_PATH.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8", newline="\n")
    MODEL_CARD_PATH.parent.mkdir(parents=True, exist_ok=True)
    MODEL_CARD_PATH.write_text(model_card(data), encoding="utf-8", newline="\n")
    return [INSIGHTS_PATH, MODEL_CARD_PATH]
