"""Model card and Model Insights data for the match simulator."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from criciq_core import paths
from criciq_ml import registry

INSIGHTS_PATH = paths.repo_root() / "frontend" / "data" / "models" / "simulator.json"
MODEL_CARD_PATH = paths.repo_root() / "docs" / "model-cards" / "simulator.md"


def insights(version: str) -> dict[str, Any]:
    evaluation = registry.load_evaluation(version, registry.SIMULATOR)
    keep = (
        "name",
        "version",
        "data_version",
        "valid",
        "test",
        "settings",
        "tuning",
        "matches",
        "simulations_per_match",
        "forced_overs",
        "win",
        "chase",
        "first_innings",
        "ties",
        "timing",
    )
    return {k: evaluation[k] for k in keep}


def _seasons(values: list[int]) -> str:
    return f"{min(values)}-{max(values)}" if len(values) > 1 else str(values[0])


def model_card(d: dict[str, Any]) -> str:
    win, chase, first = d["win"], d["chase"], d["first_innings"]
    s = d["settings"]
    gain = win["gain_vs_coin_flip"]
    chase_gain = chase["gain_vs_chase_rate"]
    lines = [
        "# Model card: match simulator",
        "",
        "<!-- Generated by `criciq-ml report` from the model registry. Do not edit by hand. -->",
        "",
        f"**Version** {d['version']} · **data** {d['data_version']} · conditions spread "
        f"{s['conditions_sd']} (tuned on {_seasons(d['valid'])})",
        "",
        "## Intended use",
        "",
        "Monte Carlo simulation of a T20 match between two chosen XIs, and of the rest of a",
        "real match from any ball with an edited score (the replay's what-if sandbox). It shows",
        "distributions (totals, margins, each player's likely contribution) and how they move",
        "when the XI or the score changes. It is labelled a model simulation everywhere; it is",
        "not a forecast and not for betting.",
        "",
        "## How a match is simulated",
        "",
        "Every legal ball: extras from league rates for the innings and phase; the ball faced",
        "from the ball-outcome model (situation, era, striker and bowler; see its model card);",
        "run outs at the league rate. The strike changes on odd runs and at the end of an over.",
        "Each over's bowler is drawn from how often each bowler bowled that over in their last",
        f"{s['history_seasons']} seasons, shrunk toward their type's league pattern (worth "
        f"{s['usage_strength']:g} overs), within the four-over quota, never twice in a row, and",
        "only if the rest of the innings can still be covered. Each simulated match draws its",
        "own conditions (how good the pitch and ground are for batting), shared by both innings,",
        f"with a spread of {s['conditions_sd']} on the log-odds scale, the value with the lowest",
        "first-innings CRPS on the validation seasons:",
        "",
        "| Spread | CRPS | 80% coverage | Brier |",
        "|---|---|---|---|",
        *[
            f"| {r['conditions_sd']} | {r['crps']} | {r['coverage_80']:.1%} | {r['brier']:.4f} |"
            for r in d["tuning"]
        ],
        "",
        "## Backtest",
        "",
        f"Every match with a result in {_seasons(d['test'])} ({d['matches']} matches), simulated",
        f"{d['simulations_per_match']:,} times before a ball was bowled, with a ball-outcome model",
        "refit on the seasons before, the actual XIs in each player's usual batting order, bowling",
        "usage, extras and run outs from the three previous seasons, and the actual side batting",
        "first.",
        "",
        "### Who wins, before a ball is bowled",
        "",
        "| Chance the side batting first wins | Brier | Log loss |",
        "|---|---|---|",
        f"| **Simulator** | **{win['simulator']['brier']:.4f}** | **{win['simulator']['log_loss']:.4f}** |",
        f"| Coin flip | {win['coin_flip']['brier']:.4f} | {win['coin_flip']['log_loss']:.4f} |",
        f"| Batting-first rate before the test ({win['bat_first_rate']['rate']:.1%}) | "
        f"{win['bat_first_rate']['brier']:.4f} | {win['bat_first_rate']['log_loss']:.4f} |",
        f"| Both sides' recent form (log5) | {win['form']['brier']:.4f} | {win['form']['log_loss']:.4f} |",
        "",
        f"Against a coin flip the simulator's Brier score is {gain['value']:+.4f} (90%: "
        f"{gain['low']:+.4f} to {gain['high']:+.4f}; positive would be better). Before a ball is bowled,",
        "who wins an IPL match is close to unpredictable from XIs and form (see the Analytics Lab",
        f"note on rivalries); the simulator predicted the side batting first {win['mean_predicted']:.1%}",
        f"on average, and it won {win['observed']:.1%} of these matches.",
        "",
        "### From the first ball of a chase",
        "",
        f"With the actual target, the simulated chance of chasing it ({chase['matches']} chases):",
        "",
        "| | Brier | Log loss |",
        "|---|---|---|",
        f"| **Simulator** | **{chase['simulator']['brier']:.4f}** | **{chase['simulator']['log_loss']:.4f}** |",
        f"| Chase success rate before the test ({chase['chase_rate']['rate']:.1%}) | "
        f"{chase['chase_rate']['brier']:.4f} | {chase['chase_rate']['log_loss']:.4f} |",
        "",
        f"Gain over the base rate {chase_gain['value']:+.4f} (90%: {chase_gain['low']:+.4f} to "
        f"{chase_gain['high']:+.4f}). The simulated chances rank chases well but are too low:",
        f"{chase['mean_predicted']:.1%} on average against {chase['observed']:.1%} chased",
        "successfully, most for modest targets. Real chasers manage risk to see a gettable target",
        "home in ways the ball-by-ball model does not capture. The what-if sandbox therefore starts",
        "from the win probability model's estimate at the real score and moves it by the",
        "simulated change (on the log-odds scale) rather than showing the simulated level.",
        "",
        "| Predicted (fifths) | Matches | Simulated | Chased |",
        "|---|---|---|---|",
        *[
            f"| {i + 1} | {c['matches']} | {c['predicted']:.1%} | {c['observed']:.1%} |"
            for i, c in enumerate(chase["calibration"])
        ],
        "",
        "### First-innings totals",
        "",
        f"{first['matches']} full first innings. If the simulated distributions are right, the",
        "actual total's percentile within its simulation (PIT) is uniform:",
        "",
        "| PIT tenth | " + " | ".join(str(i + 1) for i in range(len(first["pit_counts"]))) + " |",
        "|---|" + "---|" * len(first["pit_counts"]),
        "| Matches | " + " | ".join(str(c) for c in first["pit_counts"]) + " |",
        "",
        f"Chi-square {first['pit_chi2']} (uniform at the 5% level below "
        f"{first['pit_chi2_critical']}). The simulated 80% range held "
        f"{first['coverage_80']:.1%} of actual totals and the 50% range "
        f"{first['coverage_50']:.1%}; CRPS {first['crps']} runs. Average total "
        f"{first['simulated_mean']} simulated against {first['actual_mean']} actual; wickets "
        f"{first['simulated_wickets']} against {first['actual_wickets']}.",
        "",
        "## Speed and rules",
        "",
        f"{d['timing']['simulations']:,} complete matches in {d['timing']['seconds']} s on the",
        "development machine (numpy, all simulations stepped together). Bowling rules gave way in",
        f"{d['forced_overs']} simulated overs of the backtest. Ties are reported as ties (super",
        f"overs are not simulated): {d['ties']['simulated']:.2%} of simulated test matches.",
        "",
        "## Limitations",
        "",
        "- No venue, weather or toss effects beyond the shared conditions draw; no Impact Player",
        "  substitutions (an XI of 11).",
        "- Batting order is fixed; real sides promote and demote batters during an innings.",
        "- The scoring era is the one before the simulated match, so in a season where scoring",
        "  jumps (as in 2023) simulated totals lag behind.",
        "- Pre-match win chances are no better than a coin flip in the backtest.",
        "",
    ]
    return "\n".join(lines)


def write_all() -> list[Path]:
    version = registry.current_version(registry.SIMULATOR)
    if version is None:
        return []
    data = insights(version)
    INSIGHTS_PATH.parent.mkdir(parents=True, exist_ok=True)
    INSIGHTS_PATH.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8", newline="\n")
    MODEL_CARD_PATH.parent.mkdir(parents=True, exist_ok=True)
    MODEL_CARD_PATH.write_text(model_card(data), encoding="utf-8", newline="\n")
    return [INSIGHTS_PATH, MODEL_CARD_PATH]
