"""Model card and Model Insights data for the match simulator.

v2 backtests each competition it serves; the card has a section per
competition, each stating what that competition's own backtest found.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from criciq_core import paths
from criciq_core import simulation as sim
from criciq_core.phases import model_format
from criciq_ml import registry
from criciq_ml.report_common import (
    IPL,
    fitted_on,
    format_path,
    pooled_path,
    spans_groups,
    write_json,
    write_text,
)
from criciq_ml.report_common import label as competition_label
from criciq_ml.simulator import gate

INSIGHTS_PATH = paths.repo_root() / "frontend" / "data" / "models" / "simulator.json"
MODEL_CARD_PATH = paths.repo_root() / "docs" / "model-cards" / "simulator.md"


def competitions_of(version: str) -> list[str]:
    """The competitions a version backtested (the IPL alone for v1)."""
    evaluation = registry.load_evaluation(version, registry.SIMULATOR)
    return list(evaluation.get("competitions", {IPL: None}))


def insights(version: str, competition: str = IPL) -> dict[str, Any]:
    evaluation = registry.load_evaluation(version, registry.SIMULATOR)
    if "competitions" in evaluation:
        evaluation = evaluation["competitions"][competition]
    keep = (
        "name",
        "version",
        "data_version",
        "valid",
        "test",
        "settings",
        "tuning",
        "matches",
        "simulations_per_match",
        "forced_overs",
        "win",
        "chase",
        "first_innings",
        "ties",
        "timing",
    )
    return {**{k: evaluation[k] for k in keep}, "competition": competition}


_QUOTA_WORDS = {4: "four", 10: "ten"}


def _seasons(values: list[int]) -> str:
    return f"{min(values)}-{max(values)}" if len(values) > 1 else str(values[0])


def _key(version: str) -> tuple[int, ...]:
    return tuple(int(x) for x in version.split("."))


def latest_pooled() -> str | None:
    """The newest version backtested beyond the IPL (it serves each competition whose
    own backtest passed), if any."""
    root = registry.root(registry.SIMULATOR)
    trained = sorted((d.name for d in root.iterdir() if (d / "evaluation.json").exists()), key=_key)
    pooled = [v for v in trained if competitions_of(v) != [IPL]]
    return pooled[-1] if pooled else None


def serves(version: str, competition: str) -> bool:
    return registry.current_version(registry.SIMULATOR, competition) == version


def _names(names: list[str]) -> str:
    """ "A", "A and B", "A, B and C"."""
    return " and ".join([", ".join(names[:-1]), names[-1]]) if len(names) > 1 else names[0]


def pooled_section(version: str) -> str:
    """The pooled version's backtest of every competition, and where it serves."""
    parts = [insights(version, c) for c in competitions_of(version)]
    served = [p["competition"] for p in parts if serves(version, p["competition"])]
    kept = [p for p in parts if p["competition"] not in served]
    competitions = competitions_of(version)
    ball = (
        "the pooled ball model (every T20 competition)"
        if spans_groups(competitions)
        else f"the ball model fitted on {fitted_on(competitions)}"
    )
    summary = [
        f"Version {version} plays matches with {ball} and "
        "was backtested on each competition below on its own matches. Each competition is "
        "simulated with it only where its own backtest passed the gate."
    ]
    if served:
        summary.append(f"It serves {_names([competition_label(c) for c in served])}.")
    for p in kept:
        reasons = "; ".join(gate(p)) or "not promoted"
        summary.append(f"It does not serve {competition_label(p['competition'])} ({reasons}).")
    lines = ["", f"# Version {version}: the other competitions", "", " ".join(summary), ""]
    for d in parts:
        section = _section(d, titled=True)
        status = (
            "Served: this backtest passed the gate."
            if d["competition"] in served
            else "Not served: " + ("; ".join(gate(d)) or "not promoted") + "."
        )
        lines += [section[0], "", status, *section[1:]]
    return "\n".join(lines)


def model_card(parts: list[dict[str, Any]]) -> str:
    """The card: one section per backtested competition."""
    version = parts[0]["version"]
    lines = [
        "# Model card: match simulator",
        "",
        "<!-- Generated by `criciq-ml report` from the model registry. Do not edit by hand. -->",
        "",
        f"**Version** {version} · **data** {parts[0]['data_version']} · backtested on "
        + ", ".join(competition_label(p["competition"]) for p in parts),
        "",
    ]
    for d in parts:
        lines += _section(d, titled=len(parts) > 1)
    return "\n".join(lines)


def _section(d: dict[str, Any], *, titled: bool) -> list[str]:
    win, chase, first = d["win"], d["chase"], d["first_innings"]
    s = d["settings"]
    gain = win["gain_vs_coin_flip"]
    chase_gain = chase["gain_vs_chase_rate"]
    name = competition_label(d["competition"])
    ipl = d["competition"] == IPL
    coin_flip = gain["low"] <= 0
    # The whole interval below zero: worse than calling every match a coin flip.
    worse = gain["high"] < 0
    low_chases = chase["mean_predicted"] < chase["observed"] - 0.03
    lopsided = win["calibration"][-1]
    timid = lopsided["observed"] - lopsided["predicted"] > 0.08
    window = s.get("level_window")
    # The spread was chosen by the PIT when the chosen value has the most uniform one.
    pits = [r.get("pit_chi2") for r in d["tuning"]]
    chosen = next(r for r in d["tuning"] if r["conditions_sd"] == s["conditions_sd"])
    by_pit = None not in pits and chosen.get("pit_chi2") == min(p for p in pits if p is not None)
    lines = [
        *([f"# {name}", ""] if titled else []),
        f"Conditions spread {s['conditions_sd']} (tuned on {_seasons(d['valid'])}).",
        "",
        "## Intended use",
        "",
        f"Monte Carlo simulation of {'an ODI' if model_format() == 'ODI' else 'a T20 match'} "
        "between two chosen XIs, and of the rest of a",
        "real match from any ball with an edited score (the replay's what-if sandbox). It shows",
        "distributions (totals, margins, each player's likely contribution) and how they move",
        "when the XI or the score changes. It is labelled a model simulation everywhere; it is",
        "not a forecast and not for betting.",
        "",
        "## How a match is simulated",
        "",
        "Every legal ball: extras from league rates for the innings and phase; the ball faced",
        "from the ball-outcome model (situation, era, striker and bowler; see its model card);",
        "run outs at the league rate. The strike changes on odd runs and at the end of an over.",
        "Each over's bowler is drawn from how often each bowler bowled that over in their last",
        f"{s['history_seasons']} seasons, shrunk toward their type's league pattern (worth "
        f"{s['usage_strength']:g} overs), within the {_QUOTA_WORDS[sim.rules_for(model_format()).quota]}"
        "-over quota, never twice in a row, and",
        "only if the rest of the innings can still be covered. Each simulated match draws its",
        "own conditions (how good the pitch and ground are for batting), shared by both innings,",
        f"with a spread of {s['conditions_sd']} on the log-odds scale: on the validation seasons,",
        (
            "the value whose first-innings totals fell most evenly across their simulated ranges "
            "(the PIT, the gate's own test; adopted after a T20I backtest with the scoring level "
            "followed had left the test ranges too wide under the 80%-coverage choice):"
            if by_pit
            else "the value whose 80% range held closest to 80% of first-innings totals"
            + (
                ". CRPS barely separates 0.3 from 0.4 there, and a season of jumping scores (2023) "
                "rewards extra width for its bias, so coverage, not CRPS, decides:"
                if ipl
                else " (coverage, not CRPS, decides):"
            )
        ),
        "",
        "| Spread | CRPS | 80% coverage | PIT chi-square | Brier |"
        if by_pit
        else "| Spread | CRPS | 80% coverage | Brier |",
        "|---|---|---|---|---|" if by_pit else "|---|---|---|---|",
        *[
            f"| {r['conditions_sd']} | {r['crps']} | {r['coverage_80']:.1%} | "
            + (f"{r['pit_chi2']} | " if by_pit else "")
            + f"{r['brier']:.4f} |"
            for r in d["tuning"]
        ],
        "",
        *(
            [
                f"It also follows the recent scoring level: before each match the scoring era is "
                f"moved so the ball model's expected runs over the previous {window} matches equal "
                "the runs actually scored, using only matches already played. The window (or none) "
                "was chosen on the validation seasons by CRPS:",
                "",
                "| Window (matches) | CRPS | Totals off by |",
                "|---|---|---|",
                *[
                    f"| {r['window'] or 'none'} | {r['crps']} | {r['bias']:+} runs |"
                    for r in d.get("level", {}).get("grid", [])
                ],
                "",
            ]
            if window
            else []
        ),
        "## Backtest",
        "",
        f"Every match with a result in {_seasons(d['test'])} ({d['matches']} matches), simulated",
        f"{d['simulations_per_match']:,} times before a ball was bowled, with a ball-outcome model",
        "refit on the seasons before, the actual XIs in each player's usual batting order, bowling",
        "usage, extras and run outs from the three previous seasons, and the actual side batting",
        "first.",
        "",
        "### Who wins, before a ball is bowled",
        "",
        "| Chance the side batting first wins | Brier | Log loss |",
        "|---|---|---|",
        f"| **Simulator** | **{win['simulator']['brier']:.4f}** | **{win['simulator']['log_loss']:.4f}** |",
        f"| Coin flip | {win['coin_flip']['brier']:.4f} | {win['coin_flip']['log_loss']:.4f} |",
        f"| Batting-first rate before the test ({win['bat_first_rate']['rate']:.1%}) | "
        f"{win['bat_first_rate']['brier']:.4f} | {win['bat_first_rate']['log_loss']:.4f} |",
        f"| Both sides' recent form (log5) | {win['form']['brier']:.4f} | {win['form']['log_loss']:.4f} |",
        "",
        f"Against a coin flip the simulator's Brier score is {gain['value']:+.4f} (90%: "
        f"{gain['low']:+.4f} to {gain['high']:+.4f}; positive is better). "
        + (
            (
                "Before a ball is bowled the simulator calls winners worse than a coin flip would "
                "(its chances lean the wrong way more often than not)"
                if worse
                else "Before a ball is bowled, who wins is close to unpredictable from XIs and form"
            )
            + (" (see the Analytics Lab note on rivalries)" if ipl else "")
            + "; "
            if coin_flip
            else "The XIs say a good deal about who wins here (sides differ widely in strength); "
        )
        + f"the simulator predicted the side batting first {win['mean_predicted']:.1%} on average, "
        f"and it won {win['observed']:.1%} of these matches.",
        "",
        "### From the first ball of a chase",
        "",
        f"With the actual target, the simulated chance of chasing it ({chase['matches']} chases):",
        "",
        "| | Brier | Log loss |",
        "|---|---|---|",
        f"| **Simulator** | **{chase['simulator']['brier']:.4f}** | **{chase['simulator']['log_loss']:.4f}** |",
        f"| Chase success rate before the test ({chase['chase_rate']['rate']:.1%}) | "
        f"{chase['chase_rate']['brier']:.4f} | {chase['chase_rate']['log_loss']:.4f} |",
        "",
        f"Gain over the base rate {chase_gain['value']:+.4f} (90%: {chase_gain['low']:+.4f} to "
        f"{chase_gain['high']:+.4f}). "
        + (
            f"The simulated chances rank chases well but are too low: {chase['mean_predicted']:.1%} "
            f"on average against {chase['observed']:.1%} chased successfully, most for modest "
            "targets. Real chasers manage risk to see a gettable target home in ways the "
            "ball-by-ball model does not capture."
            if low_chases
            else f"On average the simulated chance was {chase['mean_predicted']:.1%}, and "
            f"{chase['observed']:.1%} of the chases succeeded."
        )
        + " The what-if sandbox starts from the win probability model's estimate at the real "
        "score and moves it by the simulated change (on the log-odds scale) rather than "
        "showing the simulated level.",
        "",
        "| Predicted (fifths) | Matches | Simulated | Chased |",
        "|---|---|---|---|",
        *[
            f"| {i + 1} | {c['matches']} | {c['predicted']:.1%} | {c['observed']:.1%} |"
            for i, c in enumerate(chase["calibration"])
        ],
        "",
        "### First-innings totals",
        "",
        f"{first['matches']} full first innings. If the simulated distributions are right, the",
        "actual total's percentile within its simulation (PIT) is uniform:",
        "",
        "| PIT tenth | " + " | ".join(str(i + 1) for i in range(len(first["pit_counts"]))) + " |",
        "|---|" + "---|" * len(first["pit_counts"]),
        "| Matches | " + " | ".join(str(c) for c in first["pit_counts"]) + " |",
        "",
        f"Chi-square {first['pit_chi2']} (uniform at the 5% level below "
        f"{first['pit_chi2_critical']}). The simulated 80% range held "
        f"{first['coverage_80']:.1%} of actual totals and the 50% range "
        f"{first['coverage_50']:.1%}; CRPS {first['crps']} runs. Average total "
        f"{first['simulated_mean']} simulated against {first['actual_mean']} actual; wickets "
        f"{first['simulated_wickets']} against {first['actual_wickets']}.",
        "",
        "## Speed and rules",
        "",
        f"{d['timing']['simulations']:,} complete matches in {d['timing']['seconds']} s on the",
        "development machine (numpy, all simulations stepped together). Bowling rules gave way in",
        f"{d['forced_overs']} simulated overs of the backtest. Ties are reported as ties (super",
        f"overs are not simulated): {d['ties']['simulated']:.2%} of simulated test matches.",
        "",
        "## Limitations",
        "",
        "- No venue, weather or toss effects beyond the shared conditions draw; no Impact Player",
        "  substitutions (an XI of 11)"
        + ("." if ipl else "; of twelve named under supersub rules, the usual top eleven bat."),
        "- Batting order is fixed; real sides promote and demote batters during an innings.",
        *(
            [
                "- The scoring era is the one before the simulated match, so in a season where "
                "scoring",
                "  jumps (as in 2023) simulated totals lag behind.",
            ]
            if ipl
            else [
                "- The scoring era is the one before the simulated match, so when scoring rises "
                "simulated totals lag behind."
            ]
        ),
        *(
            [
                "- Pre-match win chances are "
                + ("worse than" if worse else "no better than")
                + " a coin flip in the backtest."
            ]
            if coin_flip
            else []
        ),
        *(
            [
                "- Win chances are too close to even between unequal sides: in the fifth of "
                f"matches it rated most one-sided the side batting first was given "
                f"{lopsided['predicted']:.1%} and won {lopsided['observed']:.1%}. Players with "
                "few balls (most associate players) are shrunk toward the average player, so "
                "mismatches look closer than they are."
            ]
            if timid
            else []
        ),
        "",
    ]
    return lines


def write_format() -> list[Path]:
    """A model group's (or another format's) newest simulator backtest (see
    ``report.write_format``), served or not: one competition's, or for a group of
    several each competition's and where it serves (as the pooled T20 data)."""
    root = registry.root(registry.SIMULATOR)
    if not root.exists():
        return []
    trained = sorted((d.name for d in root.iterdir() if (d / "evaluation.json").exists()), key=_key)
    if not trained:
        return []
    version = trained[-1]
    competitions = competitions_of(version)
    if len(competitions) > 1:
        parts = {c: insights(version, c) for c in competitions}
        data: dict[str, Any] = {
            "version": version,
            "served": [c for c in parts if serves(version, c)],
            "competitions": {c: {**part, "gate": gate(part)} for c, part in parts.items()},
        }
        return [
            write_json(format_path(INSIGHTS_PATH), data),
            write_text(format_path(MODEL_CARD_PATH), _group_card(version, parts)),
        ]
    competition = competitions[0]
    part = insights(version, competition)
    data = {**part, "gate": gate(part), "served": serves(version, competition)}
    return [
        write_json(format_path(INSIGHTS_PATH), data),
        write_text(format_path(MODEL_CARD_PATH), model_card([part])),
    ]


def _group_card(version: str, parts: dict[str, dict[str, Any]]) -> str:
    """The card of a group's simulator: every competition's backtest, and where it serves."""
    lines = [model_card(list(parts.values())), "", "## Where it serves", ""]
    for competition, part in parts.items():
        problems = gate(part)
        name = competition_label(competition)
        if serves(version, competition):
            lines.append(f"- **{name}**: served (its backtest passed the gate).")
        else:
            lines.append(
                f"- **{name}**: not served; its backtest failed the gate: "
                + ("; ".join(problems) if problems else "not promoted")
                + "."
            )
    return "\n".join([*lines, ""])


def write_all() -> list[Path]:
    ipl = registry.current_version(registry.SIMULATOR, IPL)
    if ipl is None:
        return []
    out = [write_json(INSIGHTS_PATH, insights(ipl, IPL))]
    card = model_card([insights(ipl, IPL)])
    pooled = latest_pooled()
    if pooled is not None:
        card += pooled_section(pooled)
        parts = {c: insights(pooled, c) for c in competitions_of(pooled)}
        out.append(
            write_json(
                pooled_path(INSIGHTS_PATH),
                {
                    "version": pooled,
                    "served": [c for c in parts if serves(pooled, c)],
                    "competitions": {c: {**part, "gate": gate(part)} for c, part in parts.items()},
                },
            )
        )
    out.append(write_text(MODEL_CARD_PATH, card))
    return out
