// Generated by `python -m criciq_api.featured`. Do not edit.
import type { Timeline } from "@/lib/api/types";

export const featuredTimelines: Record<number, () => Promise<Timeline>> = {
  1448353: () => import("./1448353.json").then((m) => m.default as unknown as Timeline),
  1322356: () => import("./1322356.json").then((m) => m.default as unknown as Timeline),
  1223872: () => import("./1223872.json").then((m) => m.default as unknown as Timeline),
  1152848: () => import("./1152848.json").then((m) => m.default as unknown as Timeline),
  215010: () => import("./215010.json").then((m) => m.default as unknown as Timeline),
  64027: () => import("./64027.json").then((m) => m.default as unknown as Timeline),
};
