// Generated by `python -m criciq_api.featured`. Do not edit.
import type { Timeline } from "@/lib/api/types";

export const featuredTimelines: Record<number, () => Promise<Timeline>> = {
  1535465: () => import("./1535465.json").then((m) => m.default as unknown as Timeline),
  1473511: () => import("./1473511.json").then((m) => m.default as unknown as Timeline),
  1426312: () => import("./1426312.json").then((m) => m.default as unknown as Timeline),
  1426268: () => import("./1426268.json").then((m) => m.default as unknown as Timeline),
  1370353: () => import("./1370353.json").then((m) => m.default as unknown as Timeline),
  1216517: () => import("./1216517.json").then((m) => m.default as unknown as Timeline),
  1181768: () => import("./1181768.json").then((m) => m.default as unknown as Timeline),
  1082625: () => import("./1082625.json").then((m) => m.default as unknown as Timeline),
  981019: () => import("./981019.json").then((m) => m.default as unknown as Timeline),
  335982: () => import("./335982.json").then((m) => m.default as unknown as Timeline),
};
