// Generated by `python -m criciq_api.featured`. Do not edit.
import type { Timeline } from "@/lib/api/types";

export const featuredTimelines: Record<number, () => Promise<Timeline>> = {
  1527595: () => import("./1527595.json").then((m) => m.default as unknown as Timeline),
  1475271: () => import("./1475271.json").then((m) => m.default as unknown as Timeline),
  1416505: () => import("./1416505.json").then((m) => m.default as unknown as Timeline),
  1354957: () => import("./1354957.json").then((m) => m.default as unknown as Timeline),
  1293033: () => import("./1293033.json").then((m) => m.default as unknown as Timeline),
  1247044: () => import("./1247044.json").then((m) => m.default as unknown as Timeline),
};
