/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Matches
         * @description Paginated match summaries, newest first by default.
         */
        get: operations["list_matches_api_v1_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Match
         * @description Match summary with full scorecards for every innings.
         */
        get: operations["read_match_api_v1_matches__match_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Timeline
         * @description Every delivery with running state: one payload drives a full client-side replay.
         */
        get: operations["read_timeline_api_v1_matches__match_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Meta
         * @description Dataset version and the seasons, franchises and venues available for filtering.
         */
        get: operations["read_meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BattingEntry */
        BattingEntry: {
            /** Balls */
            balls: number;
            /**
             * Dismissal
             * @description How out, e.g. 'c Dhoni b Bravo'; None if not out.
             */
            dismissal: string | null;
            /** Fours */
            fours: number;
            /** Is Out */
            is_out: boolean;
            /** Name */
            name: string;
            /** Player Id */
            player_id: string;
            /** Runs */
            runs: number;
            /** Sixes */
            sixes: number;
            /** Strike Rate */
            strike_rate: number | null;
        };
        /** BowlingEntry */
        BowlingEntry: {
            /** Economy */
            economy: number | null;
            /** Maidens */
            maidens: number;
            /** Name */
            name: string;
            /** Noballs */
            noballs: number;
            /** Overs */
            overs: string;
            /** Player Id */
            player_id: string;
            /** Runs */
            runs: number;
            /** Wickets */
            wickets: number;
            /** Wides */
            wides: number;
        };
        /** Extras */
        Extras: {
            /** Byes */
            byes: number;
            /** Legbyes */
            legbyes: number;
            /** Noballs */
            noballs: number;
            /** Penalty */
            penalty: number;
            /** Total */
            total: number;
            /** Wides */
            wides: number;
        };
        /** FallOfWicket */
        FallOfWicket: {
            /** Name */
            name: string;
            /** Overs */
            overs: string;
            /** Player Id */
            player_id: string;
            /** Runs */
            runs: number;
            /** Wicket */
            wicket: number;
        };
        /** FranchiseInfo */
        FranchiseInfo: {
            /** First Season */
            first_season: number;
            /** Franchise Id */
            franchise_id: string;
            /** Is Active */
            is_active: boolean;
            /** Last Season */
            last_season: number | null;
            /** Name */
            name: string;
            /** Primary Color */
            primary_color: string;
            /** Secondary Color */
            secondary_color: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** InningsScorecard */
        InningsScorecard: {
            /** Batting */
            batting: components["schemas"]["BattingEntry"][];
            batting_team: components["schemas"]["TeamRef"];
            /** Bowling */
            bowling: components["schemas"]["BowlingEntry"][];
            bowling_team: components["schemas"]["TeamRef"];
            /** Did Not Bat */
            did_not_bat: components["schemas"]["PlayerRef"][];
            extras: components["schemas"]["Extras"];
            /** Fall Of Wickets */
            fall_of_wickets: components["schemas"]["FallOfWicket"][];
            /** Innings No */
            innings_no: number;
            /** Is Super Over */
            is_super_over: boolean;
            /** Overs */
            overs: string;
            /** Runs */
            runs: number;
            /** Target Overs */
            target_overs: number | null;
            /** Target Runs */
            target_runs: number | null;
            /** Wickets */
            wickets: number;
        };
        /** MatchDetail */
        MatchDetail: {
            /** Innings */
            innings: components["schemas"]["InningsScorecard"][];
            summary: components["schemas"]["MatchSummary"];
        };
        /** MatchPage */
        MatchPage: {
            /** Items */
            items: components["schemas"]["MatchSummary"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** MatchSummary */
        MatchSummary: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Decided By Super Over */
            decided_by_super_over: boolean;
            /** Is Playoff */
            is_playoff: boolean;
            /** Match Id */
            match_id: number;
            /** Match Number */
            match_number: number | null;
            /**
             * Outcome Type
             * @enum {string}
             */
            outcome_type: "win" | "tie" | "no_result";
            /** Player Of Match */
            player_of_match: string[];
            /** Result Text */
            result_text: string;
            /** Season */
            season: number;
            /** Stage */
            stage: string;
            /** Target Runs */
            target_runs: number | null;
            /** @description The side that batted first. */
            team_a: components["schemas"]["TeamScore"];
            team_b: components["schemas"]["TeamScore"];
            toss: components["schemas"]["Toss"];
            venue: components["schemas"]["VenueRef"];
            /** Win Method */
            win_method: string | null;
            /** Winner Id */
            winner_id: string | null;
        };
        /** Meta */
        Meta: {
            /**
             * Api Version
             * @constant
             */
            api_version: "v1";
            /** App Version */
            app_version: string;
            /** Data Version */
            data_version: string;
            /** Franchises */
            franchises: components["schemas"]["FranchiseInfo"][];
            /** Model Versions */
            model_versions: {
                [key: string]: string;
            };
            /** Seasons */
            seasons: components["schemas"]["SeasonInfo"][];
            /** Venues */
            venues: components["schemas"]["VenueInfo"][];
        };
        /** PlayerRef */
        PlayerRef: {
            /** Name */
            name: string;
            /** Player Id */
            player_id: string;
        };
        /**
         * ScoreProjectionModel
         * @description The model behind a timeline's first-innings score projections.
         */
        ScoreProjectionModel: {
            /**
             * Levels
             * @description Quantile level of each value in `projection`.
             */
            levels: number[];
            /** Trained From */
            trained_from: number;
            /** Trained Through */
            trained_through: number;
            /** Version */
            version: string;
        };
        /** SeasonInfo */
        SeasonInfo: {
            /** Impact Player Rule */
            impact_player_rule: boolean;
            /** Matches */
            matches: number;
            /** Year */
            year: number;
        };
        /** TeamRef */
        TeamRef: {
            /** Color */
            color: string;
            /** Franchise Id */
            franchise_id: string;
            /** Name */
            name: string;
            /** Team Season Id */
            team_season_id: string;
        };
        /** TeamScore */
        TeamScore: {
            /** Color */
            color: string;
            /** Franchise Id */
            franchise_id: string;
            /** Name */
            name: string;
            /**
             * Overs
             * @description Scoreboard overs, e.g. '19.4'.
             */
            overs: string | null;
            /** Runs */
            runs: number | null;
            /** Team Season Id */
            team_season_id: string;
            /** Wickets */
            wickets: number | null;
        };
        /**
         * Timeline
         * @description Everything the client needs to replay a match ball by ball, in one payload.
         */
        Timeline: {
            /** Deliveries */
            deliveries: components["schemas"]["TimelineDelivery"][];
            /** Innings */
            innings: components["schemas"]["TimelineInnings"][];
            /** Players */
            players: {
                [key: string]: components["schemas"]["TimelinePlayer"];
            };
            /** @description Present when the first innings has score projections. */
            score_projection?: components["schemas"]["ScoreProjectionModel"] | null;
            /** Substitutions */
            substitutions: components["schemas"]["TimelineSubstitution"][];
            summary: components["schemas"]["MatchSummary"];
            /** Teams */
            teams: {
                [key: string]: components["schemas"]["TeamRef"];
            };
            /** @description Present when the match has model win probabilities. */
            win_probability?: components["schemas"]["WinProbabilityModel"] | null;
        };
        /** TimelineDelivery */
        TimelineDelivery: {
            /** Ball Label */
            ball_label: string | null;
            /** Batter Id */
            batter_id: string;
            /** Bowler Id */
            bowler_id: string;
            /** Byes */
            byes: number;
            /**
             * Factors
             * @description Percentage points each factor adds to the batting side's chance, relative to the model's average, in the order of Timeline.win_probability.factor_keys. Absent once the result is certain.
             */
            factors?: number[] | null;
            /** Innings No */
            innings_no: number;
            /** Is Four */
            is_four: boolean;
            /** Is Legal */
            is_legal: boolean;
            /** Is Six */
            is_six: boolean;
            /**
             * Legal Ball No
             * @description Legal balls bowled in the innings after this delivery.
             */
            legal_ball_no: number;
            /** Legbyes */
            legbyes: number;
            /** Noballs */
            noballs: number;
            /** Non Striker Id */
            non_striker_id: string;
            /**
             * Over No
             * @description 0-based over number.
             */
            over_no: number;
            /** Penalty */
            penalty: number;
            /**
             * Projection
             * @description First innings only: quantiles of the final total after this ball, at the levels in Timeline.score_projection.levels (model estimate).
             */
            projection?: number[] | null;
            /** Runs Batter */
            runs_batter: number;
            /** Runs Extras */
            runs_extras: number;
            /** Runs Total */
            runs_total: number;
            /** Seq No */
            seq_no: number;
            /**
             * Team Runs
             * @description Innings score after this delivery.
             */
            team_runs: number;
            /** Team Wickets */
            team_wickets: number;
            wicket: components["schemas"]["TimelineWicket"] | null;
            /** Wides */
            wides: number;
            /**
             * Wp
             * @description Win probability of the side batting first after this ball (model estimate).
             */
            wp?: number | null;
        };
        /** TimelineInnings */
        TimelineInnings: {
            /** Batting Team Id */
            batting_team_id: string;
            /** Bowling Team Id */
            bowling_team_id: string;
            /**
             * Factors Start
             * @description Explanation of wp_start (see Timeline.win_probability).
             */
            factors_start?: number[] | null;
            /** Innings No */
            innings_no: number;
            /** Is Super Over */
            is_super_over: boolean;
            /**
             * Max Balls
             * @description Legal balls available to the batting side.
             */
            max_balls: number;
            /**
             * Projection Start
             * @description First innings only: quantiles of the final total before the first ball.
             */
            projection_start?: number[] | null;
            /** Target Balls */
            target_balls: number | null;
            /** Target Runs */
            target_runs: number | null;
            /**
             * Wp Start
             * @description Win probability of the side batting first before this innings' first ball.
             */
            wp_start?: number | null;
        };
        /** TimelinePlayer */
        TimelinePlayer: {
            /** Full Name */
            full_name: string | null;
            /** Name */
            name: string;
        };
        /** TimelineSubstitution */
        TimelineSubstitution: {
            /** Innings No */
            innings_no: number;
            /** Player In Id */
            player_in_id: string | null;
            /** Player Out Id */
            player_out_id: string | null;
            /** Reason */
            reason: string | null;
            /** Seq No */
            seq_no: number;
            /** Team Season Id */
            team_season_id: string;
        };
        /** TimelineWicket */
        TimelineWicket: {
            /** Bowler Credited */
            bowler_credited: boolean;
            /** Fielder Ids */
            fielder_ids: string[];
            /** Is Dismissal */
            is_dismissal: boolean;
            /** Kind */
            kind: string;
            /** Player Out Id */
            player_out_id: string;
        };
        /** Toss */
        Toss: {
            /** Decision */
            decision: ("bat" | "field") | null;
            /** Winner Id */
            winner_id: string | null;
            /** Winner Name */
            winner_name: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VenueInfo */
        VenueInfo: {
            /** City */
            city: string;
            /** Country */
            country: string;
            /** Matches */
            matches: number;
            /** Name */
            name: string;
            /** Venue Id */
            venue_id: string;
        };
        /** VenueRef */
        VenueRef: {
            /** City */
            city: string;
            /** Name */
            name: string;
            /** Venue Id */
            venue_id: string;
        };
        /**
         * WinProbabilityModel
         * @description The model behind a timeline's win probabilities.
         */
        WinProbabilityModel: {
            /**
             * Base Innings1
             * @description Average first-innings estimate: the reference point for its factors.
             */
            base_innings1: number;
            /**
             * Base Innings2
             * @description Average chase estimate: the reference point for its factors.
             */
            base_innings2: number;
            /**
             * Factor Keys
             * @description Order of the values in each `factors` list.
             */
            factor_keys: string[];
            /** Trained From */
            trained_from: number;
            /** Trained Through */
            trained_through: number;
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_matches_api_v1_matches_get: {
        parameters: {
            query?: {
                season?: number | null;
                /** @description Franchise id, e.g. MI */
                team?: string | null;
                /** @description Venue id */
                venue?: string | null;
                /** @description Only playoffs (true) or league */
                playoffs?: boolean | null;
                sort?: "latest" | "oldest";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_match_api_v1_matches__match_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_timeline_api_v1_matches__match_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
