/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Matches
         * @description Paginated match summaries, newest first by default.
         */
        get: operations["list_matches_api_v1_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Match
         * @description Match summary with full scorecards for every innings.
         */
        get: operations["read_match_api_v1_matches__match_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Timeline
         * @description Every delivery with running state: one payload drives a full client-side replay.
         */
        get: operations["read_timeline_api_v1_matches__match_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matchups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Matchups
         * @description Batter-bowler pairs with raw, expected and shrunk strike rates.
         *
         *     Filter by batter (the bowlers they faced) or by bowler (the batters they
         *     bowled to). ``batter_edge`` and ``bowler_edge`` rank by the matchup effect
         *     beyond each player's overall record.
         */
        get: operations["list_matchups_api_v1_matchups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matchups/{batter_id}/{bowler_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Matchup
         * @description Head-to-head record, the empirical-Bayes estimate and next-ball odds for a pair.
         */
        get: operations["read_matchup_api_v1_matchups__batter_id___bowler_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Meta
         * @description Dataset version and the seasons, franchises and venues available for filtering.
         */
        get: operations["read_meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Players
         * @description Player directory with headline numbers; season and team filters scope the numbers.
         */
        get: operations["list_players_api_v1_players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Player
         * @description Profile: batting and bowling against par, seasons, phases, ratings and recent form.
         */
        get: operations["read_player_api_v1_players__player_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{player_id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Similar
         * @description Players with the most similar batting and bowling styles in the same seasons.
         */
        get: operations["read_similar_api_v1_players__player_id__similar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{player_id}/splits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Splits
         * @description Batting and bowling split by phase, opponent type, position, venue, opposition and more.
         */
        get: operations["read_splits_api_v1_players__player_id__splits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predict/next-ball": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Predict Next Ball
         * @description Outcome probabilities for the next ball in a given situation (model estimate).
         */
        post: operations["predict_next_ball_api_v1_predict_next_ball_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Overview
         * @description Every franchise's record and titles, champions by season and league-wide trends.
         */
        get: operations["read_overview_api_v1_teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/h2h": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Head To Head
         * @description Head-to-head record of two franchises, against what their form predicts.
         */
        get: operations["read_head_to_head_api_v1_teams_h2h_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/standings/{season}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Standings
         * @description The league table for a season (points, net run rate, finish) and its playoffs.
         */
        get: operations["read_standings_api_v1_teams_standings__season__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{franchise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Team
         * @description A franchise's seasons, results by situation, phase profile, players and swings.
         */
        get: operations["read_team_api_v1_teams__franchise_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BattingEntry */
        BattingEntry: {
            /** Balls */
            balls: number;
            /**
             * Dismissal
             * @description How out, e.g. 'c Dhoni b Bravo'; None if not out.
             */
            dismissal: string | null;
            /** Fours */
            fours: number;
            /** Is Out */
            is_out: boolean;
            /** Name */
            name: string;
            /** Player Id */
            player_id: string;
            /** Runs */
            runs: number;
            /** Sixes */
            sixes: number;
            /** Strike Rate */
            strike_rate: number | null;
        };
        /** BattingInnings */
        BattingInnings: {
            /** Balls */
            balls: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Dismissal */
            dismissal: string | null;
            /** Fours */
            fours: number;
            /** Is Out */
            is_out: boolean;
            /** Match Id */
            match_id: number;
            opposition: components["schemas"]["TeamTag"];
            /** Position */
            position: number;
            /**
             * Result
             * @enum {string}
             */
            result: "won" | "lost" | "no_result";
            /** Runs */
            runs: number;
            /** Season */
            season: number;
            /** Sixes */
            sixes: number;
            /** Venue */
            venue: string;
            /** Wpa */
            wpa: number | null;
        };
        /** BattingSplitGroup */
        BattingSplitGroup: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Rows */
            rows: components["schemas"]["BattingSplitRow"][];
        };
        /** BattingSplitRow */
        BattingSplitRow: {
            /** Average */
            average: number | null;
            /** Balls */
            balls: number;
            /** Boundary Pct */
            boundary_pct: number | null;
            /** Color */
            color?: string | null;
            /** Dot Pct */
            dot_pct: number | null;
            /** Fifties */
            fifties: number | null;
            /** Highest */
            highest: number | null;
            /**
             * Innings
             * @description None for ball-level splits (phase, bowler type).
             */
            innings: number | null;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Outs */
            outs: number;
            /** Par Strike Rate */
            par_strike_rate: number | null;
            /** Runs */
            runs: number;
            /** Strike Rate */
            strike_rate: number | null;
        };
        /** BattingSummary */
        BattingSummary: {
            /** Average */
            average: number | null;
            /** Balls */
            balls: number;
            /** Boundary Pct */
            boundary_pct: number | null;
            /** Dot Pct */
            dot_pct: number | null;
            /** Ducks */
            ducks: number;
            /** Fifties */
            fifties: number;
            /** Fours */
            fours: number;
            highest: components["schemas"]["HighScore"] | null;
            /** Hundreds */
            hundreds: number;
            /** Innings */
            innings: number;
            /** Matches */
            matches: number;
            /** Not Outs */
            not_outs: number;
            /** Outs */
            outs: number;
            /** Par Average */
            par_average: number | null;
            /** Par Boundary Pct */
            par_boundary_pct: number | null;
            /** Par Dot Pct */
            par_dot_pct: number | null;
            /** Par Strike Rate */
            par_strike_rate: number | null;
            /** Runs */
            runs: number;
            /**
             * Runs Above Par
             * @description Runs scored minus par runs for the same balls.
             */
            runs_above_par: number;
            /** Sixes */
            sixes: number;
            /** Strike Rate */
            strike_rate: number | null;
            /**
             * Wpa
             * @description Win probability added, in probability units.
             */
            wpa: number | null;
            /**
             * Wpa Innings
             * @description Innings with win probabilities behind ``wpa``.
             */
            wpa_innings: number;
        };
        /** BestFigures */
        BestFigures: {
            /** Match Id */
            match_id: number;
            /** Opposition Id */
            opposition_id: string;
            /** Runs */
            runs: number;
            /** Season */
            season: number;
            /** Wickets */
            wickets: number;
        };
        /** BowlingEntry */
        BowlingEntry: {
            /** Economy */
            economy: number | null;
            /** Maidens */
            maidens: number;
            /** Name */
            name: string;
            /** Noballs */
            noballs: number;
            /** Overs */
            overs: string;
            /** Player Id */
            player_id: string;
            /** Runs */
            runs: number;
            /** Wickets */
            wickets: number;
            /** Wides */
            wides: number;
        };
        /** BowlingInnings */
        BowlingInnings: {
            /** Balls */
            balls: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Economy */
            economy: number | null;
            /** Match Id */
            match_id: number;
            opposition: components["schemas"]["TeamTag"];
            /** Overs */
            overs: string;
            /**
             * Result
             * @enum {string}
             */
            result: "won" | "lost" | "no_result";
            /** Runs */
            runs: number;
            /** Season */
            season: number;
            /** Venue */
            venue: string;
            /** Wickets */
            wickets: number;
            /** Wpa */
            wpa: number | null;
        };
        /** BowlingSplitGroup */
        BowlingSplitGroup: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Rows */
            rows: components["schemas"]["BowlingSplitRow"][];
        };
        /** BowlingSplitRow */
        BowlingSplitRow: {
            /** Average */
            average: number | null;
            /** Balls */
            balls: number;
            /** Color */
            color?: string | null;
            /** Dot Pct */
            dot_pct: number | null;
            /** Economy */
            economy: number | null;
            /** Innings */
            innings: number | null;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Par Economy */
            par_economy: number | null;
            /** Runs */
            runs: number;
            /** Strike Rate */
            strike_rate: number | null;
            /** Wickets */
            wickets: number;
        };
        /** BowlingSummary */
        BowlingSummary: {
            /** Average */
            average: number | null;
            /** Balls */
            balls: number;
            best: components["schemas"]["BestFigures"] | null;
            /** Boundary Pct */
            boundary_pct: number | null;
            /** Dot Pct */
            dot_pct: number | null;
            /** Economy */
            economy: number | null;
            /**
             * Five Wickets
             * @description Innings with five or more wickets.
             */
            five_wickets: number;
            /**
             * Four Wickets
             * @description Innings with exactly four wickets.
             */
            four_wickets: number;
            /** Innings */
            innings: number;
            /** Maidens */
            maidens: number;
            /** Matches */
            matches: number;
            /** Noballs */
            noballs: number;
            /** Overs */
            overs: string;
            /** Par Dot Pct */
            par_dot_pct: number | null;
            /** Par Economy */
            par_economy: number | null;
            /** Par Strike Rate */
            par_strike_rate: number | null;
            /** Runs */
            runs: number;
            /**
             * Runs Saved
             * @description Par runs minus runs conceded for the same balls.
             */
            runs_saved: number;
            /** Strike Rate */
            strike_rate: number | null;
            /** Wickets */
            wickets: number;
            /** Wides */
            wides: number;
            /** Wpa */
            wpa: number | null;
            /** Wpa Innings */
            wpa_innings: number;
        };
        /** DismissalCount */
        DismissalCount: {
            /** Count */
            count: number;
            /** Kind */
            kind: string;
        };
        /** Dismissals */
        Dismissals: {
            /**
             * Batting
             * @description How the player got out.
             */
            batting: components["schemas"]["DismissalCount"][];
            /**
             * Bowling
             * @description How the player took wickets.
             */
            bowling: components["schemas"]["DismissalCount"][];
        };
        /** Extras */
        Extras: {
            /** Byes */
            byes: number;
            /** Legbyes */
            legbyes: number;
            /** Noballs */
            noballs: number;
            /** Penalty */
            penalty: number;
            /** Total */
            total: number;
            /** Wides */
            wides: number;
        };
        /** FallOfWicket */
        FallOfWicket: {
            /** Name */
            name: string;
            /** Overs */
            overs: string;
            /** Player Id */
            player_id: string;
            /** Runs */
            runs: number;
            /** Wicket */
            wicket: number;
        };
        /** FieldingSummary */
        FieldingSummary: {
            /** Catches */
            catches: number;
            /** Run Outs */
            run_outs: number;
            /** Stumpings */
            stumpings: number;
        };
        /** FormerName */
        FormerName: {
            /** First Season */
            first_season: number;
            /** Last Season */
            last_season: number;
            /** Name */
            name: string;
        };
        /** FranchiseInfo */
        FranchiseInfo: {
            /** First Season */
            first_season: number;
            /** Franchise Id */
            franchise_id: string;
            /** Is Active */
            is_active: boolean;
            /** Last Season */
            last_season: number | null;
            /** Name */
            name: string;
            /** Primary Color */
            primary_color: string;
            /** Secondary Color */
            secondary_color: string;
        };
        /** FranchiseSummary */
        FranchiseSummary: {
            /** Color */
            color: string;
            /** Finals */
            finals: number[];
            /** First Season */
            first_season: number;
            /** Franchise Id */
            franchise_id: string;
            /** Is Active */
            is_active: boolean;
            /** Last Season */
            last_season: number;
            /** Name */
            name: string;
            /**
             * Names
             * @description Every name the franchise played under.
             */
            names: components["schemas"]["FormerName"][];
            /**
             * Playoffs
             * @description Seasons in which the side reached the playoffs.
             */
            playoffs: number[];
            record: components["schemas"]["Record"];
            /** Seasons */
            seasons: number;
            /** Secondary Color */
            secondary_color: string;
            /** Titles */
            titles: number[];
        };
        /**
         * H2HExpectation
         * @description A's wins against what each side's form in those seasons predicts (log5).
         */
        H2HExpectation: {
            /** A Expected */
            a_expected: number;
            /** A Won */
            a_won: number;
            /** Decided */
            decided: number;
            /** High */
            high: number;
            /**
             * Low
             * @description 90% range of A's wins from chance alone.
             */
            low: number;
            /** Seasons Used */
            seasons_used: number;
        };
        /** H2HPlayer */
        H2HPlayer: {
            /** Balls */
            balls?: number | null;
            /** Economy */
            economy?: number | null;
            /** Innings */
            innings: number;
            /** Name */
            name: string;
            /** Player Id */
            player_id: string;
            /** Runs */
            runs?: number | null;
            /** Strike Rate */
            strike_rate?: number | null;
            team: components["schemas"]["TeamTag"];
            /** Wickets */
            wickets?: number | null;
        };
        /** H2HRecord */
        H2HRecord: {
            /** A Won */
            a_won: number;
            /** B Won */
            b_won: number;
            /** No Result */
            no_result: number;
            /** Played */
            played: number;
            /**
             * Tied
             * @description Ties settled by a super over (already counted as wins).
             */
            tied: number;
        };
        /** H2HScoring */
        H2HScoring: {
            /** A Avg Total */
            a_avg_total: number | null;
            a_highest: components["schemas"]["TeamTotal"] | null;
            /** B Avg Total */
            b_avg_total: number | null;
            b_highest: components["schemas"]["TeamTotal"] | null;
        };
        /** H2HSeason */
        H2HSeason: {
            record: components["schemas"]["H2HRecord"];
            /** Season */
            season: number;
        };
        /** H2HSplit */
        H2HSplit: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            record: components["schemas"]["H2HRecord"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeadToHead */
        HeadToHead: {
            /** Average */
            average: number | null;
            /** Balls */
            balls: number;
            /** Dismissals */
            dismissals: number;
            /** Dots */
            dots: number;
            /** Fours */
            fours: number;
            /** Runs */
            runs: number;
            /** Sixes */
            sixes: number;
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** HighScore */
        HighScore: {
            /** Match Id */
            match_id: number;
            /** Not Out */
            not_out: boolean;
            /** Opposition Id */
            opposition_id: string;
            /** Runs */
            runs: number;
            /** Season */
            season: number;
        };
        /** InningsScorecard */
        InningsScorecard: {
            /** Batting */
            batting: components["schemas"]["BattingEntry"][];
            batting_team: components["schemas"]["TeamRef"];
            /** Bowling */
            bowling: components["schemas"]["BowlingEntry"][];
            bowling_team: components["schemas"]["TeamRef"];
            /** Did Not Bat */
            did_not_bat: components["schemas"]["PlayerRef"][];
            extras: components["schemas"]["Extras"];
            /** Fall Of Wickets */
            fall_of_wickets: components["schemas"]["FallOfWicket"][];
            /** Innings No */
            innings_no: number;
            /** Is Super Over */
            is_super_over: boolean;
            /** Overs */
            overs: string;
            /** Runs */
            runs: number;
            /** Target Overs */
            target_overs: number | null;
            /** Target Runs */
            target_runs: number | null;
            /** Wickets */
            wickets: number;
        };
        /** Interval */
        Interval: {
            /**
             * High
             * @description Upper end; None when unbounded.
             */
            high: number | null;
            /**
             * Low
             * @description Lower end of the 90% interval.
             */
            low: number | null;
            /** Value */
            value: number | null;
        };
        /** LeagueTrends */
        LeagueTrends: {
            /** @description Matches won by the side batting second. */
            chasing: components["schemas"]["Rate"];
            /** @description Close finishes as a share of decided matches. */
            close: components["schemas"]["Rate"];
            /** @description Home sides' wins in matches with a home side. */
            home: components["schemas"]["Rate"];
            /** Seasons */
            seasons: components["schemas"]["SeasonTrend"][];
            /** @description Matches won by the side that won the toss. */
            toss: components["schemas"]["Rate"];
        };
        /** MatchDetail */
        MatchDetail: {
            /** Innings */
            innings: components["schemas"]["InningsScorecard"][];
            summary: components["schemas"]["MatchSummary"];
        };
        /** MatchPage */
        MatchPage: {
            /** Items */
            items: components["schemas"]["MatchSummary"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** MatchSummary */
        MatchSummary: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Decided By Super Over */
            decided_by_super_over: boolean;
            /** Is Playoff */
            is_playoff: boolean;
            /** Match Id */
            match_id: number;
            /** Match Number */
            match_number: number | null;
            /**
             * Outcome Type
             * @enum {string}
             */
            outcome_type: "win" | "tie" | "no_result";
            /** Player Of Match */
            player_of_match: string[];
            /** Result Text */
            result_text: string;
            /** Season */
            season: number;
            /** Stage */
            stage: string;
            /** Target Runs */
            target_runs: number | null;
            /** @description The side that batted first. */
            team_a: components["schemas"]["TeamScore"];
            team_b: components["schemas"]["TeamScore"];
            toss: components["schemas"]["Toss"];
            venue: components["schemas"]["VenueRef"];
            /** Win Method */
            win_method: string | null;
            /** Winner Id */
            winner_id: string | null;
        };
        /** MatchupDetail */
        MatchupDetail: {
            batter: components["schemas"]["MatchupPlayer"];
            bowler: components["schemas"]["MatchupPlayer"];
            /** By Phase */
            by_phase: components["schemas"]["MatchupSplitRow"][];
            /** By Season */
            by_season: components["schemas"]["MatchupSplitRow"][];
            /**
             * Context
             * @description The situation the next-ball probabilities assume.
             */
            context: string;
            /** Dismissals */
            dismissals: components["schemas"]["MatchupDismissal"][];
            estimate: components["schemas"]["MatchupNumbers"] | null;
            expected: components["schemas"]["MatchupNumbers"] | null;
            head_to_head: components["schemas"]["HeadToHead"];
            /** Model Version */
            model_version: string | null;
            /** Next Ball */
            next_ball: components["schemas"]["NextBall"][];
            /**
             * Phase
             * @description Phase filter applied to the record, if any.
             */
            phase: ("powerplay" | "middle" | "death") | null;
            raw: components["schemas"]["MatchupNumbers"] | null;
            sample: components["schemas"]["SampleSize"];
            window: components["schemas"]["SeasonWindow"];
        };
        /** MatchupDismissal */
        MatchupDismissal: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Kind */
            kind: string;
            /** Match Id */
            match_id: number;
            /** Season */
            season: number;
        };
        /** MatchupList */
        MatchupList: {
            /** Items */
            items: components["schemas"]["MatchupListItem"][];
            /** Kappa */
            kappa: number | null;
            /** Total */
            total: number;
        };
        /** MatchupListItem */
        MatchupListItem: {
            /** Balls */
            balls: number;
            batter: components["schemas"]["MatchupPlayer"];
            bowler: components["schemas"]["MatchupPlayer"];
            /** Dismissals */
            dismissals: number;
            /**
             * Edge
             * @description Estimated minus expected strike rate: the matchup effect beyond form.
             */
            edge: number | null;
            /** Estimated Strike Rate */
            estimated_strike_rate: number | null;
            /** Expected Strike Rate */
            expected_strike_rate: number | null;
            /** Runs */
            runs: number;
            /** Strike Rate */
            strike_rate: number | null;
            /** Weight */
            weight: number;
        };
        /** MatchupNumbers */
        MatchupNumbers: {
            balls_per_dismissal: components["schemas"]["Interval"];
            boundary_pct: components["schemas"]["Interval"];
            dot_pct: components["schemas"]["Interval"];
            strike_rate: components["schemas"]["Interval"];
        };
        /** MatchupPlayer */
        MatchupPlayer: {
            /** Batting Hand */
            batting_hand: ("right" | "left") | null;
            /** Bowling Style */
            bowling_style: string | null;
            /** Bowling Type */
            bowling_type: ("pace" | "spin") | null;
            /** Full Name */
            full_name: string | null;
            /** Name */
            name: string;
            /** Player Id */
            player_id: string;
            team: components["schemas"]["TeamTag"] | null;
        };
        /** MatchupSplitRow */
        MatchupSplitRow: {
            /** Balls */
            balls: number;
            /** Dismissals */
            dismissals: number;
            /** Expected Strike Rate */
            expected_strike_rate: number | null;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Runs */
            runs: number;
            /** Strike Rate */
            strike_rate: number | null;
        };
        /** Meta */
        Meta: {
            /**
             * Api Version
             * @constant
             */
            api_version: "v1";
            /** App Version */
            app_version: string;
            /** Data Version */
            data_version: string;
            /** Franchises */
            franchises: components["schemas"]["FranchiseInfo"][];
            /** Model Versions */
            model_versions: {
                [key: string]: string;
            };
            /** Seasons */
            seasons: components["schemas"]["SeasonInfo"][];
            /** Venues */
            venues: components["schemas"]["VenueInfo"][];
        };
        /** NextBall */
        NextBall: {
            /** Expected Runs */
            expected_runs: number;
            /** Expected Runs With History */
            expected_runs_with_history: number;
            /** Label */
            label: string;
            /**
             * Model
             * @description From the players' overall records.
             */
            model: components["schemas"]["OutcomeProbability"][];
            /**
             * Phase
             * @enum {string}
             */
            phase: "powerplay" | "middle" | "death";
            /**
             * With History
             * @description Adjusted by the shrunk head-to-head record.
             */
            with_history: components["schemas"]["OutcomeProbability"][];
        };
        /** NextBallRequest */
        NextBallRequest: {
            /**
             * Batter Balls
             * @description Balls the batter has faced.
             * @default 20
             */
            batter_balls: number;
            /** Batter Id */
            batter_id: string;
            /** Bowler Id */
            bowler_id: string;
            /**
             * Innings
             * @default 1
             * @enum {integer}
             */
            innings: 1 | 2;
            /**
             * Phase
             * @default middle
             * @enum {string}
             */
            phase: "powerplay" | "middle" | "death";
            /**
             * Pressure
             * @description Required rate against par; chases only.
             */
            pressure?: ("low" | "par" | "high" | "extreme") | null;
            /**
             * Wickets
             * @description Wickets down before the ball.
             * @default 2
             */
            wickets: number;
        };
        /** NextBallResponse */
        NextBallResponse: {
            batter: components["schemas"]["MatchupPlayer"];
            bowler: components["schemas"]["MatchupPlayer"];
            /** Expected Runs */
            expected_runs: number;
            /** Expected Runs With History */
            expected_runs_with_history: number;
            /** History Balls */
            history_balls: number;
            /** Model */
            model: components["schemas"]["OutcomeProbability"][];
            /** Model Version */
            model_version: string;
            request: components["schemas"]["NextBallRequest"];
            /** With History */
            with_history: components["schemas"]["OutcomeProbability"][];
        };
        /** OpponentRecord */
        OpponentRecord: {
            opponent: components["schemas"]["TeamTag"];
            record: components["schemas"]["Record"];
        };
        /** OutcomeProbability */
        OutcomeProbability: {
            /** Label */
            label: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "dot" | "one" | "two" | "three" | "four" | "six" | "out";
            /** Probability */
            probability: number;
        };
        /** PhaseBatting */
        PhaseBatting: {
            /** Average */
            average: number | null;
            /** Balls */
            balls: number;
            /** Boundary Pct */
            boundary_pct: number | null;
            /** Dot Pct */
            dot_pct: number | null;
            /** Label */
            label: string;
            /** Outs */
            outs: number;
            /** Par Boundary Pct */
            par_boundary_pct: number | null;
            /** Par Dot Pct */
            par_dot_pct: number | null;
            /** Par Strike Rate */
            par_strike_rate: number | null;
            /** Phase */
            phase: string;
            /** Runs */
            runs: number;
            /**
             * Share
             * @description Share of the player's balls in this phase (0-1).
             */
            share: number;
            /** Strike Rate */
            strike_rate: number | null;
        };
        /** PhaseBowling */
        PhaseBowling: {
            /** Average */
            average: number | null;
            /** Balls */
            balls: number;
            /** Dot Pct */
            dot_pct: number | null;
            /** Economy */
            economy: number | null;
            /** Label */
            label: string;
            /** Par Dot Pct */
            par_dot_pct: number | null;
            /** Par Economy */
            par_economy: number | null;
            /** Phase */
            phase: string;
            /** Runs */
            runs: number;
            /** Share */
            share: number;
            /** Strike Rate */
            strike_rate: number | null;
            /** Wickets */
            wickets: number;
        };
        /** PhaseLine */
        PhaseLine: {
            /** Balls */
            balls: number;
            /** Balls Per Wicket */
            balls_per_wicket: number | null;
            /** Boundary Pct */
            boundary_pct: number | null;
            /** Dot Pct */
            dot_pct: number | null;
            /** Par Balls Per Wicket */
            par_balls_per_wicket: number | null;
            /** Par Boundary Pct */
            par_boundary_pct: number | null;
            /** Par Dot Pct */
            par_dot_pct: number | null;
            /**
             * Par Run Rate
             * @description League run rate in the same seasons and phase, weighted by this side's balls.
             */
            par_run_rate: number | null;
            /** Run Rate */
            run_rate: number | null;
            /** Runs */
            runs: number;
            /** Wickets */
            wickets: number;
        };
        /** PhaseSplits */
        PhaseSplits: {
            /** Batting */
            batting: components["schemas"]["PhaseBatting"][];
            /** Bowling */
            bowling: components["schemas"]["PhaseBowling"][];
        };
        /** PlayerBio */
        PlayerBio: {
            /** Batting Hand */
            batting_hand: ("right" | "left") | null;
            /** Bowling Arm */
            bowling_arm: ("right" | "left") | null;
            /** Bowling Style */
            bowling_style: string | null;
            /** Bowling Type */
            bowling_type: ("pace" | "spin") | null;
            /** Country */
            country: string | null;
            /** Date Of Birth */
            date_of_birth: string | null;
            /** First Season */
            first_season: number;
            /** Full Name */
            full_name: string | null;
            /** Is Keeper */
            is_keeper: boolean;
            /** Last Season */
            last_season: number;
            /** Matches */
            matches: number;
            /** Name */
            name: string;
            /** Player Id */
            player_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "batter" | "bowler" | "all_rounder";
            /**
             * Teams
             * @description Franchises played for, most recent first.
             */
            teams: components["schemas"]["TeamStint"][];
        };
        /** PlayerListItem */
        PlayerListItem: {
            /** Batting Average */
            batting_average: number | null;
            /** Country */
            country: string | null;
            /** Economy */
            economy: number | null;
            /**
             * First Season
             * @description Career debut season.
             */
            first_season: number;
            /** Full Name */
            full_name: string | null;
            /** Is Keeper */
            is_keeper: boolean;
            /**
             * Last Season
             * @description Most recent season played.
             */
            last_season: number;
            /**
             * Matches
             * @description Matches within the filters.
             */
            matches: number;
            /** Name */
            name: string;
            /** Player Id */
            player_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "batter" | "bowler" | "all_rounder";
            /** Runs */
            runs: number;
            /** Strike Rate */
            strike_rate: number | null;
            /** @description Most recent team within the filters. */
            team: components["schemas"]["TeamTag"] | null;
            /** Wickets */
            wickets: number;
        };
        /** PlayerPage */
        PlayerPage: {
            /** Items */
            items: components["schemas"]["PlayerListItem"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** PlayerProfile */
        PlayerProfile: {
            batting: components["schemas"]["BattingSummary"] | null;
            bowling: components["schemas"]["BowlingSummary"] | null;
            dismissals: components["schemas"]["Dismissals"];
            fielding: components["schemas"]["FieldingSummary"];
            phases: components["schemas"]["PhaseSplits"];
            player: components["schemas"]["PlayerBio"];
            ratings: components["schemas"]["Ratings"];
            recent: components["schemas"]["RecentInnings"];
            /** Seasons */
            seasons: components["schemas"]["SeasonLine"][];
            window: components["schemas"]["SeasonWindow"];
        };
        /** PlayerRef */
        PlayerRef: {
            /** Name */
            name: string;
            /** Player Id */
            player_id: string;
        };
        /** PlayerSplits */
        PlayerSplits: {
            /** Batting */
            batting: components["schemas"]["BattingSplitGroup"][];
            /** Bowling */
            bowling: components["schemas"]["BowlingSplitGroup"][];
            window: components["schemas"]["SeasonWindow"];
        };
        /**
         * Rate
         * @description A share of decided matches with a 90% Wilson interval.
         */
        Rate: {
            /** High */
            high: number | null;
            /** Hits */
            hits: number;
            /** Low */
            low: number | null;
            /** Pct */
            pct: number | null;
            /** Total */
            total: number;
        };
        /**
         * Rating
         * @description One CricIQ Rating: a percentile among qualified players, after shrinkage.
         */
        Rating: {
            /**
             * Average
             * @description Qualified players' average, in ``unit``.
             */
            average: number | null;
            /** Description */
            description: string;
            /**
             * Exposure
             * @description Balls or innings behind the estimate.
             */
            exposure: number;
            /**
             * Exposure Unit
             * @enum {string}
             */
            exposure_unit: "balls" | "innings";
            /**
             * High
             * @description Upper end of the 90% interval of the rating.
             */
            high: number | null;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Low
             * @description Lower end of the 90% interval of the rating.
             */
            low: number | null;
            /**
             * Qualified
             * @description Whether the player is in the reference population.
             */
            qualified: boolean;
            /**
             * Rating
             * @description 0-100: share of qualified players in the window with a lower estimate. None below the minimum sample.
             */
            rating: number | null;
            /**
             * Raw
             * @description The player's own record, in ``unit``.
             */
            raw: number | null;
            /**
             * Stability
             * @description How strongly single-season ratings persist into the next season.
             * @enum {string}
             */
            stability: "high" | "moderate" | "low";
            /**
             * Unit
             * @enum {string}
             */
            unit: "runs_per_100" | "dismissals_per_100" | "runs_per_over" | "wickets_per_4_overs" | "points" | "percent";
            /**
             * Value
             * @description Shrunk estimate, in ``unit`` (higher is better).
             */
            value: number | null;
            /**
             * Weight
             * @description Share of the estimate that comes from the player's record.
             */
            weight: number;
        };
        /** RatingGroup */
        RatingGroup: {
            /** Balls */
            balls: number;
            /** Items */
            items: components["schemas"]["Rating"][];
            /** Min Balls */
            min_balls: number;
            /**
             * Population
             * @description Qualified players in the window.
             */
            population: number;
            /**
             * Qualified
             * @description At least ``min_balls`` in the role in the window.
             */
            qualified: boolean;
        };
        /** Ratings */
        Ratings: {
            batting: components["schemas"]["RatingGroup"] | null;
            bowling: components["schemas"]["RatingGroup"] | null;
        };
        /** RecentInnings */
        RecentInnings: {
            /** Batting */
            batting: components["schemas"]["BattingInnings"][];
            /** Bowling */
            bowling: components["schemas"]["BowlingInnings"][];
        };
        /**
         * Record
         * @description Results; a tie settled by a super over counts for the super-over winner.
         */
        Record: {
            /** Lost */
            lost: number;
            /** No Result */
            no_result: number;
            /** Played */
            played: number;
            /**
             * Win Pct
             * @description Wins as a percentage of decided matches.
             */
            win_pct: number | null;
            /** Won */
            won: number;
        };
        /** RecordGroup */
        RecordGroup: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Splits */
            splits: components["schemas"]["RecordSplit"][];
        };
        /** RecordSplit */
        RecordSplit: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            record: components["schemas"]["Record"];
        };
        /** SampleSize */
        SampleSize: {
            /** Balls */
            balls: number;
            /**
             * Kappa
             * @description Prior strength, in balls, fitted across all pairs.
             */
            kappa: number;
            /**
             * Level
             * @enum {string}
             */
            level: "none" | "tiny" | "small" | "moderate" | "large";
            /**
             * Weight
             * @description Share of the estimate that comes from head-to-head balls.
             */
            weight: number;
        };
        /**
         * ScoreProjectionModel
         * @description The model behind a timeline's first-innings score projections.
         */
        ScoreProjectionModel: {
            /**
             * Levels
             * @description Quantile level of each value in `projection`.
             */
            levels: number[];
            /** Trained From */
            trained_from: number;
            /** Trained Through */
            trained_through: number;
            /** Version */
            version: string;
        };
        /** SeasonBatting */
        SeasonBatting: {
            /** Average */
            average: number | null;
            /** Balls */
            balls: number;
            /** Fifties */
            fifties: number;
            /** Highest */
            highest: number;
            /** Hundreds */
            hundreds: number;
            /** Innings */
            innings: number;
            /** Outs */
            outs: number;
            /** Par Strike Rate */
            par_strike_rate: number | null;
            /** Runs */
            runs: number;
            /** Strike Rate */
            strike_rate: number | null;
        };
        /** SeasonBowling */
        SeasonBowling: {
            /** Average */
            average: number | null;
            /** Balls */
            balls: number;
            /** Economy */
            economy: number | null;
            /** Innings */
            innings: number;
            /** Par Economy */
            par_economy: number | null;
            /** Runs */
            runs: number;
            /** Strike Rate */
            strike_rate: number | null;
            /** Wickets */
            wickets: number;
        };
        /** SeasonChampion */
        SeasonChampion: {
            champion: components["schemas"]["TeamTag"];
            /** Final Match Id */
            final_match_id: number | null;
            /** Result Text */
            result_text: string | null;
            runner_up: components["schemas"]["TeamTag"] | null;
            /** Season */
            season: number;
        };
        /** SeasonInfo */
        SeasonInfo: {
            /** Impact Player Rule */
            impact_player_rule: boolean;
            /** Matches */
            matches: number;
            /** Year */
            year: number;
        };
        /** SeasonLine */
        SeasonLine: {
            batting: components["schemas"]["SeasonBatting"] | null;
            bowling: components["schemas"]["SeasonBowling"] | null;
            /** Matches */
            matches: number;
            /** Season */
            season: number;
            /** Teams */
            teams: string[];
        };
        /** SeasonTrend */
        SeasonTrend: {
            /** Avg First Innings */
            avg_first_innings: number | null;
            /** Chasing Win Pct */
            chasing_win_pct: number | null;
            /**
             * Field First Pct
             * @description Share of tosses won where the side bowled.
             */
            field_first_pct: number | null;
            /**
             * Home Win Pct
             * @description None when the season had no home games.
             */
            home_win_pct: number | null;
            /**
             * Matches
             * @description Decided matches.
             */
            matches: number;
            /** Season */
            season: number;
            /** Toss Winner Win Pct */
            toss_winner_win_pct: number | null;
        };
        /** SeasonWindow */
        SeasonWindow: {
            /**
             * First
             * @description First season included.
             */
            first: number;
            /**
             * Last
             * @description Last season included.
             */
            last: number;
        };
        /** SimilarPlayer */
        SimilarPlayer: {
            /**
             * Balls
             * @description The player's balls in the role in the window.
             */
            balls: number;
            /** Name */
            name: string;
            /** Player Id */
            player_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "batter" | "bowler" | "all_rounder";
            /**
             * Shared
             * @description Style traits both players share.
             */
            shared: string[];
            /**
             * Similarity
             * @description Cosine similarity of the two style profiles (-1 to 1).
             */
            similarity: number;
            /** @description Most recent team. */
            team: components["schemas"]["TeamTag"] | null;
        };
        /** SimilarPlayers */
        SimilarPlayers: {
            batting: components["schemas"]["StyleGroup"] | null;
            bowling: components["schemas"]["StyleGroup"] | null;
            window: components["schemas"]["SeasonWindow"];
        };
        /** StandingRow */
        StandingRow: {
            /**
             * Exit Stage
             * @description Last playoff match for sides that did not win.
             */
            exit_stage: string | null;
            /**
             * Finish
             * @enum {string}
             */
            finish: "champion" | "runner_up" | "playoffs" | "league";
            /** Lost */
            lost: number;
            /**
             * No Result
             * @description Includes fixtures abandoned without a ball bowled.
             */
            no_result: number;
            /** Nrr */
            nrr: number | null;
            /** Played */
            played: number;
            /** Points */
            points: number;
            /** Position */
            position: number;
            team: components["schemas"]["TeamTag"];
            /**
             * Team Name
             * @description The name the side played under that season.
             */
            team_name: string;
            /** Won */
            won: number;
        };
        /** Standings */
        Standings: {
            /**
             * Abandoned
             * @description League fixtures abandoned without a ball bowled.
             */
            abandoned: number;
            /** Playoffs */
            playoffs: components["schemas"]["MatchSummary"][];
            /** Rows */
            rows: components["schemas"]["StandingRow"][];
            /** Season */
            season: number;
        };
        /** StyleGroup */
        StyleGroup: {
            /** Items */
            items: components["schemas"]["SimilarPlayer"][];
            /** Min Balls */
            min_balls: number;
            /**
             * Population
             * @description Players compared (at least the minimum balls).
             */
            population: number;
            /**
             * Traits
             * @description The player's most distinctive traits.
             */
            traits: string[];
        };
        /**
         * Swing
         * @description A win from a low win probability, or a defeat from a high one.
         */
        Swing: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Innings No */
            innings_no: number;
            /** Match Id */
            match_id: number;
            opponent: components["schemas"]["TeamTag"];
            /** Result Text */
            result_text: string;
            /** Season */
            season: number;
            /** Seq No */
            seq_no: number;
            /**
             * Situation
             * @description The score at that ball, e.g. 'CSK 45/4 after 9.2 overs'.
             */
            situation: string;
            /**
             * Win Probability
             * @description The side's lowest (comeback) or highest (collapse).
             */
            win_probability: number;
        };
        /** TeamBatter */
        TeamBatter: {
            /** Average */
            average: number | null;
            /** Balls */
            balls: number;
            /** Innings */
            innings: number;
            /** Name */
            name: string;
            /** Player Id */
            player_id: string;
            /** Runs */
            runs: number;
            /** Strike Rate */
            strike_rate: number | null;
        };
        /** TeamBowler */
        TeamBowler: {
            /** Average */
            average: number | null;
            /** Balls */
            balls: number;
            /** Economy */
            economy: number | null;
            /** Innings */
            innings: number;
            /** Name */
            name: string;
            /** Player Id */
            player_id: string;
            /** Wickets */
            wickets: number;
        };
        /** TeamHeadToHead */
        TeamHeadToHead: {
            a: components["schemas"]["TeamTag"];
            b: components["schemas"]["TeamTag"];
            /** Batters */
            batters: components["schemas"]["H2HPlayer"][];
            /** Bowlers */
            bowlers: components["schemas"]["H2HPlayer"][];
            expectation: components["schemas"]["H2HExpectation"] | null;
            /**
             * Meetings
             * @description Every meeting in the window, newest first.
             */
            meetings: components["schemas"]["MatchSummary"][];
            record: components["schemas"]["H2HRecord"];
            scoring: components["schemas"]["H2HScoring"];
            /** Seasons */
            seasons: components["schemas"]["H2HSeason"][];
            /** Splits */
            splits: components["schemas"]["H2HSplit"][];
            window: components["schemas"]["SeasonWindow"];
        };
        /** TeamMargin */
        TeamMargin: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Match Id */
            match_id: number;
            opponent: components["schemas"]["TeamTag"];
            /** Result Text */
            result_text: string;
            /** Season */
            season: number;
        };
        /** TeamPhase */
        TeamPhase: {
            batting: components["schemas"]["PhaseLine"];
            bowling: components["schemas"]["PhaseLine"];
            /** Label */
            label: string;
            /** Phase */
            phase: string;
        };
        /** TeamProfile */
        TeamProfile: {
            /** Batters */
            batters: components["schemas"]["TeamBatter"][];
            /** Bowlers */
            bowlers: components["schemas"]["TeamBowler"][];
            /** @description Close finishes in the window. */
            close: components["schemas"]["Record"];
            /** Collapses */
            collapses: components["schemas"]["Swing"][];
            /** Comebacks */
            comebacks: components["schemas"]["Swing"][];
            /** Opponents */
            opponents: components["schemas"]["OpponentRecord"][];
            /** Phases */
            phases: components["schemas"]["TeamPhase"][];
            record: components["schemas"]["Record"];
            scoring: components["schemas"]["TeamScoring"];
            /**
             * Seasons
             * @description Every season, regardless of the window.
             */
            seasons: components["schemas"]["TeamSeason"][];
            /** Splits */
            splits: components["schemas"]["RecordGroup"][];
            team: components["schemas"]["FranchiseSummary"];
            /** Venues */
            venues: components["schemas"]["VenueRecord"][];
            window: components["schemas"]["SeasonWindow"];
        };
        /** TeamRef */
        TeamRef: {
            /** Color */
            color: string;
            /** Franchise Id */
            franchise_id: string;
            /** Name */
            name: string;
            /** Team Season Id */
            team_season_id: string;
        };
        /** TeamScore */
        TeamScore: {
            /** Color */
            color: string;
            /** Franchise Id */
            franchise_id: string;
            /** Name */
            name: string;
            /**
             * Overs
             * @description Scoreboard overs, e.g. '19.4'.
             */
            overs: string | null;
            /** Runs */
            runs: number | null;
            /** Team Season Id */
            team_season_id: string;
            /** Wickets */
            wickets: number | null;
        };
        /** TeamScoring */
        TeamScoring: {
            /** Avg First Innings */
            avg_first_innings: number | null;
            biggest_win_runs: components["schemas"]["TeamMargin"] | null;
            biggest_win_wickets: components["schemas"]["TeamMargin"] | null;
            /** First Innings */
            first_innings: number;
            highest: components["schemas"]["TeamTotal"] | null;
            /** @description Lowest completed total (bowled out or 20 overs). */
            lowest: components["schemas"]["TeamTotal"] | null;
        };
        /** TeamSeason */
        TeamSeason: {
            /** Exit Stage */
            exit_stage: string | null;
            /**
             * Finish
             * @enum {string}
             */
            finish: "champion" | "runner_up" | "playoffs" | "league";
            /** Lost */
            lost: number;
            /** No Result */
            no_result: number;
            /** Nrr */
            nrr: number | null;
            /** Played */
            played: number;
            /** Playoff Lost */
            playoff_lost: number;
            /** Playoff Won */
            playoff_won: number;
            /** Points */
            points: number;
            /** Position */
            position: number;
            /** Season */
            season: number;
            /** Team Name */
            team_name: string;
            /** Teams */
            teams: number;
            /** Won */
            won: number;
        };
        /** TeamStint */
        TeamStint: {
            /** Color */
            color: string;
            /** Franchise Id */
            franchise_id: string;
            /** Matches */
            matches: number;
            /** Name */
            name: string;
            /** Seasons */
            seasons: number[];
        };
        /** TeamTag */
        TeamTag: {
            /** Color */
            color: string;
            /** Franchise Id */
            franchise_id: string;
            /** Name */
            name: string;
        };
        /** TeamTotal */
        TeamTotal: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Match Id */
            match_id: number;
            opponent: components["schemas"]["TeamTag"];
            /** Overs */
            overs: string;
            /** Runs */
            runs: number;
            /** Season */
            season: number;
            /** Wickets */
            wickets: number;
        };
        /** TeamsOverview */
        TeamsOverview: {
            /** Champions */
            champions: components["schemas"]["SeasonChampion"][];
            /** Franchises */
            franchises: components["schemas"]["FranchiseSummary"][];
            league: components["schemas"]["LeagueTrends"];
            /** Seasons */
            seasons: number[];
        };
        /**
         * Timeline
         * @description Everything the client needs to replay a match ball by ball, in one payload.
         */
        Timeline: {
            /** Deliveries */
            deliveries: components["schemas"]["TimelineDelivery"][];
            /** Innings */
            innings: components["schemas"]["TimelineInnings"][];
            /** Players */
            players: {
                [key: string]: components["schemas"]["TimelinePlayer"];
            };
            /** @description Present when the first innings has score projections. */
            score_projection?: components["schemas"]["ScoreProjectionModel"] | null;
            /** Substitutions */
            substitutions: components["schemas"]["TimelineSubstitution"][];
            summary: components["schemas"]["MatchSummary"];
            /** Teams */
            teams: {
                [key: string]: components["schemas"]["TeamRef"];
            };
            /** @description Present when the match has model win probabilities. */
            win_probability?: components["schemas"]["WinProbabilityModel"] | null;
        };
        /** TimelineDelivery */
        TimelineDelivery: {
            /** Ball Label */
            ball_label: string | null;
            /** Batter Id */
            batter_id: string;
            /** Bowler Id */
            bowler_id: string;
            /** Byes */
            byes: number;
            /**
             * Factors
             * @description Percentage points each factor adds to the batting side's chance, relative to the model's average, in the order of Timeline.win_probability.factor_keys. Absent once the result is certain.
             */
            factors?: number[] | null;
            /** Innings No */
            innings_no: number;
            /** Is Four */
            is_four: boolean;
            /** Is Legal */
            is_legal: boolean;
            /** Is Six */
            is_six: boolean;
            /**
             * Legal Ball No
             * @description Legal balls bowled in the innings after this delivery.
             */
            legal_ball_no: number;
            /** Legbyes */
            legbyes: number;
            /**
             * Leverage
             * @description How much the next ball can move the match: expected change in win probability over the next ball, relative to a typical ball (1 = typical).
             */
            leverage?: number | null;
            /**
             * Momentum
             * @description Change in the batting side's win probability over the last 12 legal balls, in percentage points.
             */
            momentum?: number | null;
            /** Noballs */
            noballs: number;
            /** Non Striker Id */
            non_striker_id: string;
            /**
             * Over No
             * @description 0-based over number.
             */
            over_no: number;
            /** Penalty */
            penalty: number;
            /**
             * Pressure
             * @description Pressure index for the next ball: percentile of leverage among every historical IPL ball (0-100).
             */
            pressure?: number | null;
            /**
             * Projection
             * @description First innings only: quantiles of the final total after this ball, at the levels in Timeline.score_projection.levels (model estimate).
             */
            projection?: number[] | null;
            /** Runs Batter */
            runs_batter: number;
            /** Runs Extras */
            runs_extras: number;
            /** Runs Total */
            runs_total: number;
            /** Seq No */
            seq_no: number;
            /**
             * Team Runs
             * @description Innings score after this delivery.
             */
            team_runs: number;
            /** Team Wickets */
            team_wickets: number;
            wicket: components["schemas"]["TimelineWicket"] | null;
            /** Wides */
            wides: number;
            /**
             * Wp
             * @description Win probability of the side batting first after this ball (model estimate).
             */
            wp?: number | null;
        };
        /** TimelineInnings */
        TimelineInnings: {
            /** Batting Team Id */
            batting_team_id: string;
            /** Bowling Team Id */
            bowling_team_id: string;
            /**
             * Factors Start
             * @description Explanation of wp_start (see Timeline.win_probability).
             */
            factors_start?: number[] | null;
            /** Innings No */
            innings_no: number;
            /** Is Super Over */
            is_super_over: boolean;
            /**
             * Leverage Start
             * @description How much the next ball can move the match: expected change in win probability over the next ball, relative to a typical ball (1 = typical).
             */
            leverage_start?: number | null;
            /**
             * Max Balls
             * @description Legal balls available to the batting side.
             */
            max_balls: number;
            /**
             * Pressure Start
             * @description Pressure index for the next ball: percentile of leverage among every historical IPL ball (0-100).
             */
            pressure_start?: number | null;
            /**
             * Projection Start
             * @description First innings only: quantiles of the final total before the first ball.
             */
            projection_start?: number[] | null;
            /** Target Balls */
            target_balls: number | null;
            /** Target Runs */
            target_runs: number | null;
            /**
             * Wp Start
             * @description Win probability of the side batting first before this innings' first ball.
             */
            wp_start?: number | null;
        };
        /** TimelinePlayer */
        TimelinePlayer: {
            /** Full Name */
            full_name: string | null;
            /** Name */
            name: string;
        };
        /** TimelineSubstitution */
        TimelineSubstitution: {
            /** Innings No */
            innings_no: number;
            /** Player In Id */
            player_in_id: string | null;
            /** Player Out Id */
            player_out_id: string | null;
            /** Reason */
            reason: string | null;
            /** Seq No */
            seq_no: number;
            /** Team Season Id */
            team_season_id: string;
        };
        /** TimelineWicket */
        TimelineWicket: {
            /** Bowler Credited */
            bowler_credited: boolean;
            /** Fielder Ids */
            fielder_ids: string[];
            /** Is Dismissal */
            is_dismissal: boolean;
            /** Kind */
            kind: string;
            /** Player Out Id */
            player_out_id: string;
        };
        /** Toss */
        Toss: {
            /** Decision */
            decision: ("bat" | "field") | null;
            /** Winner Id */
            winner_id: string | null;
            /** Winner Name */
            winner_name: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VenueInfo */
        VenueInfo: {
            /** City */
            city: string;
            /** Country */
            country: string;
            /** Matches */
            matches: number;
            /** Name */
            name: string;
            /** Venue Id */
            venue_id: string;
        };
        /** VenueRecord */
        VenueRecord: {
            /** City */
            city: string;
            /** Name */
            name: string;
            record: components["schemas"]["Record"];
            /** Venue Id */
            venue_id: string;
        };
        /** VenueRef */
        VenueRef: {
            /** City */
            city: string;
            /** Name */
            name: string;
            /** Venue Id */
            venue_id: string;
        };
        /**
         * WinProbabilityModel
         * @description The model behind a timeline's win probabilities.
         */
        WinProbabilityModel: {
            /**
             * Base Innings1
             * @description Average first-innings estimate: the reference point for its factors.
             */
            base_innings1: number;
            /**
             * Base Innings2
             * @description Average chase estimate: the reference point for its factors.
             */
            base_innings2: number;
            /**
             * Factor Keys
             * @description Order of the values in each `factors` list.
             */
            factor_keys: string[];
            /**
             * Pressure Thresholds
             * @description Leverage at the pressure index's band edges (50, 80 and 95): where Medium, High and Very high pressure begin.
             */
            pressure_thresholds?: number[] | null;
            /** Trained From */
            trained_from: number;
            /** Trained Through */
            trained_through: number;
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_matches_api_v1_matches_get: {
        parameters: {
            query?: {
                season?: number | null;
                /** @description Franchise id, e.g. MI */
                team?: string | null;
                /** @description Venue id */
                venue?: string | null;
                /** @description Only playoffs (true) or league */
                playoffs?: boolean | null;
                sort?: "latest" | "oldest";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_match_api_v1_matches__match_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_timeline_api_v1_matches__match_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_matchups_api_v1_matchups_get: {
        parameters: {
            query?: {
                batter?: string | null;
                bowler?: string | null;
                /** @description First season (inclusive). */
                from?: number | null;
                /** @description Last season (inclusive). */
                to?: number | null;
                min_balls?: number;
                sort?: "balls" | "batter_edge" | "bowler_edge";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchupList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_matchup_api_v1_matchups__batter_id___bowler_id__get: {
        parameters: {
            query?: {
                /** @description First season (inclusive). */
                from?: number | null;
                /** @description Last season (inclusive). */
                to?: number | null;
                phase?: ("powerplay" | "middle" | "death") | null;
            };
            header?: never;
            path: {
                batter_id: string;
                bowler_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchupDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    list_players_api_v1_players_get: {
        parameters: {
            query?: {
                /** @description Name search */
                q?: string | null;
                role?: ("batter" | "bowler" | "all_rounder" | "keeper") | null;
                season?: number | null;
                /** @description Franchise id, e.g. MI */
                team?: string | null;
                sort?: "matches" | "runs" | "wickets" | "recent" | "name";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_player_api_v1_players__player_id__get: {
        parameters: {
            query?: {
                /** @description First season (inclusive). */
                from?: number | null;
                /** @description Last season (inclusive). */
                to?: number | null;
            };
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_similar_api_v1_players__player_id__similar_get: {
        parameters: {
            query?: {
                /** @description First season (inclusive). */
                from?: number | null;
                /** @description Last season (inclusive). */
                to?: number | null;
            };
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarPlayers"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_splits_api_v1_players__player_id__splits_get: {
        parameters: {
            query?: {
                /** @description First season (inclusive). */
                from?: number | null;
                /** @description Last season (inclusive). */
                to?: number | null;
            };
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerSplits"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_next_ball_api_v1_predict_next_ball_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NextBallRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextBallResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_overview_api_v1_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamsOverview"];
                };
            };
        };
    };
    read_head_to_head_api_v1_teams_h2h_get: {
        parameters: {
            query: {
                /** @description Franchise id, e.g. MI */
                a: string;
                /** @description Franchise id, e.g. MI */
                b: string;
                /** @description First season (inclusive). */
                from?: number | null;
                /** @description Last season (inclusive). */
                to?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamHeadToHead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_standings_api_v1_teams_standings__season__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Standings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_team_api_v1_teams__franchise_id__get: {
        parameters: {
            query?: {
                /** @description First season (inclusive). */
                from?: number | null;
                /** @description Last season (inclusive). */
                to?: number | null;
            };
            header?: never;
            path: {
                franchise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
