/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Matches
         * @description Paginated match summaries, newest first by default.
         */
        get: operations["list_matches_api_v1_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Match
         * @description Match summary with full scorecards for every innings.
         */
        get: operations["read_match_api_v1_matches__match_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Timeline
         * @description Every delivery with running state: one payload drives a full client-side replay.
         */
        get: operations["read_timeline_api_v1_matches__match_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Meta
         * @description Dataset version and the seasons, franchises and venues available for filtering.
         */
        get: operations["read_meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Players
         * @description Player directory with headline numbers; season and team filters scope the numbers.
         */
        get: operations["list_players_api_v1_players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Player
         * @description Profile: batting and bowling against par, seasons, phases, percentiles and recent form.
         */
        get: operations["read_player_api_v1_players__player_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{player_id}/splits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Splits
         * @description Batting and bowling split by phase, opponent type, position, venue, opposition and more.
         */
        get: operations["read_splits_api_v1_players__player_id__splits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BattingEntry */
        BattingEntry: {
            /** Balls */
            balls: number;
            /**
             * Dismissal
             * @description How out, e.g. 'c Dhoni b Bravo'; None if not out.
             */
            dismissal: string | null;
            /** Fours */
            fours: number;
            /** Is Out */
            is_out: boolean;
            /** Name */
            name: string;
            /** Player Id */
            player_id: string;
            /** Runs */
            runs: number;
            /** Sixes */
            sixes: number;
            /** Strike Rate */
            strike_rate: number | null;
        };
        /** BattingInnings */
        BattingInnings: {
            /** Balls */
            balls: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Dismissal */
            dismissal: string | null;
            /** Fours */
            fours: number;
            /** Is Out */
            is_out: boolean;
            /** Match Id */
            match_id: number;
            opposition: components["schemas"]["TeamTag"];
            /** Position */
            position: number;
            /**
             * Result
             * @enum {string}
             */
            result: "won" | "lost" | "no_result";
            /** Runs */
            runs: number;
            /** Season */
            season: number;
            /** Sixes */
            sixes: number;
            /** Venue */
            venue: string;
            /** Wpa */
            wpa: number | null;
        };
        /** BattingSplitGroup */
        BattingSplitGroup: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Rows */
            rows: components["schemas"]["BattingSplitRow"][];
        };
        /** BattingSplitRow */
        BattingSplitRow: {
            /** Average */
            average: number | null;
            /** Balls */
            balls: number;
            /** Boundary Pct */
            boundary_pct: number | null;
            /** Color */
            color?: string | null;
            /** Dot Pct */
            dot_pct: number | null;
            /** Fifties */
            fifties: number | null;
            /** Highest */
            highest: number | null;
            /**
             * Innings
             * @description None for ball-level splits (phase, bowler type).
             */
            innings: number | null;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Outs */
            outs: number;
            /** Par Strike Rate */
            par_strike_rate: number | null;
            /** Runs */
            runs: number;
            /** Strike Rate */
            strike_rate: number | null;
        };
        /** BattingSummary */
        BattingSummary: {
            /** Average */
            average: number | null;
            /** Balls */
            balls: number;
            /** Boundary Pct */
            boundary_pct: number | null;
            /** Dot Pct */
            dot_pct: number | null;
            /** Ducks */
            ducks: number;
            /** Fifties */
            fifties: number;
            /** Fours */
            fours: number;
            highest: components["schemas"]["HighScore"] | null;
            /** Hundreds */
            hundreds: number;
            /** Innings */
            innings: number;
            /** Matches */
            matches: number;
            /** Not Outs */
            not_outs: number;
            /** Outs */
            outs: number;
            /** Par Average */
            par_average: number | null;
            /** Par Boundary Pct */
            par_boundary_pct: number | null;
            /** Par Dot Pct */
            par_dot_pct: number | null;
            /** Par Strike Rate */
            par_strike_rate: number | null;
            /** Runs */
            runs: number;
            /**
             * Runs Above Par
             * @description Runs scored minus par runs for the same balls.
             */
            runs_above_par: number;
            /** Sixes */
            sixes: number;
            /** Strike Rate */
            strike_rate: number | null;
            /**
             * Wpa
             * @description Win probability added, in probability units.
             */
            wpa: number | null;
            /**
             * Wpa Innings
             * @description Innings with win probabilities behind ``wpa``.
             */
            wpa_innings: number;
        };
        /** BestFigures */
        BestFigures: {
            /** Match Id */
            match_id: number;
            /** Opposition Id */
            opposition_id: string;
            /** Runs */
            runs: number;
            /** Season */
            season: number;
            /** Wickets */
            wickets: number;
        };
        /** BowlingEntry */
        BowlingEntry: {
            /** Economy */
            economy: number | null;
            /** Maidens */
            maidens: number;
            /** Name */
            name: string;
            /** Noballs */
            noballs: number;
            /** Overs */
            overs: string;
            /** Player Id */
            player_id: string;
            /** Runs */
            runs: number;
            /** Wickets */
            wickets: number;
            /** Wides */
            wides: number;
        };
        /** BowlingInnings */
        BowlingInnings: {
            /** Balls */
            balls: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Economy */
            economy: number | null;
            /** Match Id */
            match_id: number;
            opposition: components["schemas"]["TeamTag"];
            /** Overs */
            overs: string;
            /**
             * Result
             * @enum {string}
             */
            result: "won" | "lost" | "no_result";
            /** Runs */
            runs: number;
            /** Season */
            season: number;
            /** Venue */
            venue: string;
            /** Wickets */
            wickets: number;
            /** Wpa */
            wpa: number | null;
        };
        /** BowlingSplitGroup */
        BowlingSplitGroup: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Rows */
            rows: components["schemas"]["BowlingSplitRow"][];
        };
        /** BowlingSplitRow */
        BowlingSplitRow: {
            /** Average */
            average: number | null;
            /** Balls */
            balls: number;
            /** Color */
            color?: string | null;
            /** Dot Pct */
            dot_pct: number | null;
            /** Economy */
            economy: number | null;
            /** Innings */
            innings: number | null;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Par Economy */
            par_economy: number | null;
            /** Runs */
            runs: number;
            /** Strike Rate */
            strike_rate: number | null;
            /** Wickets */
            wickets: number;
        };
        /** BowlingSummary */
        BowlingSummary: {
            /** Average */
            average: number | null;
            /** Balls */
            balls: number;
            best: components["schemas"]["BestFigures"] | null;
            /** Boundary Pct */
            boundary_pct: number | null;
            /** Dot Pct */
            dot_pct: number | null;
            /** Economy */
            economy: number | null;
            /**
             * Five Wickets
             * @description Innings with five or more wickets.
             */
            five_wickets: number;
            /**
             * Four Wickets
             * @description Innings with exactly four wickets.
             */
            four_wickets: number;
            /** Innings */
            innings: number;
            /** Maidens */
            maidens: number;
            /** Matches */
            matches: number;
            /** Noballs */
            noballs: number;
            /** Overs */
            overs: string;
            /** Par Dot Pct */
            par_dot_pct: number | null;
            /** Par Economy */
            par_economy: number | null;
            /** Par Strike Rate */
            par_strike_rate: number | null;
            /** Runs */
            runs: number;
            /**
             * Runs Saved
             * @description Par runs minus runs conceded for the same balls.
             */
            runs_saved: number;
            /** Strike Rate */
            strike_rate: number | null;
            /** Wickets */
            wickets: number;
            /** Wides */
            wides: number;
            /** Wpa */
            wpa: number | null;
            /** Wpa Innings */
            wpa_innings: number;
        };
        /** DismissalCount */
        DismissalCount: {
            /** Count */
            count: number;
            /** Kind */
            kind: string;
        };
        /** Dismissals */
        Dismissals: {
            /**
             * Batting
             * @description How the player got out.
             */
            batting: components["schemas"]["DismissalCount"][];
            /**
             * Bowling
             * @description How the player took wickets.
             */
            bowling: components["schemas"]["DismissalCount"][];
        };
        /** Extras */
        Extras: {
            /** Byes */
            byes: number;
            /** Legbyes */
            legbyes: number;
            /** Noballs */
            noballs: number;
            /** Penalty */
            penalty: number;
            /** Total */
            total: number;
            /** Wides */
            wides: number;
        };
        /** FallOfWicket */
        FallOfWicket: {
            /** Name */
            name: string;
            /** Overs */
            overs: string;
            /** Player Id */
            player_id: string;
            /** Runs */
            runs: number;
            /** Wicket */
            wicket: number;
        };
        /** FieldingSummary */
        FieldingSummary: {
            /** Catches */
            catches: number;
            /** Run Outs */
            run_outs: number;
            /** Stumpings */
            stumpings: number;
        };
        /** FranchiseInfo */
        FranchiseInfo: {
            /** First Season */
            first_season: number;
            /** Franchise Id */
            franchise_id: string;
            /** Is Active */
            is_active: boolean;
            /** Last Season */
            last_season: number | null;
            /** Name */
            name: string;
            /** Primary Color */
            primary_color: string;
            /** Secondary Color */
            secondary_color: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** HighScore */
        HighScore: {
            /** Match Id */
            match_id: number;
            /** Not Out */
            not_out: boolean;
            /** Opposition Id */
            opposition_id: string;
            /** Runs */
            runs: number;
            /** Season */
            season: number;
        };
        /** InningsScorecard */
        InningsScorecard: {
            /** Batting */
            batting: components["schemas"]["BattingEntry"][];
            batting_team: components["schemas"]["TeamRef"];
            /** Bowling */
            bowling: components["schemas"]["BowlingEntry"][];
            bowling_team: components["schemas"]["TeamRef"];
            /** Did Not Bat */
            did_not_bat: components["schemas"]["PlayerRef"][];
            extras: components["schemas"]["Extras"];
            /** Fall Of Wickets */
            fall_of_wickets: components["schemas"]["FallOfWicket"][];
            /** Innings No */
            innings_no: number;
            /** Is Super Over */
            is_super_over: boolean;
            /** Overs */
            overs: string;
            /** Runs */
            runs: number;
            /** Target Overs */
            target_overs: number | null;
            /** Target Runs */
            target_runs: number | null;
            /** Wickets */
            wickets: number;
        };
        /** MatchDetail */
        MatchDetail: {
            /** Innings */
            innings: components["schemas"]["InningsScorecard"][];
            summary: components["schemas"]["MatchSummary"];
        };
        /** MatchPage */
        MatchPage: {
            /** Items */
            items: components["schemas"]["MatchSummary"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** MatchSummary */
        MatchSummary: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Decided By Super Over */
            decided_by_super_over: boolean;
            /** Is Playoff */
            is_playoff: boolean;
            /** Match Id */
            match_id: number;
            /** Match Number */
            match_number: number | null;
            /**
             * Outcome Type
             * @enum {string}
             */
            outcome_type: "win" | "tie" | "no_result";
            /** Player Of Match */
            player_of_match: string[];
            /** Result Text */
            result_text: string;
            /** Season */
            season: number;
            /** Stage */
            stage: string;
            /** Target Runs */
            target_runs: number | null;
            /** @description The side that batted first. */
            team_a: components["schemas"]["TeamScore"];
            team_b: components["schemas"]["TeamScore"];
            toss: components["schemas"]["Toss"];
            venue: components["schemas"]["VenueRef"];
            /** Win Method */
            win_method: string | null;
            /** Winner Id */
            winner_id: string | null;
        };
        /** Meta */
        Meta: {
            /**
             * Api Version
             * @constant
             */
            api_version: "v1";
            /** App Version */
            app_version: string;
            /** Data Version */
            data_version: string;
            /** Franchises */
            franchises: components["schemas"]["FranchiseInfo"][];
            /** Model Versions */
            model_versions: {
                [key: string]: string;
            };
            /** Seasons */
            seasons: components["schemas"]["SeasonInfo"][];
            /** Venues */
            venues: components["schemas"]["VenueInfo"][];
        };
        /** Percentile */
        Percentile: {
            /**
             * Balls
             * @description The player's balls behind this metric.
             */
            balls: number;
            /** Description */
            description: string;
            /** Higher Is Better */
            higher_is_better: boolean;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Min Balls */
            min_balls: number;
            /**
             * Percentile
             * @description 0-100 among qualified players; None if unqualified.
             */
            percentile: number | null;
            /**
             * Population
             * @description Qualified players compared against.
             */
            population: number;
            /**
             * Unit
             * @enum {string}
             */
            unit: "runs_per_100" | "percent" | "runs_per_over" | "points";
            /** Value */
            value: number | null;
        };
        /** PercentileGroup */
        PercentileGroup: {
            /** Balls */
            balls: number;
            /** Items */
            items: components["schemas"]["Percentile"][];
            /** Min Balls */
            min_balls: number;
            /** Population */
            population: number;
            /** Qualified */
            qualified: boolean;
        };
        /** Percentiles */
        Percentiles: {
            batting: components["schemas"]["PercentileGroup"] | null;
            bowling: components["schemas"]["PercentileGroup"] | null;
        };
        /** PhaseBatting */
        PhaseBatting: {
            /** Average */
            average: number | null;
            /** Balls */
            balls: number;
            /** Boundary Pct */
            boundary_pct: number | null;
            /** Dot Pct */
            dot_pct: number | null;
            /** Label */
            label: string;
            /** Outs */
            outs: number;
            /** Par Boundary Pct */
            par_boundary_pct: number | null;
            /** Par Dot Pct */
            par_dot_pct: number | null;
            /** Par Strike Rate */
            par_strike_rate: number | null;
            /** Phase */
            phase: string;
            /** Runs */
            runs: number;
            /**
             * Share
             * @description Share of the player's balls in this phase (0-1).
             */
            share: number;
            /** Strike Rate */
            strike_rate: number | null;
        };
        /** PhaseBowling */
        PhaseBowling: {
            /** Average */
            average: number | null;
            /** Balls */
            balls: number;
            /** Dot Pct */
            dot_pct: number | null;
            /** Economy */
            economy: number | null;
            /** Label */
            label: string;
            /** Par Dot Pct */
            par_dot_pct: number | null;
            /** Par Economy */
            par_economy: number | null;
            /** Phase */
            phase: string;
            /** Runs */
            runs: number;
            /** Share */
            share: number;
            /** Strike Rate */
            strike_rate: number | null;
            /** Wickets */
            wickets: number;
        };
        /** PhaseSplits */
        PhaseSplits: {
            /** Batting */
            batting: components["schemas"]["PhaseBatting"][];
            /** Bowling */
            bowling: components["schemas"]["PhaseBowling"][];
        };
        /** PlayerBio */
        PlayerBio: {
            /** Batting Hand */
            batting_hand: ("right" | "left") | null;
            /** Bowling Arm */
            bowling_arm: ("right" | "left") | null;
            /** Bowling Style */
            bowling_style: string | null;
            /** Bowling Type */
            bowling_type: ("pace" | "spin") | null;
            /** Country */
            country: string | null;
            /** Date Of Birth */
            date_of_birth: string | null;
            /** First Season */
            first_season: number;
            /** Full Name */
            full_name: string | null;
            /** Is Keeper */
            is_keeper: boolean;
            /** Last Season */
            last_season: number;
            /** Matches */
            matches: number;
            /** Name */
            name: string;
            /** Player Id */
            player_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "batter" | "bowler" | "all_rounder";
            /**
             * Teams
             * @description Franchises played for, most recent first.
             */
            teams: components["schemas"]["TeamStint"][];
        };
        /** PlayerListItem */
        PlayerListItem: {
            /** Batting Average */
            batting_average: number | null;
            /** Country */
            country: string | null;
            /** Economy */
            economy: number | null;
            /**
             * First Season
             * @description Career debut season.
             */
            first_season: number;
            /** Full Name */
            full_name: string | null;
            /** Is Keeper */
            is_keeper: boolean;
            /**
             * Last Season
             * @description Most recent season played.
             */
            last_season: number;
            /**
             * Matches
             * @description Matches within the filters.
             */
            matches: number;
            /** Name */
            name: string;
            /** Player Id */
            player_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "batter" | "bowler" | "all_rounder";
            /** Runs */
            runs: number;
            /** Strike Rate */
            strike_rate: number | null;
            /** @description Most recent team within the filters. */
            team: components["schemas"]["TeamTag"] | null;
            /** Wickets */
            wickets: number;
        };
        /** PlayerPage */
        PlayerPage: {
            /** Items */
            items: components["schemas"]["PlayerListItem"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** PlayerProfile */
        PlayerProfile: {
            batting: components["schemas"]["BattingSummary"] | null;
            bowling: components["schemas"]["BowlingSummary"] | null;
            dismissals: components["schemas"]["Dismissals"];
            fielding: components["schemas"]["FieldingSummary"];
            percentiles: components["schemas"]["Percentiles"];
            phases: components["schemas"]["PhaseSplits"];
            player: components["schemas"]["PlayerBio"];
            recent: components["schemas"]["RecentInnings"];
            /** Seasons */
            seasons: components["schemas"]["SeasonLine"][];
            window: components["schemas"]["SeasonWindow"];
        };
        /** PlayerRef */
        PlayerRef: {
            /** Name */
            name: string;
            /** Player Id */
            player_id: string;
        };
        /** PlayerSplits */
        PlayerSplits: {
            /** Batting */
            batting: components["schemas"]["BattingSplitGroup"][];
            /** Bowling */
            bowling: components["schemas"]["BowlingSplitGroup"][];
            window: components["schemas"]["SeasonWindow"];
        };
        /** RecentInnings */
        RecentInnings: {
            /** Batting */
            batting: components["schemas"]["BattingInnings"][];
            /** Bowling */
            bowling: components["schemas"]["BowlingInnings"][];
        };
        /**
         * ScoreProjectionModel
         * @description The model behind a timeline's first-innings score projections.
         */
        ScoreProjectionModel: {
            /**
             * Levels
             * @description Quantile level of each value in `projection`.
             */
            levels: number[];
            /** Trained From */
            trained_from: number;
            /** Trained Through */
            trained_through: number;
            /** Version */
            version: string;
        };
        /** SeasonBatting */
        SeasonBatting: {
            /** Average */
            average: number | null;
            /** Balls */
            balls: number;
            /** Fifties */
            fifties: number;
            /** Highest */
            highest: number;
            /** Hundreds */
            hundreds: number;
            /** Innings */
            innings: number;
            /** Outs */
            outs: number;
            /** Par Strike Rate */
            par_strike_rate: number | null;
            /** Runs */
            runs: number;
            /** Strike Rate */
            strike_rate: number | null;
        };
        /** SeasonBowling */
        SeasonBowling: {
            /** Average */
            average: number | null;
            /** Balls */
            balls: number;
            /** Economy */
            economy: number | null;
            /** Innings */
            innings: number;
            /** Par Economy */
            par_economy: number | null;
            /** Runs */
            runs: number;
            /** Strike Rate */
            strike_rate: number | null;
            /** Wickets */
            wickets: number;
        };
        /** SeasonInfo */
        SeasonInfo: {
            /** Impact Player Rule */
            impact_player_rule: boolean;
            /** Matches */
            matches: number;
            /** Year */
            year: number;
        };
        /** SeasonLine */
        SeasonLine: {
            batting: components["schemas"]["SeasonBatting"] | null;
            bowling: components["schemas"]["SeasonBowling"] | null;
            /** Matches */
            matches: number;
            /** Season */
            season: number;
            /** Teams */
            teams: string[];
        };
        /** SeasonWindow */
        SeasonWindow: {
            /**
             * First
             * @description First season included.
             */
            first: number;
            /**
             * Last
             * @description Last season included.
             */
            last: number;
        };
        /** TeamRef */
        TeamRef: {
            /** Color */
            color: string;
            /** Franchise Id */
            franchise_id: string;
            /** Name */
            name: string;
            /** Team Season Id */
            team_season_id: string;
        };
        /** TeamScore */
        TeamScore: {
            /** Color */
            color: string;
            /** Franchise Id */
            franchise_id: string;
            /** Name */
            name: string;
            /**
             * Overs
             * @description Scoreboard overs, e.g. '19.4'.
             */
            overs: string | null;
            /** Runs */
            runs: number | null;
            /** Team Season Id */
            team_season_id: string;
            /** Wickets */
            wickets: number | null;
        };
        /** TeamStint */
        TeamStint: {
            /** Color */
            color: string;
            /** Franchise Id */
            franchise_id: string;
            /** Matches */
            matches: number;
            /** Name */
            name: string;
            /** Seasons */
            seasons: number[];
        };
        /** TeamTag */
        TeamTag: {
            /** Color */
            color: string;
            /** Franchise Id */
            franchise_id: string;
            /** Name */
            name: string;
        };
        /**
         * Timeline
         * @description Everything the client needs to replay a match ball by ball, in one payload.
         */
        Timeline: {
            /** Deliveries */
            deliveries: components["schemas"]["TimelineDelivery"][];
            /** Innings */
            innings: components["schemas"]["TimelineInnings"][];
            /** Players */
            players: {
                [key: string]: components["schemas"]["TimelinePlayer"];
            };
            /** @description Present when the first innings has score projections. */
            score_projection?: components["schemas"]["ScoreProjectionModel"] | null;
            /** Substitutions */
            substitutions: components["schemas"]["TimelineSubstitution"][];
            summary: components["schemas"]["MatchSummary"];
            /** Teams */
            teams: {
                [key: string]: components["schemas"]["TeamRef"];
            };
            /** @description Present when the match has model win probabilities. */
            win_probability?: components["schemas"]["WinProbabilityModel"] | null;
        };
        /** TimelineDelivery */
        TimelineDelivery: {
            /** Ball Label */
            ball_label: string | null;
            /** Batter Id */
            batter_id: string;
            /** Bowler Id */
            bowler_id: string;
            /** Byes */
            byes: number;
            /**
             * Factors
             * @description Percentage points each factor adds to the batting side's chance, relative to the model's average, in the order of Timeline.win_probability.factor_keys. Absent once the result is certain.
             */
            factors?: number[] | null;
            /** Innings No */
            innings_no: number;
            /** Is Four */
            is_four: boolean;
            /** Is Legal */
            is_legal: boolean;
            /** Is Six */
            is_six: boolean;
            /**
             * Legal Ball No
             * @description Legal balls bowled in the innings after this delivery.
             */
            legal_ball_no: number;
            /** Legbyes */
            legbyes: number;
            /** Noballs */
            noballs: number;
            /** Non Striker Id */
            non_striker_id: string;
            /**
             * Over No
             * @description 0-based over number.
             */
            over_no: number;
            /** Penalty */
            penalty: number;
            /**
             * Projection
             * @description First innings only: quantiles of the final total after this ball, at the levels in Timeline.score_projection.levels (model estimate).
             */
            projection?: number[] | null;
            /** Runs Batter */
            runs_batter: number;
            /** Runs Extras */
            runs_extras: number;
            /** Runs Total */
            runs_total: number;
            /** Seq No */
            seq_no: number;
            /**
             * Team Runs
             * @description Innings score after this delivery.
             */
            team_runs: number;
            /** Team Wickets */
            team_wickets: number;
            wicket: components["schemas"]["TimelineWicket"] | null;
            /** Wides */
            wides: number;
            /**
             * Wp
             * @description Win probability of the side batting first after this ball (model estimate).
             */
            wp?: number | null;
        };
        /** TimelineInnings */
        TimelineInnings: {
            /** Batting Team Id */
            batting_team_id: string;
            /** Bowling Team Id */
            bowling_team_id: string;
            /**
             * Factors Start
             * @description Explanation of wp_start (see Timeline.win_probability).
             */
            factors_start?: number[] | null;
            /** Innings No */
            innings_no: number;
            /** Is Super Over */
            is_super_over: boolean;
            /**
             * Max Balls
             * @description Legal balls available to the batting side.
             */
            max_balls: number;
            /**
             * Projection Start
             * @description First innings only: quantiles of the final total before the first ball.
             */
            projection_start?: number[] | null;
            /** Target Balls */
            target_balls: number | null;
            /** Target Runs */
            target_runs: number | null;
            /**
             * Wp Start
             * @description Win probability of the side batting first before this innings' first ball.
             */
            wp_start?: number | null;
        };
        /** TimelinePlayer */
        TimelinePlayer: {
            /** Full Name */
            full_name: string | null;
            /** Name */
            name: string;
        };
        /** TimelineSubstitution */
        TimelineSubstitution: {
            /** Innings No */
            innings_no: number;
            /** Player In Id */
            player_in_id: string | null;
            /** Player Out Id */
            player_out_id: string | null;
            /** Reason */
            reason: string | null;
            /** Seq No */
            seq_no: number;
            /** Team Season Id */
            team_season_id: string;
        };
        /** TimelineWicket */
        TimelineWicket: {
            /** Bowler Credited */
            bowler_credited: boolean;
            /** Fielder Ids */
            fielder_ids: string[];
            /** Is Dismissal */
            is_dismissal: boolean;
            /** Kind */
            kind: string;
            /** Player Out Id */
            player_out_id: string;
        };
        /** Toss */
        Toss: {
            /** Decision */
            decision: ("bat" | "field") | null;
            /** Winner Id */
            winner_id: string | null;
            /** Winner Name */
            winner_name: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VenueInfo */
        VenueInfo: {
            /** City */
            city: string;
            /** Country */
            country: string;
            /** Matches */
            matches: number;
            /** Name */
            name: string;
            /** Venue Id */
            venue_id: string;
        };
        /** VenueRef */
        VenueRef: {
            /** City */
            city: string;
            /** Name */
            name: string;
            /** Venue Id */
            venue_id: string;
        };
        /**
         * WinProbabilityModel
         * @description The model behind a timeline's win probabilities.
         */
        WinProbabilityModel: {
            /**
             * Base Innings1
             * @description Average first-innings estimate: the reference point for its factors.
             */
            base_innings1: number;
            /**
             * Base Innings2
             * @description Average chase estimate: the reference point for its factors.
             */
            base_innings2: number;
            /**
             * Factor Keys
             * @description Order of the values in each `factors` list.
             */
            factor_keys: string[];
            /** Trained From */
            trained_from: number;
            /** Trained Through */
            trained_through: number;
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_matches_api_v1_matches_get: {
        parameters: {
            query?: {
                season?: number | null;
                /** @description Franchise id, e.g. MI */
                team?: string | null;
                /** @description Venue id */
                venue?: string | null;
                /** @description Only playoffs (true) or league */
                playoffs?: boolean | null;
                sort?: "latest" | "oldest";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_match_api_v1_matches__match_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_timeline_api_v1_matches__match_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    list_players_api_v1_players_get: {
        parameters: {
            query?: {
                /** @description Name search */
                q?: string | null;
                role?: ("batter" | "bowler" | "all_rounder" | "keeper") | null;
                season?: number | null;
                /** @description Franchise id, e.g. MI */
                team?: string | null;
                sort?: "matches" | "runs" | "wickets" | "recent" | "name";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_player_api_v1_players__player_id__get: {
        parameters: {
            query?: {
                /** @description First season (inclusive). */
                from?: number | null;
                /** @description Last season (inclusive). */
                to?: number | null;
            };
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_splits_api_v1_players__player_id__splits_get: {
        parameters: {
            query?: {
                /** @description First season (inclusive). */
                from?: number | null;
                /** @description Last season (inclusive). */
                to?: number | null;
            };
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerSplits"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
