// Generated by `python -m criciq_api.featured`. Do not edit.
import type { Timeline } from "@/lib/api/types";

export const featuredTimelines: Record<number, () => Promise<Timeline>> = {
  1512773: () => import("./1512773.json").then((m) => m.default as unknown as Timeline),
  1415755: () => import("./1415755.json").then((m) => m.default as unknown as Timeline),
  1298179: () => import("./1298179.json").then((m) => m.default as unknown as Timeline),
  1273756: () => import("./1273756.json").then((m) => m.default as unknown as Timeline),
  951373: () => import("./951373.json").then((m) => m.default as unknown as Timeline),
  682965: () => import("./682965.json").then((m) => m.default as unknown as Timeline),
  533298: () => import("./533298.json").then((m) => m.default as unknown as Timeline),
  412703: () => import("./412703.json").then((m) => m.default as unknown as Timeline),
  356017: () => import("./356017.json").then((m) => m.default as unknown as Timeline),
  287879: () => import("./287879.json").then((m) => m.default as unknown as Timeline),
};
