/**
 * Analytics Lab notes. The data under `data/lab/` is generated by
 * `criciq-ml report` (the IPL's notes) and `criciq-ml lab-formats` (the notes
 * comparing formats) from the scored serving databases and bundled, so the
 * notes never wait for the API.
 */
import clutchData from "@/data/lab/clutch.json";
import homeData from "@/data/lab/home.json";
import momentumData from "@/data/lab/momentum.json";
import pressureData from "@/data/lab/pressure.json";
import rivalriesData from "@/data/lab/rivalries.json";
import tossData from "@/data/lab/toss.json";
import type { CompetitionId } from "@/lib/competitions";

export interface Estimate {
  value: number;
  low: number;
  high: number;
}

export interface MomentumNote {
  states: number;
  matches: number;
  momentum_sd: number;
  runs_per_10_points: Estimate;
  wickets_per_10_points: Estimate;
  result_per_10_points: Estimate;
  bands: {
    label: string;
    states: number;
    runs_next_12: number;
    runs_above_expected: Estimate;
    wickets_above_expected: Estimate;
    result_above_wp: Estimate;
  }[];
  data_version: string;
}

export interface PressureRow {
  band: string;
  from: number;
  to: number;
  innings_no: number;
  balls: number;
  share: number;
  strike_rate: number;
  expected_strike_rate: number;
  dot_pct: number;
  boundary_pct: number;
  dismissals_per_100: number;
  expected_dismissals_per_100: number;
  runs_above_expected_per_100: Estimate;
}

export interface PressureMoment {
  match_id: number;
  innings_no: number;
  seq_no: number;
  ball_label: string;
  season: number;
  date: string;
  teams: string;
  stage: string;
  result: string;
  leverage: number;
  situation: string;
  bowler: string;
  happened: string;
}

export interface PressureNote {
  balls: number;
  bands: { label: string; from: number; to: number }[];
  rows: PressureRow[];
  top_moments: PressureMoment[];
  swing_check: { balls: number; leverage: number; realised: Estimate }[];
  data_version: string;
}

export interface ClutchRole {
  players: number;
  min_high_balls: number;
  split_half_r: number | null;
  null_90: number | null;
  p_value: number | null;
  reliable_r: number;
  halves: { player_id: string; name: string; odd: number; even: number }[];
  most_exposed: {
    player_id: string;
    name: string;
    high_balls: number;
    clutch: number;
    low: number;
    high: number;
  }[];
}

export interface ClutchNote {
  high_pressure: number;
  roles: Record<"batting" | "bowling", ClutchRole>;
  data_version: string;
}

export interface RivalryGroup {
  label: string;
  meetings: number;
  win_pct: number | null;
  expected_pct: number | null;
  excess: Estimate | null;
}

export interface RivalriesNote {
  meetings: number;
  min_prior: number;
  form_prior: number;
  form_scan: { prior: number; log_loss: number }[];
  coin_flip_log_loss: number;
  favourite: RivalryGroup;
  calibration: RivalryGroup[];
  rivalry: RivalryGroup[];
  edge_per_10: Estimate | null;
  close_share: number;
  favourites: RivalryGroup[];
  persistence: {
    pairs: number;
    min_close: number;
    season_pairs: number;
    win_r: number | null;
    close_r: number | null;
    other_r: number | null;
    null_90: number | null;
    p_value: number | null;
  };
  data_version: string;
}

/** A share of results (a win 1, a draw or a tie without a winner a half), with its interval. */
export interface ShareRow {
  label: string;
  matches: number;
  won: number;
  drawn: number;
  lost: number;
  share: Estimate;
}

export type FormatKey = "test" | "odi" | "t20i" | "ipl" | "leagues";

export interface TossNote {
  formats: (ShareRow & { key: FormatKey })[];
  choices: (ShareRow & { key: FormatKey; decision: "bat" | "field"; chose: number })[];
  tests_by_region: ShareRow[];
  data_version: string;
}

export interface HomeNote {
  formats: (ShareRow & {
    key: FormatKey;
    neutral_share: number;
    balanced: { pairs: number; matches: number; share: Estimate } | null;
  })[];
  min_each_end: number;
  data_version: string;
}

export const MOMENTUM = momentumData as unknown as MomentumNote;
export const PRESSURE = pressureData as unknown as PressureNote;
export const CLUTCH = clutchData as unknown as ClutchNote;
export const RIVALRIES = rivalriesData as unknown as RivalriesNote;
export const TOSS = tossData as unknown as TossNote;
export const HOME = homeData as unknown as HomeNote;

export type LabSlug = "momentum" | "pressure" | "clutch" | "rivalries" | "toss" | "home";

export interface LabEntry {
  slug: LabSlug;
  title: string;
  question: string;
  answer: string;
  /** "ipl": a note about the IPL's balls; "formats": a note comparing every kind of cricket. */
  scope: "ipl" | "formats";
}

/** A share as points above an even split: 0.536 is "+3.6". */
export function pointsAboveEven(share: number): number {
  return 100 * (share - 0.5);
}

function tossRow(key: FormatKey) {
  return TOSS.formats.find((f) => f.key === key);
}

function homeRow(key: FormatKey) {
  return HOME.formats.find((f) => f.key === key);
}

function pct(share: number | undefined): string {
  return share === undefined ? "n/a" : `${(100 * share).toFixed(1)}%`;
}

function hottest() {
  return MOMENTUM.bands[MOMENTUM.bands.length - 1];
}

function veryHighChase(): PressureRow | undefined {
  return PRESSURE.rows.find((r) => r.band === "Very high" && r.innings_no === 2);
}

export const LAB: readonly LabEntry[] = [
  {
    slug: "momentum",
    title: "Is momentum real?",
    question:
      "Does a side that has just gained win probability keep scoring faster than expected, or win more often than the model says?",
    scope: "ipl",
    answer: `Barely. After a surge of 15+ points, sides score ${signed(hottest().runs_above_expected.value, 1)} runs above expectation in the next two overs and do not win any more often than the win probability already says.`,
  },
  {
    slug: "pressure",
    title: "What pressure does to batting",
    question:
      "Each ball gets a pressure index: how much it can move the match. How do batters change as it rises?",
    scope: "ipl",
    answer: veryHighChase()
      ? `They take risks. At very high pressure in a chase, batters score ${signed(veryHighChase()!.runs_above_expected_per_100.value, 1)} runs per 100 balls above expectation and get out more often.`
      : "The index ranks every ball by how much it can move the match.",
  },
  {
    slug: "clutch",
    title: "Is clutch a skill?",
    question:
      "Some players seem to rise to the big moments. Does a player's record under pressure in some seasons predict it in others?",
    scope: "ipl",
    answer: `Not reliably. A batter's record under pressure in odd seasons predicts it in even seasons with a correlation of ${CLUTCH.roles.batting.split_half_r?.toFixed(2) ?? "n/a"}, far below the ${CLUTCH.roles.batting.reliable_r} a usable rating would need; for bowlers it is ${CLUTCH.roles.bowling.split_half_r?.toFixed(2) ?? "n/a"}.`,
  },
  {
    slug: "rivalries",
    title: "Do rivalries and close finishes repeat?",
    question:
      "Some sides seem to have a hold over others, and some seem to win every tight finish. Does either predict the next match?",
    scope: "ipl",
    answer: `No. Sides that had won ${RIVALRIES.rivalry[0]?.label.replace("Won ", "") ?? "60%+"} of earlier meetings won ${RIVALRIES.rivalry[0]?.win_pct ?? "n/a"}% of the next, against ${RIVALRIES.rivalry[0]?.expected_pct ?? "n/a"}% expected from form, and close-finish records do not carry over. Even form says little: the side in better form wins ${RIVALRIES.favourite.win_pct ?? "n/a"}% of the time.`,
  },
  {
    slug: "toss",
    title: "Does the toss matter more in Tests?",
    question:
      "The toss is a coin flip, so the toss winner's results show what winning it is worth. Is it worth more in a five-day Test than in one-day cricket?",
    scope: "formats",
    answer: `Yes, a little: toss winners took ${pct(tossRow("test")?.share.value)} of the results in Tests (a draw counts half), and ${pct(tossRow("leagues")?.share.value)} in the BBL, CPL, PSL and SA20, where most of them bowl first. In ODIs (${pct(tossRow("odi")?.share.value)}), T20Is (${pct(tossRow("t20i")?.share.value)}) and the IPL it makes no measurable difference.`,
  },
  {
    slug: "home",
    title: "Home advantage by format",
    question:
      "How much better do sides do at home in Tests, ODIs and T20 cricket, once strong sides hosting more often is taken out?",
    scope: "formats",
    answer: `It grows with the length of the match: home sides took ${pct(homeRow("test")?.balanced?.share.value)} of results in Tests, ${pct(homeRow("odi")?.balanced?.share.value)} in ODIs and ${pct(homeRow("t20i")?.balanced?.share.value)} in T20Is, between the same pairs of sides; in the IPL it is ${pct(homeRow("ipl")?.balanced?.share.value)}, no advantage at all.`,
  },
];

export function labEntry(slug: string): LabEntry | undefined {
  return LAB.find((e) => e.slug === slug);
}

/** The notes a competition's Analytics Lab shows: the IPL's own, and those comparing formats. */
export function labNotes(competition: CompetitionId): LabEntry[] {
  return LAB.filter((e) => e.scope === "formats" || competition === "ipl");
}

export function signed(value: number, digits = 1): string {
  const text = Math.abs(value).toFixed(digits);
  if (Number(text) === 0) return (0).toFixed(digits);
  return `${value > 0 ? "+" : "−"}${text}`;
}
