/**
 * Analytics Lab notes. The data under `data/lab/` is generated by
 * `criciq-ml report` from the scored serving database and bundled, so the
 * notes never wait for the API.
 */
import clutchData from "@/data/lab/clutch.json";
import momentumData from "@/data/lab/momentum.json";
import pressureData from "@/data/lab/pressure.json";

export interface Estimate {
  value: number;
  low: number;
  high: number;
}

export interface MomentumNote {
  states: number;
  matches: number;
  momentum_sd: number;
  runs_per_10_points: Estimate;
  wickets_per_10_points: Estimate;
  result_per_10_points: Estimate;
  bands: {
    label: string;
    states: number;
    runs_next_12: number;
    runs_above_expected: Estimate;
    wickets_above_expected: Estimate;
    result_above_wp: Estimate;
  }[];
  data_version: string;
}

export interface PressureRow {
  band: string;
  from: number;
  to: number;
  innings_no: number;
  balls: number;
  share: number;
  strike_rate: number;
  expected_strike_rate: number;
  dot_pct: number;
  boundary_pct: number;
  dismissals_per_100: number;
  expected_dismissals_per_100: number;
  runs_above_expected_per_100: Estimate;
}

export interface PressureMoment {
  match_id: number;
  innings_no: number;
  seq_no: number;
  ball_label: string;
  season: number;
  date: string;
  teams: string;
  stage: string;
  result: string;
  leverage: number;
  situation: string;
  bowler: string;
  happened: string;
}

export interface PressureNote {
  balls: number;
  bands: { label: string; from: number; to: number }[];
  rows: PressureRow[];
  top_moments: PressureMoment[];
  swing_check: { balls: number; leverage: number; realised: Estimate }[];
  data_version: string;
}

export interface ClutchRole {
  players: number;
  min_high_balls: number;
  split_half_r: number | null;
  null_90: number | null;
  p_value: number | null;
  reliable_r: number;
  halves: { player_id: string; name: string; odd: number; even: number }[];
  most_exposed: {
    player_id: string;
    name: string;
    high_balls: number;
    clutch: number;
    low: number;
    high: number;
  }[];
}

export interface ClutchNote {
  high_pressure: number;
  roles: Record<"batting" | "bowling", ClutchRole>;
  data_version: string;
}

export const MOMENTUM = momentumData as unknown as MomentumNote;
export const PRESSURE = pressureData as unknown as PressureNote;
export const CLUTCH = clutchData as unknown as ClutchNote;

export type LabSlug = "momentum" | "pressure" | "clutch";

export interface LabEntry {
  slug: LabSlug;
  title: string;
  question: string;
  answer: string;
}

function hottest() {
  return MOMENTUM.bands[MOMENTUM.bands.length - 1];
}

function veryHighChase(): PressureRow | undefined {
  return PRESSURE.rows.find((r) => r.band === "Very high" && r.innings_no === 2);
}

export const LAB: readonly LabEntry[] = [
  {
    slug: "momentum",
    title: "Is momentum real?",
    question:
      "Does a side that has just gained win probability keep scoring faster than expected, or win more often than the model says?",
    answer: `Barely. After a surge of 15+ points, sides score ${signed(hottest().runs_above_expected.value, 1)} runs above expectation in the next two overs and do not win any more often than the win probability already says.`,
  },
  {
    slug: "pressure",
    title: "What pressure does to batting",
    question:
      "Each ball gets a pressure index: how much it can move the match. How do batters change as it rises?",
    answer: veryHighChase()
      ? `They take risks. At very high pressure in a chase, batters score ${signed(veryHighChase()!.runs_above_expected_per_100.value, 1)} runs per 100 balls above expectation and get out more often.`
      : "The index ranks every ball by how much it can move the match.",
  },
  {
    slug: "clutch",
    title: "Is clutch a skill?",
    question:
      "Some players seem to rise to the big moments. Does a player's record under pressure in some seasons predict it in others?",
    answer: `Not reliably. A batter's record under pressure in odd seasons predicts it in even seasons with a correlation of ${CLUTCH.roles.batting.split_half_r?.toFixed(2) ?? "n/a"}, far below the ${CLUTCH.roles.batting.reliable_r} a usable rating would need; for bowlers it is ${CLUTCH.roles.bowling.split_half_r?.toFixed(2) ?? "n/a"}.`,
  },
];

export function labEntry(slug: string): LabEntry | undefined {
  return LAB.find((e) => e.slug === slug);
}

export function signed(value: number, digits = 1): string {
  const text = Math.abs(value).toFixed(digits);
  if (Number(text) === 0) return (0).toFixed(digits);
  return `${value > 0 ? "+" : "−"}${text}`;
}
