/**
 * Model Insights data. `data/models/win-probability.json` is generated by
 * `criciq-ml report` from the model registry (the same numbers as the model
 * card), and bundled so the page never depends on the API being awake. Every
 * model group has models of its own, trained on its own competitions only
 * (ADR-0013): the files in `data/models/` are the IPL's, `data/models/leagues/`
 * the BBL's, CPL's, PSL's and SA20's, `data/models/t20i/` the T20Is' and
 * `data/models/odi/` the ODIs'. `data/models/t20/` keeps the pooled T20 version
 * of V2-3, shown only as the trade-off it was replaced with.
 */
import ballOutcomeData from "@/data/models/ball-outcome.json";
import leaguesBallOutcomeData from "@/data/models/leagues/ball-outcome.json";
import leaguesRatingsData from "@/data/models/leagues/ratings.json";
import leaguesProjectionData from "@/data/models/leagues/score-projection.json";
import leaguesSimulatorData from "@/data/models/leagues/simulator.json";
import leaguesWinProbabilityData from "@/data/models/leagues/win-probability.json";
import odiBallOutcomeData from "@/data/models/odi/ball-outcome.json";
import odiProjectionData from "@/data/models/odi/score-projection.json";
import odiRatingsData from "@/data/models/odi/ratings.json";
import odiSimulatorData from "@/data/models/odi/simulator.json";
import odiWinProbabilityData from "@/data/models/odi/win-probability.json";
import ratingsData from "@/data/models/ratings.json";
import projectionData from "@/data/models/score-projection.json";
import simulatorData from "@/data/models/simulator.json";
import t20WinProbabilityData from "@/data/models/t20/win-probability.json";
import t20iBallOutcomeData from "@/data/models/t20i/ball-outcome.json";
import t20iRatingsData from "@/data/models/t20i/ratings.json";
import t20iProjectionData from "@/data/models/t20i/score-projection.json";
import t20iSimulatorData from "@/data/models/t20i/simulator.json";
import t20iWinProbabilityData from "@/data/models/t20i/win-probability.json";
import data from "@/data/models/win-probability.json";
import type { CompetitionId } from "@/lib/competitions";

export interface Metrics {
  rows: number;
  log_loss: number;
  brier: number;
  ece: number;
  auc: number | null;
}

export interface Bootstrap {
  improvement: number;
  ci_low: number;
  ci_high: number;
  matches: number;
}

export interface ReliabilityBin {
  lower: number;
  upper: number;
  predicted: number;
  observed: number;
  count: number;
}

export interface PhaseRow {
  innings_no: number;
  phase: "powerplay" | "middle" | "death";
  rows: number;
  model_log_loss: number;
  baseline_log_loss: number;
  model_brier: number;
  baseline_brier: number;
}

export interface BacktestRow {
  season: number;
  matches: number;
  model_log_loss: number;
  baseline_log_loss: number;
  model_brier: number;
  baseline_brier: number;
  model_ece: number;
}

export interface SelectionRow {
  innings_no: number;
  variant: string;
  label: string;
  log_loss: number;
  brier: number;
  seasons: number[];
}

export interface Swing {
  match_id: number;
  innings_no: number;
  seq_no: number;
  ball_label: string;
  season: number;
  date: string;
  stage: string;
  teams: string;
  result: string;
  description: string;
  team: string;
  swing: number;
  wp_after: number;
}

export interface ModelInsights {
  name: string;
  version: string;
  data_version: string;
  trained_on: { seasons: number[]; matches: number; rows: number };
  splits: { train: number[]; validation: number[]; test: number[]; served_through: number };
  features: Record<string, { key: string; label: string }[]>;
  calibration: {
    method: "none" | "platt";
    selection: { method: string; log_loss: number; brier: number }[];
  };
  test: {
    matches: number;
    model: Metrics;
    alternatives: (Metrics & { key: string })[];
    baseline: Metrics;
    state_only: Metrics;
    vs_baseline: Bootstrap;
    vs_state_only: Bootstrap;
    reliability: ReliabilityBin[];
    baseline_reliability: ReliabilityBin[];
    by_phase: PhaseRow[];
  };
  importance: { group: string; label: string; share: number }[];
  feature_selection: SelectionRow[];
  backtest: BacktestRow[];
  swings: Swing[];
}

export const WIN_PROBABILITY = data as unknown as ModelInsights;

/** Chart roles: the model in the brand colour, the baseline in neutral grey. */
export const SERIES = {
  model: { color: "var(--chart-3)", label: "CricIQ model" },
  baseline: { color: "var(--chart-5)", label: "Logistic baseline" },
} as const;

export function seasonSpan(seasons: number[]): string {
  const sorted = [...seasons].sort((a, b) => a - b);
  return sorted.length > 1 ? `${sorted[0]}–${sorted[sorted.length - 1]}` : String(sorted[0]);
}

// ---------------------------------------------------------------- score projection

export interface ProjectionMetrics {
  rows: number;
  innings: number;
  coverage80: number;
  width80: number;
  mae: number;
  bias: number;
  pinball: number;
  threshold_brier: number;
  level_calibration: { level: number; observed: number }[];
}

export interface ProjectionBacktestRow {
  season: number;
  innings: number;
  coverage80: number;
  mae: number;
  bias: number;
  par_mae: number;
  mean_total: number;
}

export interface ScoreProjectionInsights {
  name: string;
  version: string;
  data_version: string;
  trained_on: { seasons: number[]; innings: number; rows: number };
  calibrated_on: number[];
  levels: number[];
  splits: {
    tune_train_through: number;
    tune_valid: number[];
    calibrate: number[];
    test: number[];
    served_through: number;
  };
  features: { key: string; label: string }[];
  test: {
    model: ProjectionMetrics;
    uncalibrated: ProjectionMetrics;
    par_baseline: ProjectionMetrics;
    run_rate: { rows: number; mae: number; bias: number };
    by_phase: {
      phase: "powerplay" | "middle" | "death";
      rows: number;
      model_mae: number;
      par_mae: number;
      run_rate_mae: number;
      model_coverage80: number;
      model_width80: number;
    }[];
    thresholds: number[];
  };
  feature_selection: {
    variant: string;
    label: string;
    pinball: number;
    mae: number;
    seasons: number[];
  }[];
  backtest: ProjectionBacktestRow[];
}

export const SCORE_PROJECTION = projectionData as unknown as ScoreProjectionInsights;

// ---------------------------------------------------------------- ball outcome

export interface BallMetrics {
  balls: number;
  log_loss: number;
  brier: number;
  expected_runs: number;
  actual_runs: number;
}

export interface OutcomeCalibration {
  predicted: number;
  observed: number;
  ece: number;
  bins: { predicted: number; observed: number; count: number }[];
}

export interface HistoryCheck {
  balls: number;
  model: number;
  shrunk: number;
  raw: number;
}

export interface BallOutcomeInsights {
  name: string;
  version: string;
  data_version: string;
  trained_on: { seasons: number[]; balls: number };
  kappa: number;
  player_scale: number;
  splits: {
    tune_train_through: number;
    tune_valid: number[];
    test: number[];
    served_through: number;
  };
  outcomes: { key: string; label: string }[];
  feature_selection: { variant: string; label: string; log_loss: number }[];
  candidate_min_gain: number;
  phase_players: boolean;
  test: {
    model: BallMetrics;
    situation_only: BallMetrics;
    baseline: BallMetrics;
    by_phase: {
      phase: "powerplay" | "middle" | "death";
      balls: number;
      model_log_loss: number;
      baseline_log_loss: number;
    }[];
    calibration: Record<string, OutcomeCalibration>;
    runs_calibration: { predicted: number; observed: number; count: number }[];
  };
  matchups: {
    kappa: number;
    served_kappa: number;
    pairs_in_history: number;
    test_pairs: number;
    all: HistoryCheck;
    by_history: (HistoryCheck & { history: string })[];
  };
  backtest: { season: number; balls: number; model_log_loss: number; baseline_log_loss: number }[];
}

export const BALL_OUTCOME = ballOutcomeData as unknown as BallOutcomeInsights;

// ---------------------------------------------------------------- ratings

export interface RatingComponentEvaluation {
  key: string;
  role: "batting" | "bowling";
  label: string;
  description: string;
  unit: string;
  unit_label: string;
  exposure: "balls" | "innings";
  k: number;
  k_validation: number;
  sigma2: number;
  weight_at: Record<string, number>;
  year_to_year: { r: number | null; pairs: number };
  split_half: { r: number | null; players: number };
  next_season: {
    pairs: number;
    mse?: { par: number; raw: number; shrunk: number };
    skill_vs_par?: number;
    skill_vs_raw?: number;
  };
  stability: "high" | "moderate" | "low";
}

export interface StyleRetrieval {
  players: number;
  candidates_median: number;
  top1: number;
  top5: number;
  chance_top1: number;
  chance_top5: number;
  median_rank: number;
  features: { key: string; label: string }[];
}

export interface RatingsInsights {
  name: string;
  version: string;
  data_version: string;
  trained_on: { seasons: number[] };
  splits: { test_from: number };
  stability: Record<"high" | "moderate", number>;
  season_factor: number;
  thresholds: {
    min_balls: number;
    min_subset_balls: number;
    min_innings: number;
    min_rated_balls: number;
    min_profile_balls: number;
    style_min_balls: number;
  };
  components: RatingComponentEvaluation[];
  similarity: Record<"batting" | "bowling", StyleRetrieval>;
}

export const RATINGS = ratingsData as unknown as RatingsInsights;

export interface Scores {
  brier: number;
  log_loss: number;
}

export interface Gain {
  value: number;
  low: number;
  high: number;
}

export interface CalibrationRow {
  matches: number;
  predicted: number;
  observed: number;
}

export interface SimulatorInsights {
  version: string;
  data_version: string;
  valid: number[];
  test: number[];
  settings: {
    conditions_sd: number;
    history_seasons: number;
    usage_strength: number;
    /** Matches the recent scoring level is followed over (absent: not followed). */
    level_window?: number;
  };
  tuning: {
    conditions_sd: number;
    crps: number;
    coverage_80: number;
    pit_chi2?: number;
    brier: number;
  }[];
  matches: number;
  simulations_per_match: number;
  forced_overs: number;
  win: {
    simulator: Scores;
    coin_flip: Scores;
    bat_first_rate: Scores & { rate: number };
    form: Scores;
    gain_vs_coin_flip: Gain;
    calibration: CalibrationRow[];
    mean_predicted: number;
    observed: number;
  };
  chase: {
    matches: number;
    simulator: Scores;
    chase_rate: Scores & { rate: number };
    gain_vs_chase_rate: Gain;
    calibration: CalibrationRow[];
    mean_predicted: number;
    observed: number;
  };
  first_innings: {
    matches: number;
    pit_counts: number[];
    pit_chi2: number;
    pit_chi2_critical: number;
    crps: number;
    coverage_80: number;
    coverage_50: number;
    actual_mean: number;
    simulated_mean: number;
    actual_wickets: number;
    simulated_wickets: number;
  };
  ties: { simulated: number };
  timing: { simulations: number; seconds: number };
}

export const SIMULATOR = simulatorData as unknown as SimulatorInsights;

// ---------------------------------------------------------------- overview

/** Share of balls on which the side the model favoured went on to win, from reliability bins. */
export function favouriteAccuracy(bins: ReliabilityBin[]): number {
  const total = bins.reduce((sum, b) => sum + b.count, 0);
  const right = bins.reduce(
    (sum, b) => sum + b.count * (b.lower >= 0.5 ? b.observed : 1 - b.observed),
    0,
  );
  return total ? right / total : 0;
}

export type SplitRole = "train" | "validation" | "test";

export interface ModelSplit {
  key: string;
  label: string;
  roles: { role: SplitRole; from: number; to: number }[];
}

export const FIRST_SEASON = 2008;

/** A season list from the registry: two entries are an inclusive range. */
function span(seasons: number[]): { from: number; to: number } {
  return { from: Math.min(...seasons), to: Math.max(...seasons) };
}

/** Which seasons each model learned from, was tuned on and was tested on. */
export function modelSplits(): ModelSplit[] {
  const wp = WIN_PROBABILITY.splits;
  const sp = SCORE_PROJECTION.splits;
  const bo = BALL_OUTCOME.splits;
  const tested = span(wp.test);
  return [
    {
      key: "win-probability",
      label: "Win probability",
      roles: [
        { role: "train", ...span(wp.train) },
        { role: "validation", ...span(wp.validation) },
        { role: "test", ...tested },
      ],
    },
    {
      key: "score-projection",
      label: "Score projection",
      roles: [
        { role: "train", from: FIRST_SEASON, to: sp.tune_train_through },
        { role: "validation", from: span(sp.tune_valid).from, to: span(sp.calibrate).to },
        { role: "test", ...span(sp.test) },
      ],
    },
    {
      key: "ball-outcome",
      label: "Ball outcome",
      roles: [
        { role: "train", from: FIRST_SEASON, to: bo.tune_train_through },
        { role: "validation", ...span(bo.tune_valid) },
        { role: "test", ...span(bo.test) },
      ],
    },
    {
      key: "ratings",
      label: "Ratings",
      roles: [
        { role: "train", from: FIRST_SEASON, to: RATINGS.splits.test_from - 1 },
        { role: "test", from: RATINGS.splits.test_from, to: wp.served_through },
      ],
    },
    {
      key: "simulator",
      label: "Simulator",
      roles: [
        { role: "train", from: FIRST_SEASON, to: span(SIMULATOR.valid).from - 1 },
        { role: "validation", ...span(SIMULATOR.valid) },
        { role: "test", ...span(SIMULATOR.test) },
      ],
    },
  ];
}

/** The role a season plays for a model, or null when it is not used. */
export function roleIn(split: ModelSplit, season: number): SplitRole | null {
  return split.roles.find((r) => season >= r.from && season <= r.to)?.role ?? null;
}

// ---------------------------------------------------------------- per competition

/** A model's results on one competition's test matches (a group of several competitions). */
export interface CompetitionResults<M> {
  competition: string;
  matches?: number;
  model: M;
  baseline?: M;
  par_baseline?: M;
  vs_baseline?: Bootstrap;
}

/** The model groups (config/model_groups.yaml): each trains on its own competitions only. */
export type ModelGroupId = "ipl" | "leagues" | "t20i" | "odi";

const GROUP_OF: Record<CompetitionId, ModelGroupId> = {
  ipl: "ipl",
  bbl: "leagues",
  cpl: "leagues",
  psl: "leagues",
  sa20: "leagues",
  t20i: "t20i",
  odi: "odi",
};

type Several<T> = T & {
  test: T extends { test: infer U } ? U & { by_competition: CompetitionResults<unknown>[] } : never;
};

/** One competition's models with a simulator backtest of its own (T20Is, ODIs). */
type SingleSimulator = SimulatorInsights & { gate: string[]; served: boolean };
/** A group's simulator: each competition's backtest, and where it passed and serves. */
interface SeveralSimulator {
  version: string;
  served: string[];
  competitions: Record<string, SimulatorInsights & { gate: string[] }>;
}

/** The BBL, CPL, PSL and SA20: one set of models trained on the four leagues only. */
const LEAGUES = {
  winProbability: leaguesWinProbabilityData as unknown as Several<ModelInsights> & {
    swings_by_competition: Record<string, Swing[]>;
  },
  scoreProjection: leaguesProjectionData as unknown as Several<ScoreProjectionInsights>,
  ballOutcome: leaguesBallOutcomeData as unknown as Several<BallOutcomeInsights>,
  ratings: leaguesRatingsData as unknown as { scopes: Record<string, RatingsInsights> },
  simulator: leaguesSimulatorData as unknown as SeveralSimulator,
};

/** Men's T20Is and ODIs: each its own models, trained on its matches alone. */
const SINGLE = {
  t20i: {
    winProbability: t20iWinProbabilityData as unknown as ModelInsights,
    scoreProjection: t20iProjectionData as unknown as ScoreProjectionInsights,
    ballOutcome: t20iBallOutcomeData as unknown as BallOutcomeInsights,
    ratings: t20iRatingsData as unknown as RatingsInsights,
    simulator: t20iSimulatorData as unknown as SingleSimulator,
  },
  odi: {
    winProbability: odiWinProbabilityData as unknown as ModelInsights,
    scoreProjection: odiProjectionData as unknown as ScoreProjectionInsights,
    ballOutcome: odiBallOutcomeData as unknown as BallOutcomeInsights,
    ratings: odiRatingsData as unknown as RatingsInsights,
    simulator: odiSimulatorData as unknown as SingleSimulator,
  },
};

/** The pooled T20 win probability of V2-3 (every T20 competition at once), which the
 * leagues' and T20Is' own models replaced: its results on each competition's test matches. */
const POOLED_WIN_PROBABILITY = t20WinProbabilityData as unknown as Several<ModelInsights>;

/** The models serving one competition, as Model Insights shows them. */
export interface ModelSet {
  competition: CompetitionId;
  /** The model group whose models serve it, trained on the group's competitions only. */
  group: ModelGroupId;
  /** The competitions the group's models were trained on. */
  trainedOn: string[];
  winProbability: ModelInsights;
  scoreProjection: ScoreProjectionInsights;
  ballOutcome: BallOutcomeInsights;
  ratings: RatingsInsights;
  /** Null where no simulator version has passed its backtest gate. */
  simulator: SimulatorInsights | null;
  /** The latest simulator backtest of this competition, served or not, with the gate's reasons. */
  simulatorBacktest: (SimulatorInsights & { gate: string[] }) | null;
  swings: Swing[];
  /** In a group of several competitions, the models' results on this one's own test matches. */
  results: {
    winProbability: CompetitionResults<Metrics> | null;
    scoreProjection: CompetitionResults<ProjectionMetrics> | null;
    ballOutcome: CompetitionResults<BallMetrics> | null;
  };
  /** The pooled T20 win probability's result here, before the group had its own (V2-3). */
  pooledWinProbability: CompetitionResults<Metrics> | null;
}

function resultsFor<M>(
  rows: CompetitionResults<unknown>[],
  id: string,
): CompetitionResults<M> | null {
  return (rows.find((r) => r.competition === id) as CompetitionResults<M> | undefined) ?? null;
}

const NO_RESULTS = { winProbability: null, scoreProjection: null, ballOutcome: null };

export function modelsFor(competition: CompetitionId): ModelSet {
  const group = GROUP_OF[competition];
  const id = competition.toUpperCase();
  const pooled = resultsFor<Metrics>(POOLED_WIN_PROBABILITY.test.by_competition, id);
  if (group === "ipl") {
    return {
      competition,
      group,
      trainedOn: ["IPL"],
      winProbability: WIN_PROBABILITY,
      scoreProjection: SCORE_PROJECTION,
      ballOutcome: BALL_OUTCOME,
      ratings: RATINGS,
      simulator: SIMULATOR,
      simulatorBacktest: { ...SIMULATOR, gate: [] },
      swings: WIN_PROBABILITY.swings,
      results: NO_RESULTS,
      pooledWinProbability: null,
    };
  }
  if (group === "leagues") {
    const wp = LEAGUES.winProbability;
    return {
      competition,
      group,
      trainedOn: (wp.trained_on as unknown as { competitions: string[] }).competitions,
      winProbability: wp,
      scoreProjection: LEAGUES.scoreProjection,
      ballOutcome: LEAGUES.ballOutcome,
      ratings: LEAGUES.ratings.scopes[id],
      simulator: LEAGUES.simulator.served.includes(id) ? LEAGUES.simulator.competitions[id] : null,
      simulatorBacktest: LEAGUES.simulator.competitions[id] ?? null,
      swings: wp.swings_by_competition[id] ?? [],
      results: {
        winProbability: resultsFor(wp.test.by_competition, id),
        scoreProjection: resultsFor(LEAGUES.scoreProjection.test.by_competition, id),
        ballOutcome: resultsFor(LEAGUES.ballOutcome.test.by_competition, id),
      },
      pooledWinProbability: pooled,
    };
  }
  const own = SINGLE[group];
  return {
    competition,
    group,
    trainedOn: [id],
    winProbability: own.winProbability,
    scoreProjection: own.scoreProjection,
    ballOutcome: own.ballOutcome,
    ratings: own.ratings,
    simulator: own.simulator.served ? own.simulator : null,
    simulatorBacktest: own.simulator,
    swings: own.winProbability.swings,
    results: NO_RESULTS,
    pooledWinProbability: pooled,
  };
}
