/**
 * Model Insights data. `data/models/win-probability.json` is generated by
 * `criciq-ml report` from the model registry (the same numbers as the model
 * card), and bundled so the page never depends on the API being awake.
 */
import data from "@/data/models/win-probability.json";

export interface Metrics {
  rows: number;
  log_loss: number;
  brier: number;
  ece: number;
  auc: number | null;
}

export interface Bootstrap {
  improvement: number;
  ci_low: number;
  ci_high: number;
  matches: number;
}

export interface ReliabilityBin {
  lower: number;
  upper: number;
  predicted: number;
  observed: number;
  count: number;
}

export interface PhaseRow {
  innings_no: number;
  phase: "powerplay" | "middle" | "death";
  rows: number;
  model_log_loss: number;
  baseline_log_loss: number;
  model_brier: number;
  baseline_brier: number;
}

export interface BacktestRow {
  season: number;
  matches: number;
  model_log_loss: number;
  baseline_log_loss: number;
  model_brier: number;
  baseline_brier: number;
  model_ece: number;
}

export interface SelectionRow {
  innings_no: number;
  variant: string;
  label: string;
  log_loss: number;
  brier: number;
  seasons: number[];
}

export interface Swing {
  match_id: number;
  innings_no: number;
  seq_no: number;
  ball_label: string;
  season: number;
  date: string;
  stage: string;
  teams: string;
  result: string;
  description: string;
  team: string;
  swing: number;
  wp_after: number;
}

export interface ModelInsights {
  name: string;
  version: string;
  data_version: string;
  trained_on: { seasons: number[]; matches: number; rows: number };
  splits: { train: number[]; validation: number[]; test: number[]; served_through: number };
  features: Record<string, { key: string; label: string }[]>;
  calibration: {
    method: "none" | "platt";
    selection: { method: string; log_loss: number; brier: number }[];
  };
  test: {
    matches: number;
    model: Metrics;
    alternatives: (Metrics & { key: string })[];
    baseline: Metrics;
    state_only: Metrics;
    vs_baseline: Bootstrap;
    vs_state_only: Bootstrap;
    reliability: ReliabilityBin[];
    baseline_reliability: ReliabilityBin[];
    by_phase: PhaseRow[];
  };
  importance: { group: string; label: string; share: number }[];
  feature_selection: SelectionRow[];
  backtest: BacktestRow[];
  swings: Swing[];
}

export const WIN_PROBABILITY = data as unknown as ModelInsights;

/** Chart roles: the model in the brand colour, the baseline in neutral grey. */
export const SERIES = {
  model: { color: "var(--chart-3)", label: "CricIQ model" },
  baseline: { color: "var(--chart-5)", label: "Logistic baseline" },
} as const;

export function seasonSpan(seasons: number[]): string {
  const sorted = [...seasons].sort((a, b) => a - b);
  return sorted.length > 1 ? `${sorted[0]}–${sorted[sorted.length - 1]}` : String(sorted[0]);
}
