/**
 * Model Insights data. `data/models/win-probability.json` is generated by
 * `criciq-ml report` from the model registry (the same numbers as the model
 * card), and bundled so the page never depends on the API being awake.
 */
import ballOutcomeData from "@/data/models/ball-outcome.json";
import projectionData from "@/data/models/score-projection.json";
import data from "@/data/models/win-probability.json";

export interface Metrics {
  rows: number;
  log_loss: number;
  brier: number;
  ece: number;
  auc: number | null;
}

export interface Bootstrap {
  improvement: number;
  ci_low: number;
  ci_high: number;
  matches: number;
}

export interface ReliabilityBin {
  lower: number;
  upper: number;
  predicted: number;
  observed: number;
  count: number;
}

export interface PhaseRow {
  innings_no: number;
  phase: "powerplay" | "middle" | "death";
  rows: number;
  model_log_loss: number;
  baseline_log_loss: number;
  model_brier: number;
  baseline_brier: number;
}

export interface BacktestRow {
  season: number;
  matches: number;
  model_log_loss: number;
  baseline_log_loss: number;
  model_brier: number;
  baseline_brier: number;
  model_ece: number;
}

export interface SelectionRow {
  innings_no: number;
  variant: string;
  label: string;
  log_loss: number;
  brier: number;
  seasons: number[];
}

export interface Swing {
  match_id: number;
  innings_no: number;
  seq_no: number;
  ball_label: string;
  season: number;
  date: string;
  stage: string;
  teams: string;
  result: string;
  description: string;
  team: string;
  swing: number;
  wp_after: number;
}

export interface ModelInsights {
  name: string;
  version: string;
  data_version: string;
  trained_on: { seasons: number[]; matches: number; rows: number };
  splits: { train: number[]; validation: number[]; test: number[]; served_through: number };
  features: Record<string, { key: string; label: string }[]>;
  calibration: {
    method: "none" | "platt";
    selection: { method: string; log_loss: number; brier: number }[];
  };
  test: {
    matches: number;
    model: Metrics;
    alternatives: (Metrics & { key: string })[];
    baseline: Metrics;
    state_only: Metrics;
    vs_baseline: Bootstrap;
    vs_state_only: Bootstrap;
    reliability: ReliabilityBin[];
    baseline_reliability: ReliabilityBin[];
    by_phase: PhaseRow[];
  };
  importance: { group: string; label: string; share: number }[];
  feature_selection: SelectionRow[];
  backtest: BacktestRow[];
  swings: Swing[];
}

export const WIN_PROBABILITY = data as unknown as ModelInsights;

/** Chart roles: the model in the brand colour, the baseline in neutral grey. */
export const SERIES = {
  model: { color: "var(--chart-3)", label: "CricIQ model" },
  baseline: { color: "var(--chart-5)", label: "Logistic baseline" },
} as const;

export function seasonSpan(seasons: number[]): string {
  const sorted = [...seasons].sort((a, b) => a - b);
  return sorted.length > 1 ? `${sorted[0]}–${sorted[sorted.length - 1]}` : String(sorted[0]);
}

// ---------------------------------------------------------------- score projection

export interface ProjectionMetrics {
  rows: number;
  innings: number;
  coverage80: number;
  width80: number;
  mae: number;
  bias: number;
  pinball: number;
  threshold_brier: number;
  level_calibration: { level: number; observed: number }[];
}

export interface ProjectionBacktestRow {
  season: number;
  innings: number;
  coverage80: number;
  mae: number;
  bias: number;
  par_mae: number;
  mean_total: number;
}

export interface ScoreProjectionInsights {
  name: string;
  version: string;
  trained_on: { seasons: number[]; innings: number; rows: number };
  calibrated_on: number[];
  levels: number[];
  splits: {
    tune_train_through: number;
    tune_valid: number[];
    calibrate: number[];
    test: number[];
    served_through: number;
  };
  features: { key: string; label: string }[];
  test: {
    model: ProjectionMetrics;
    uncalibrated: ProjectionMetrics;
    par_baseline: ProjectionMetrics;
    run_rate: { rows: number; mae: number; bias: number };
    by_phase: {
      phase: "powerplay" | "middle" | "death";
      rows: number;
      model_mae: number;
      par_mae: number;
      run_rate_mae: number;
      model_coverage80: number;
      model_width80: number;
    }[];
    thresholds: number[];
  };
  feature_selection: {
    variant: string;
    label: string;
    pinball: number;
    mae: number;
    seasons: number[];
  }[];
  backtest: ProjectionBacktestRow[];
}

export const SCORE_PROJECTION = projectionData as unknown as ScoreProjectionInsights;

// ---------------------------------------------------------------- ball outcome

export interface BallMetrics {
  balls: number;
  log_loss: number;
  brier: number;
  expected_runs: number;
  actual_runs: number;
}

export interface OutcomeCalibration {
  predicted: number;
  observed: number;
  ece: number;
  bins: { predicted: number; observed: number; count: number }[];
}

export interface HistoryCheck {
  balls: number;
  model: number;
  shrunk: number;
  raw: number;
}

export interface BallOutcomeInsights {
  name: string;
  version: string;
  data_version: string;
  trained_on: { seasons: number[]; balls: number };
  kappa: number;
  player_scale: number;
  splits: {
    tune_train_through: number;
    tune_valid: number[];
    test: number[];
    served_through: number;
  };
  outcomes: { key: string; label: string }[];
  feature_selection: { variant: string; label: string; log_loss: number }[];
  candidate_min_gain: number;
  phase_players: boolean;
  test: {
    model: BallMetrics;
    situation_only: BallMetrics;
    baseline: BallMetrics;
    by_phase: {
      phase: "powerplay" | "middle" | "death";
      balls: number;
      model_log_loss: number;
      baseline_log_loss: number;
    }[];
    calibration: Record<string, OutcomeCalibration>;
    runs_calibration: { predicted: number; observed: number; count: number }[];
  };
  matchups: {
    kappa: number;
    served_kappa: number;
    pairs_in_history: number;
    test_pairs: number;
    all: HistoryCheck;
    by_history: (HistoryCheck & { history: string })[];
  };
  backtest: { season: number; balls: number; model_log_loss: number; baseline_log_loss: number }[];
}

export const BALL_OUTCOME = ballOutcomeData as unknown as BallOutcomeInsights;
