// Generated by `python -m criciq_api.featured`. Do not edit.
import type { Timeline } from "@/lib/api/types";

export const featuredTimelines: Record<number, () => Promise<Timeline>> = {
  1493281: () => import("./1493281.json").then((m) => m.default as unknown as Timeline),
  1443100: () => import("./1443100.json").then((m) => m.default as unknown as Timeline),
  1386137: () => import("./1386137.json").then((m) => m.default as unknown as Timeline),
  1324684: () => import("./1324684.json").then((m) => m.default as unknown as Timeline),
  1269698: () => import("./1269698.json").then((m) => m.default as unknown as Timeline),
  1226882: () => import("./1226882.json").then((m) => m.default as unknown as Timeline),
};
